### Read 2015-2020 Dungeness csv file extract temp and flow

In [9]:
#imports

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from urllib.request import urlopen
from bs4 import BeautifulSoup
import io
import datetime
import matplotlib.dates as mdates

In [5]:
year = 2015
#csv_name = "C:/Users/maria/OneDrive/Documents/data/pied_piper/"+str(year)+"_Dungeness_all_R.csv"
csv_name = "/home/maria/Documents/data/pied_piper/"+str(year)+"_dungeness_all_R.csv"
df = pd.read_csv(csv_name, header=0)

In [3]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    display(df)

,Unnamed: 0,Down,In,Up,Date,Up_date,Down_time,Up_time,midpoint,steelheadsmolt_wild_perhour,steelheadsmolt_hatchery_perhour,coho1_wild_perhour,coho1_hatchery_perhour,coho0_wild_perhour,chinook1_wild_perhour,chinook1_hatchery_perhour,chinook0_wild_perhour,chinook0_hatchery_perhour
0,1,2015-02-04 08:30:00,24.000000,2015-02-05 08:30:00,2015-02-04,2015-02-05,1899-12-30 08:30:00,1899-12-30 08:30:00,2015-02-04 20:30:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.083333,0.000000
1,2,2015-02-05 08:30:00,8.500000,2015-02-05 17:00:00,2015-02-05,2015-02-05,1899-12-30 08:30:00,1899-12-30 17:00:00,2015-02-05 12:45:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.117647,0.000000
2,3,2015-02-09 06:00:00,12.000000,2015-02-09 18:00:00,2015-02-09,2015-02-09,1899-12-30 06:00:00,1899-12-30 18:00:00,2015-02-09 12:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.083333,0.000000
3,4,2015-02-09 18:00:00,13.500000,2015-02-10 07:30:00,2015-02-09,2015-02-10,1899-12-30 18:00:00,1899-12-30 07:30:00,2015-02-10 00:45:00,0.000000,0.000000,0.222222,0.000000,0.000000,0.000000,0,0.370370,0.000000
4,5,2015-02-10 07:30:00,9.500000,2015-02-10 17:00:00,2015-02-10,2015-02-10,1899-12-30 07:30:00,1899-12-30 17:00:00,2015-02-10 12:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.105263,0.000000
5,6,2015-02-10 17:00:00,14.500000,2015-02-11 07:30:00,2015-02-10,2015-02-11,1899-12-30 17:00:00,1899-12-30 07:30:00,2015-02-11 00:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.275862,0.000000
6,7,2015-02-11 07:30:00,9.500000,2015-02-11 17:00:00,2015-02-11,2015-02-11,1899-12-30 07:30:00,1899-12-30 17:00:00,2015-02-11 12:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.105263,0.000000
7,8,2015-02-11 17:00:00,14.500000,2015-02-12 07:30:00,2015-02-11,2015-02-12,1899-12-30 17:00:00,1899-12-30 07:30:00,2015-02-12 00:15:00,0.000000,0.000000,0.068966,0.000000,0.000000,0.000000,0,0.068966,0.000000
8,9,2015-02-12 07:30:00,9.500000,2015-02-12 17:00:00,2015-02-12,2015-02-12,1899-12-30 07:30:00,1899-12-30 17:00:00,2015-02-12 12:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.210526,0.000000
9,10,2015-02-12 17:00:00,14.000000,2015-02-13 07:00:00,2015-02-12,2015-02-13,1899-12-30 17:00:00,1899-12-30 07:00:00,2015-02-13 00:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.071429,0.000000
10,11,2015-02-13 17:00:00,14.500000,2015-02-14 07:30:00,2015-02-13,2015-02-14,1899-12-30 17:00:00,1899-12-30 07:30:00,2015-02-14 00:15:00,0.000000,0.000000,0.068966,0.000000,0.000000,0.000000,0,0.000000,0.000000
11,12,2015-02-14 07:30:00,9.500000,2015-02-14 17:00:00,2015-02-14,2015-02-14,1899-12-30 07:30:00,1899-12-30 17:00:00,2015-02-14 12:15:00,0.105263,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.105263,0.000000
12,13,2015-02-15 07:30:00,10.750000,2015-02-15 18:15:00,2015-02-15,2015-02-15,1899-12-30 07:30:00,1899-12-30 18:15:00,2015-02-15 12:52:30,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000
13,14,2015-02-15 18:15:00,14.750000,2015-02-16 09:00:00,2015-02-15,2015-02-16,1899-12-30 18:15:00,1899-12-30 09:00:00,2015-02-16 01:37:30,0.000000,0.000000,0.067797,0.000000,0.000000,0.135593,0,0.000000,0.000000
14,15,2015-02-16 09:00:00,9.000000,2015-02-16 18:00:00,2015-02-16,2015-02-16,1899-12-30 09:00:00,1899-12-30 18:00:00,2015-02-16 13:30:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.111111,0,0.000000,0.000000
15,16,2015-02-16 18:00:00,14.000000,2015-02-17 08:00:00,2015-02-16,2015-02-17,1899-12-30 18:00:00,1899-12-30 08:00:00,2015-02-17 01:00:00,0.000000,0.000000,0.071429,0.000000,0.000000,0.071429,0,0.000000,0.000000
16,17,2015-02-19 08:00:00,23.000000,2015-02-20 07:00:00,2015-02-19,2015-02-20,1899-12-30 08:00:00,1899-12-30 07:00:00,2015-02-19 19:30:00,0.000000,0.000000,0.043478,0.000000,0.000000,0.000000,0,0.000000,0.000000
17,18,2015-02-21 07:00:00,24.000000,2015-02-22 07:00:00,2015-02-21,2015-02-22,1899-12-30 07:00:00,1899-12-30 07:00:00,2015-02-21 19:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.041667,0.000000
18,19,2015-02-22 07:00:00,24.000000,2015-02-23 07:00:00,2015-02-22,2015-02-23,1899-12-30 07:00:00,1899-12-30 07:00:00,2015-02-22 19:00:00,0.000000,0.000000,0.041667,0.000000,0.000000,0.000000,0,0.041667,0.000000
19,20,2015-02-23 07:00:00,24.000000,2015-02-24 07:00:00,2015-02-23,2015-02-24,1899-12-30 07:00:00,1899-12-30 07:00:00,2015-02-23 19:00:00,0.000000,0.000000,0.041667,0.000000,0.000000,0.000000,0,0.000000,0.000000
20,21,2015-02-28 08:00:00,24.000000,2015-03-01 08:00:00,2015-02-28,2015-03-01,1899-12-30 08:00:00,1899-12-30 08:00:00,2015-02-28 20:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.041667,0,0.000000,0.000000
21,22,2015-03-02 08:00:00,23.000000,2015-03-03 07:00:00,2015-03-02,2015-03-03,1899-12-30 08:00:00,1899-12-30 07:00:00,2015-03-02 19:30:00,0.000000,0.043478,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000
22,23,2015-03-05 07:00:00,24.000000,2015-03-06 07:00:00,2015-03-05,2015-03-06,1899-12-30 07:00:00,1899-12-30 07:00:00,2015-03-05 19:00:00,0.000000,0.000000,0.041667,0.000000,0.000000,0.000000,0,0.000000,0.000000
23,24,2015-03-06 07:00:00,25.000000,2015-03-07 08:00:00,2015-03-06,2015-03-07,1899-12-30 07:00:00,1899-12-30 08:00:00,2015-03-06 19:30:00,0.000000,0.000000,0.040000,0.000000,0.000000,0.120000,0,0.000000,0.000000
24,25,2015-03-08 08:00:00,11.000000,2015-03-08 19:00:00,2015-03-08,2015-03-08,1899-12-30 08:00:00,1899-12-30 19:00:00,2015-03-08 13:30:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.090909,0.000000
25,26,2015-03-08 19:00:00,14.500000,2015-03-09 09:30:00,2015-03-08,2015-03-09,1899-12-30 19:00:00,1899-12-30 09:30:00,2015-03-09 02:15:00,0.000000,0.000000,0.137931,0.000000,0.000000,0.000000,0,0.000000,0.000000
26,27,2015-03-09 17:45:00,14.250000,2015-03-10 08:00:00,2015-03-09,2015-03-10,1899-12-30 17:45:00,1899-12-30 08:00:00,2015-03-10 00:52:30,0.000000,0.000000,0.000000,0.000000,0.000000,0.070175,0,0.000000,0.000000
27,28,2015-03-10 17:30:00,14.000000,2015-03-11 07:30:00,2015-03-10,2015-03-11,1899-12-30 17:30:00,1899-12-30 07:30:00,2015-03-11 00:30:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.071429,0,0.000000,0.000000
28,29,2015-03-11 17:00:00,13.750000,2015-03-12 06:45:00,2015-03-11,2015-03-12,1899-12-30 17:00:00,1899-12-30 06:45:00,2015-03-11 23:52:30,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.145455,0.000000
29,30,2015-03-13 17:30:00,13.500000,2015-03-14 07:00:00,2015-03-13,2015-03-14,1899-12-30 17:30:00,1899-12-30 07:00:00,2015-03-14 00:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.074074,0.000000
30,31,2015-03-14 18:30:00,14.000000,2015-03-15 08:30:00,2015-03-14,2015-03-15,1899-12-30 18:30:00,1899-12-30 08:30:00,2015-03-15 01:30:00,0.000000,0.000000,0.071429,0.000000,0.000000,0.000000,0,0.000000,0.000000
31,32,2015-03-16 19:00:00,13.500000,2015-03-17 08:30:00,2015-03-16,2015-03-17,1899-12-30 19:00:00,1899-12-30 08:30:00,2015-03-17 01:45:00,0.000000,0.000000,0.074074,0.000000,0.000000,0.000000,0,0.000000,0.000000
32,33,2015-03-18 17:30:00,14.000000,2015-03-19 07:30:00,2015-03-18,2015-03-19,1899-12-30 17:30:00,1899-12-30 07:30:00,2015-03-19 00:30:00,0.000000,0.000000,0.071429,0.000000,0.000000,0.000000,0,0.000000,0.000000
33,34,2015-03-19 18:30:00,13.000000,2015-03-20 07:30:00,2015-03-19,2015-03-20,1899-12-30 18:30:00,1899-12-30 07:30:00,2015-03-20 01:00:00,0.000000,0.000000,0.153846,0.000000,0.000000,0.000000,0,0.076923,0.000000
34,35,2015-03-21 19:00:00,13.000000,2015-03-22 08:00:00,2015-03-21,2015-03-22,1899-12-30 19:00:00,1899-12-30 08:00:00,2015-03-22 01:30:00,0.000000,0.000000,0.153846,0.000000,0.000000,0.000000,0,0.076923,0.000000
35,36,2015-03-23 08:30:00,11.000000,2015-03-23 19:30:00,2015-03-23,2015-03-23,1899-12-30 08:30:00,1899-12-30 19:30:00,2015-03-23 14:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000
36,37,2015-03-23 19:30:00,13.000000,2015-03-24 08:30:00,2015-03-23,2015-03-24,1899-12-30 19:30:00,1899-12-30 08:30:00,2015-03-24 02:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.076923,0.000000
37,38,2015-03-24 19:00:00,13.000000,2015-03-25 08:00:00,2015-03-24,2015-03-25,1899-12-30 19:00:00,1899-12-30 08:00:00,2015-03-25 01:30:00,0.000000,0.000000,0.153846,0.000000,0.000000,0.000000,0,0.230769,0.000000
38,39,2015-03-25 18:30:00,13.500000,2015-03-26 08:00:00,2015-03-25,2015-03-26,1899-12-30 18:30:00,1899-12-30 08:00:00,2015-03-26 01:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.296296,0.000000
39,40,2015-03-26 18:00:00,14.500000,2015-03-27 08:30:00,2015-03-26,2015-03-27,1899-12-30 18:00:00,1899-12-30 08:30:00,2015-03-27 01:15:00,0.000000,0.000000,0.068966,0.000000,0.000000,0.000000,0,0.206897,0.000000
40,41,2015-03-27 18:00:00,14.000000,2015-03-28 08:00:00,2015-03-27,2015-03-28,1899-12-30 18:00:00,1899-12-30 08:00:00,2015-03-28 01:00:00,0.000000,0.000000,0.142857,0.000000,0.000000,0.000000,0,0.142857,0.000000
41,42,2015-03-28 18:00:00,13.500000,2015-03-29 07:30:00,2015-03-28,2015-03-29,1899-12-30 18:00:00,1899-12-30 07:30:00,2015-03-29 00:45:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.074074,0.000000
42,43,2015-03-29 18:30:00,13.000000,2015-03-30 07:30:00,2015-03-29,2015-03-30,1899-12-30 18:30:00,1899-12-30 07:30:00,2015-03-30 01:00:00,0.000000,0.000000,0.153846,0.000000,0.000000,0.000000,0,0.000000,0.000000
43,44,2015-03-30 18:30:00,14.000000,2015-03-31 08:30:00,2015-03-30,2015-03-31,1899-12-30 18:30:00,1899-12-30 08:30:00,2015-03-31 01:30:00,0.000000,0.000000,0.214286,0.000000,0.000000,0.000000,0,0.142857,0.000000
44,45,2015-03-31 18:00:00,13.000000,2015-04-01 07:00:00,2015-03-31,2015-04-01,1899-12-30 18:00:00,1899-12-30 07:00:00,2015-04-01 00:30:00,0.000000,0.000000,0.153846,0.000000,0.000000,0.000000,0,0.230769,0.000000
45,46,2015-04-01 19:30:00,11.000000,2015-04-02 06:30:00,2015-04-01,2015-04-02,1899-12-30 19:30:00,1899-12-30 06:30:00,2015-04-02 01:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.090909,0.000000
46,47,2015-04-03 19:30:00,12.500000,2015-04-04 08:00:00,2015-04-03,2015-04-04,1899-12-30 19:30:00,1899-12-30 08:00:00,2015-04-04 01:45:00,0.000000,0.000000,0.080000,0.000000,0.000000,0.000000,0,0.000000,0.000000
47,48,2015-04-04 19:30:00,12.500000,2015-04-05 08:00:00,2015-04-04,2015-04-05,1899-12-30 19:30:00,1899-12-30 08:00:00,2015-04-05 01:45:00,0.080000,0.000000,0.000000,0.000000,0.000000,0.080000,0,0.000000,0.000000
48,49,2015-04-05 19:00:00,13.500000,2015-04-06 08:30:00,2015-04-05,2015-04-06,1899-12-30 19:00:00,1899-12-30 08:30:00,2015-04-06 01:45:00,0.000000,0.074074,0.000000,0.000000,0.000000,0.000000,0,0.074074,0.000000
49,50,2015-04-05 19:00:00,13.500000,2015-04-06 08:30:00,2015-04-05,2015-04-06,1899-12-30 19:00:00,1899-12-30 08:30:00,2015-04-06 01:45:00,0.000000,0.074074,0.000000,0.000000,0.000000,0.000000,0,0.074074,0.000000
50,51,2015-04-06 18:30:00,13.000000,2015-04-07 07:30:00,2015-04-06,2015-04-07,1899-12-30 18:30:00,1899-12-30 07:30:00,2015-04-07 01:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.153846,0.000000
51,52,2015-04-07 17:00:00,16.250000,2015-04-08 09:15:00,2015-04-07,2015-04-08,1899-12-30 17:00:00,1899-12-30 09:15:00,2015-04-08 01:07:30,0.000000,0.000000,0.061538,0.000000,0.000000,0.000000,0,0.123077,0.000000
52,53,2015-04-08 18:00:00,13.500000,2015-04-09 07:30:00,2015-04-08,2015-04-09,1899-12-30 18:00:00,1899-12-30 07:30:00,2015-04-09 00:45:00,0.000000,0.000000,0.222222,0.000000,0.000000,0.000000,0,0.148148,0.000000
53,54,2015-04-09 18:00:00,13.000000,2015-04-10 07:00:00,2015-04-09,2015-04-10,1899-12-30 18:00:00,1899-12-30 07:00:00,2015-04-10 00:30:00,0.000000,0.000000,0.307692,0.000000,0.000000,0.153846,0,0.153846,0.000000
54,55,2015-04-10 20:00:00,13.000000,2015-04-11 09:00:00,2015-04-10,2015-04-11,1899-12-30 20:00:00,1899-12-30 09:00:00,2015-04-11 02:30:00,0.076923,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.230769,0.000000
55,56,2015-04-11 18:30:00,13.500000,2015-04-12 08:00:00,2015-04-11,2015-04-12,1899-12-30 18:30:00,1899-12-30 08:00:00,2015-04-12 01:15:00,0.000000,0.000000,0.074074,0.000000,0.000000,0.000000,0,0.148148,0.000000
56,57,2015-04-12 19:30:00,12.500000,2015-04-13 08:00:00,2015-04-12,2015-04-13,1899-12-30 19:30:00,1899-12-30 08:00:00,2015-04-13 01:45:00,0.080000,0.080000,0.080000,0.000000,0.000000,0.000000,0,0.000000,0.000000
57,58,2015-04-13 20:00:00,12.000000,2015-04-14 08:00:00,2015-04-13,2015-04-14,1899-12-30 20:00:00,1899-12-30 08:00:00,2015-04-14 02:00:00,0.083333,0.000000,0.000000,0.083333,0.000000,0.000000,0,0.250000,0.000000
58,59,2015-04-14 20:00:00,12.000000,2015-04-15 08:00:00,2015-04-14,2015-04-15,1899-12-30 20:00:00,1899-12-30 08:00:00,2015-04-15 02:00:00,0.250000,0.000000,0.166667,0.000000,0.000000,0.166667,0,0.000000,0.000000
59,60,2015-04-15 20:00:00,12.000000,2015-04-16 08:00:00,2015-04-15,2015-04-16,1899-12-30 20:00:00,1899-12-30 08:00:00,2015-04-16 02:00:00,0.416667,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000
60,61,2015-04-16 18:00:00,14.000000,2015-04-17 08:00:00,2015-04-16,2015-04-17,1899-12-30 18:00:00,1899-12-30 08:00:00,2015-04-17 01:00:00,0.357143,0.000000,0.000000,0.000000,0.000000,0.071429,0,0.000000,0.000000
61,62,2015-04-17 18:00:00,15.000000,2015-04-18 09:00:00,2015-04-17,2015-04-18,1899-12-30 18:00:00,1899-12-30 09:00:00,2015-04-18 01:30:00,0.133333,0.000000,0.066667,0.000000,0.000000,0.066667,0,0.066667,0.000000
62,63,2015-04-18 20:15:00,11.750000,2015-04-19 08:00:00,2015-04-18,2015-04-19,1899-12-30 20:15:00,1899-12-30 08:00:00,2015-04-19 02:07:30,0.170213,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000
63,64,2015-04-19 19:15:00,12.750000,2015-04-20 08:00:00,2015-04-19,2015-04-20,1899-12-30 19:15:00,1899-12-30 08:00:00,2015-04-20 01:37:30,0.000000,0.000000,0.156863,0.000000,0.000000,0.078431,0,0.000000,0.000000
64,65,2015-04-21 20:30:00,11.500000,2015-04-22 08:00:00,2015-04-21,2015-04-22,1899-12-30 20:30:00,1899-12-30 08:00:00,2015-04-22 02:15:00,0.347826,0.086957,0.000000,0.000000,0.000000,0.086957,0,0.086957,0.000000
65,66,2015-04-22 17:30:00,14.500000,2015-04-23 08:00:00,2015-04-22,2015-04-23,1899-12-30 17:30:00,1899-12-30 08:00:00,2015-04-23 00:45:00,0.068966,0.000000,0.344828,0.000000,0.000000,0.000000,0,0.068966,0.000000
66,67,2015-04-23 20:00:00,12.000000,2015-04-24 08:00:00,2015-04-23,2015-04-24,1899-12-30 20:00:00,1899-12-30 08:00:00,2015-04-24 02:00:00,0.166667,0.000000,0.333333,0.000000,0.000000,0.083333,0,0.166667,0.000000
67,68,2015-04-24 20:30:00,11.500000,2015-04-25 08:00:00,2015-04-24,2015-04-25,1899-12-30 20:30:00,1899-12-30 08:00:00,2015-04-25 02:15:00,0.434783,0.000000,0.521739,0.000000,0.000000,0.000000,0,0.086957,0.000000
68,69,2015-04-24 20:30:00,11.500000,2015-04-25 08:00:00,2015-04-24,2015-04-25,1899-12-30 20:30:00,1899-12-30 08:00:00,2015-04-25 02:15:00,0.086957,0.000000,0.521739,0.000000,0.000000,0.000000,0,0.086957,0.000000
69,70,2015-04-25 20:30:00,11.500000,2015-04-26 08:00:00,2015-04-25,2015-04-26,1899-12-30 20:30:00,1899-12-30 08:00:00,2015-04-26 02:15:00,0.347826,0.000000,0.347826,0.000000,0.000000,0.173913,0,0.000000,0.000000
70,71,2015-04-26 19:00:00,13.000000,2015-04-27 08:00:00,2015-04-26,2015-04-27,1899-12-30 19:00:00,1899-12-30 08:00:00,2015-04-27 01:30:00,0.307692,0.000000,0.076923,0.000000,0.000000,0.000000,0,0.000000,0.000000
71,72,2015-04-27 08:00:00,12.000000,2015-04-27 20:00:00,2015-04-27,2015-04-27,1899-12-30 08:00:00,1899-12-30 20:00:00,2015-04-27 14:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000
72,73,2015-04-27 20:00:00,12.000000,2015-04-28 08:00:00,2015-04-27,2015-04-28,1899-12-30 20:00:00,1899-12-30 08:00:00,2015-04-28 02:00:00,0.250000,0.000000,0.000000,0.000000,0.000000,0.083333,0,0.000000,0.000000
73,74,2015-04-29 17:30:00,14.500000,2015-04-30 08:00:00,2015-04-29,2015-04-30,1899-12-30 17:30:00,1899-12-30 08:00:00,2015-04-30 00:45:00,0.206897,0.000000,0.275862,0.000000,0.000000,0.000000,0,0.068966,0.000000
74,75,2015-04-30 20:00:00,12.000000,2015-05-01 08:00:00,2015-04-30,2015-05-01,1899-12-30 20:00:00,1899-12-30 08:00:00,2015-05-01 02:00:00,0.250000,0.000000,0.083333,0.000000,0.000000,0.000000,0,0.000000,0.000000
75,76,2015-05-01 16:30:00,14.000000,2015-05-02 06:30:00,2015-05-01,2015-05-02,1899-12-30 16:30:00,1899-12-30 06:30:00,2015-05-01 23:30:00,0.071429,0.000000,0.142857,0.000000,0.000000,0.000000,0,0.000000,0.000000
76,77,2015-05-01 16:30:00,14.000000,2015-05-02 06:30:00,2015-05-01,2015-05-02,1899-12-30 16:30:00,1899-12-30 06:30:00,2015-05-01 23:30:00,0.071429,0.000000,0.071429,0.000000,0.000000,0.000000,0,0.000000,0.000000
77,78,2015-05-02 21:00:00,11.000000,2015-05-03 08:00:00,2015-05-02,2015-05-03,1899-12-30 21:00:00,1899-12-30 08:00:00,2015-05-03 02:30:00,0.636364,0.000000,0.545455,0.000000,0.000000,0.000000,0,0.000000,0.000000
78,79,2015-05-02 21:00:00,11.000000,2015-05-03 08:00:00,2015-05-02,2015-05-03,1899-12-30 21:00:00,1899-12-30 08:00:00,2015-05-03 02:30:00,0.636364,0.000000,0.181818,0.000000,0.000000,0.000000,0,0.000000,0.000000
79,80,2015-05-03 08:00:00,11.000000,2015-05-03 19:00:00,2015-05-03,2015-05-03,1899-12-30 08:00:00,1899-12-30 19:00:00,2015-05-03 13:30:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000
80,81,2015-05-03 19:00:00,13.000000,2015-05-04 08:00:00,2015-05-03,2015-05-04,1899-12-30 19:00:00,1899-12-30 08:00:00,2015-05-04 01:30:00,0.538462,0.000000,0.538462,0.000000,0.000000,0.000000,0,0.076923,0.000000
81,82,2015-05-03 19:00:00,13.000000,2015-05-04 08:00:00,2015-05-03,2015-05-04,1899-12-30 19:00:00,1899-12-30 08:00:00,2015-05-04 01:30:00,0.538462,0.000000,0.230769,0.000000,0.000000,0.000000,0,0.076923,0.000000
82,83,2015-05-04 20:00:00,13.000000,2015-05-05 09:00:00,2015-05-04,2015-05-05,1899-12-30 20:00:00,1899-12-30 09:00:00,2015-05-05 02:30:00,0.230769,0.000000,0.153846,0.000000,0.000000,0.000000,0,0.153846,0.000000
83,84,2015-05-05 19:45:00,12.500000,2015-05-06 08:15:00,2015-05-05,2015-05-06,1899-12-30 19:45:00,1899-12-30 08:15:00,2015-05-06 02:00:00,1.040000,0.000000,0.320000,0.000000,0.000000,0.000000,0,0.240000,0.000000
84,85,2015-05-05 19:45:00,12.500000,2015-05-06 08:15:00,2015-05-05,2015-05-06,1899-12-30 19:45:00,1899-12-30 08:15:00,2015-05-06 02:00:00,1.040000,0.000000,0.160000,0.000000,0.000000,0.000000,0,0.240000,0.000000
85,86,2015-05-06 21:00:00,11.000000,2015-05-07 08:00:00,2015-05-06,2015-05-07,1899-12-30 21:00:00,1899-12-30 08:00:00,2015-05-07 02:30:00,0.181818,0.090909,0.272727,0.000000,0.000000,0.000000,0,0.090909,0.000000
86,87,2015-05-06 21:00:00,11.000000,2015-05-07 08:00:00,2015-05-06,2015-05-07,1899-12-30 21:00:00,1899-12-30 08:00:00,2015-05-07 02:30:00,0.181818,0.090909,0.909091,0.000000,0.000000,0.000000,0,0.090909,0.000000
87,88,2015-05-06 21:00:00,11.000000,2015-05-07 08:00:00,2015-05-06,2015-05-07,1899-12-30 21:00:00,1899-12-30 08:00:00,2015-05-07 02:30:00,2.181818,0.090909,0.272727,0.000000,0.000000,0.000000,0,0.090909,0.000000
88,89,2015-05-06 21:00:00,11.000000,2015-05-07 08:00:00,2015-05-06,2015-05-07,1899-12-30 21:00:00,1899-12-30 08:00:00,2015-05-07 02:30:00,2.181818,0.090909,0.909091,0.000000,0.000000,0.000000,0,0.090909,0.000000
89,90,2015-05-07 08:00:00,10.500000,2015-05-07 18:30:00,2015-05-07,2015-05-07,1899-12-30 08:00:00,1899-12-30 18:30:00,2015-05-07 13:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000
90,91,2015-05-07 18:30:00,13.000000,2015-05-08 07:30:00,2015-05-07,2015-05-08,1899-12-30 18:30:00,1899-12-30 07:30:00,2015-05-08 01:00:00,0.230769,0.000000,1.230769,0.000000,0.000000,0.000000,0,0.076923,0.000000
91,92,2015-05-07 18:30:00,13.000000,2015-05-08 07:30:00,2015-05-07,2015-05-08,1899-12-30 18:30:00,1899-12-30 07:30:00,2015-05-08 01:00:00,0.230769,0.000000,0.769231,0.000000,0.000000,0.000000,0,0.076923,0.000000
92,93,2015-05-07 18:30:00,13.000000,2015-05-08 07:30:00,2015-05-07,2015-05-08,1899-12-30 18:30:00,1899-12-30 07:30:00,2015-05-08 01:00:00,1.461538,0.000000,1.230769,0.000000,0.000000,0.000000,0,0.076923,0.000000

In [5]:
#getting flow data
#reading html data
year = "2015"

# url = "https://apps.ecology.wa.gov/ContinuousFlowAndWQ/StationData/Prod/18A050/18A050_" + year + "_WTM_FM.TXT"
# html = urlopen(url).read()
# soup = BeautifulSoup(html, features="html.parser")

# # kill all script and style elements
# for script in soup(["script", "style"]):
#     script.extract()    # rip it out

# # get text
# text = soup.get_text()
url_flow = "https://apps.ecology.wa.gov/ContinuousFlowAndWQ/StationData/Prod/18A050/18A050_" + year+ "_DSG_FM.TXT"
html_flow = urlopen(url_flow).read()
soup_flow = BeautifulSoup(html_flow, features="html.parser")

# kill all script and style elements
for script in soup_flow(["script", "style"]):
    script.extract()    # rip it out


text_flow = soup_flow.get_text()
# text_flow = text_flow[519:-135]

# df_flow = pd.read_csv(io.StringIO(text_flow), sep='\s+', header = None, names = ["date", "time", "flow", "quality"])
# df_flow['midpoint'] =  pd.to_datetime(df_flow['date'] + ' ' + df_flow['time'])

In [19]:
# 2018 : 519:-153
# 2019 : 519:-119
# 2020 : 519:-119

def flow_data(year):
    url_flow = "https://apps.ecology.wa.gov/ContinuousFlowAndWQ/StationData/Prod/18A050/18A050_" + str(year)+ "_DSG_FM.TXT"
    html_flow = urlopen(url_flow).read()
    soup_flow = BeautifulSoup(html_flow, features="html.parser")

    # kill all script and style elements
    for script in soup_flow(["script", "style"]):
        script.extract()    # rip it out


    text_flow = soup_flow.get_text()
    
    if str(year) == "2017":
        text_flow = text_flow[519:-135]
    elif str(year) == "2018":
        text_flow = text_flow[519:-153]
    elif str(year) == "2019":
        text_flow = text_flow[519:-119]
    elif str(year) == "2020":
        text_flow = text_flow[519:-119]
    elif str(year) == "2016":
        text_flow = text_flow[519:-210]
    elif str(year) == "2015":
        text_flow = text_flow[519:-203]
        
    df_flow = pd.read_csv(io.StringIO(text_flow), sep='\s+', header = None, names = ["date", "time", "flow", "quality"])
    df_flow['midpoint'] =  pd.to_datetime(df_flow['date'] + ' ' + df_flow['time'])
    
    return(df_flow)

In [7]:
def read_csv(year):
    csv_name = "C:/Users/maria/OneDrive/Documents/data/pied_piper/"+str(year)+"_dungeness_all_R.csv"
    df = pd.read_csv(csv_name, header=0)
    df['midpoint'] = pd.to_datetime(df['midpoint'])
    
    df_flow = flow_data(year)
    df_year_flow = pd.merge_asof(
        df.dropna(subset = ['midpoint']),df_flow, on="midpoint",tolerance=pd.Timedelta(minutes = 15))
    df_year_flow.to_csv("C:/Users/maria/OneDrive/Documents/data/pied_piper/" + str(year) + "_dungeness_all.csv")
    return(df_year_flow)

In [8]:
df_year_flow = read_csv(2016)

with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    display(df_year_flow)

FileNotFoundError: [Errno 2] File C:/Users/maria/OneDrive/Documents/data/pied_piper/2016_dungeness_all_R.csv does not exist: 'C:/Users/maria/OneDrive/Documents/data/pied_piper/2016_dungeness_all_R.csv'

In [27]:
#aggregating data
def aggregate(year):
    csv_name = "C:/Users/maria/OneDrive/Documents/data/pied_piper/"+str(year)+"_dungeness_all.csv"
    df_year_flow = pd.read_csv(csv_name, header=0)
    groupedby_dates_year = df_year_flow.groupby(by=["Date"]).agg({'In':'sum',
                                                                       'chinook0_hatchery_perhour':'sum',
                                                                       'chinook0_wild_perhour':'sum',
                                                                       'chinook1_hatchery_perhour':'sum',
                                                                       'chinook1_wild_perhour':'sum',
                                                                       'coho1_hatchery_perhour':'sum',
                                                                       'coho1_wild_perhour':'sum',
                                                                       'steelheadsmolt_hatchery_perhour':'sum',
                                                                       'steelheadsmolt_wild_perhour':'sum',
                                                                       'flow':'mean'})
    groupedby_dates_year.to_csv("C:/Users/maria/OneDrive/Documents/data/pied_piper/"+str(year)+"_dungeness.csv") 
# with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
#     display(groupedby_dates_year)

In [36]:
aggregate(2020)