### To attach temperature data to nisqually data files

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sys import platform

In [3]:
if platform == "linux" or platform == "linux2":
    data_string = "/home/maria/Documents/data/pied_piper/nisqually/"
    output_String = "/home/maria/Documents/output/pied_piper/nisqually/"
else:
    data_string = "C:/Users/maria/OneDrive/Documents/data/pied_piper/"
    output_string = "C:/Users/maria/OneDrive/Documents/output/pied_piper/"

In [14]:
year = "2020"
df = pd.read_csv(data_string + year + "_nisqually_all_R_new.csv")
with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    display(df)

,Unnamed: 0,Down,In,Up,Date,Up_date,Down_time,Up_time,midpoint,pink1_wild_perhour,pink1_wild_num,pink1_hatchery_perhour,pink1_hatchery_num,pink0_wild_perhour,pink0_wild_num,pink0_hatchery_perhour,pink0_hatchery_num,chum1_wild_perhour,chum1_wild_num,chum1_hatchery_perhour,chum1_hatchery_num,chum0_wild_perhour,chum0_wild_num,chum0_hatchery_perhour,chum0_hatchery_num,steelheadsmolt_wild_perhour,steelheadsmolt_wild_num,steelheadsmolt_hatchery_perhour,steelheadsmolt_hatchery_num,coho1_wild_perhour,coho1_wild_num,coho1_hatchery_perhour,coho1_hatchery_num,coho0_wild_perhour,coho0_wild_num,coho0_hatchery_perhour,coho0_hatchery_num,chinook1_wild_perhour,chinook1_wild_num,chinook1_hatchery_perhour,chinook1_hatchery_num,chinook0_wild_perhour,chinook0_wild_num,chinook0_hatchery_perhour,chinook0_hatchery_num
0,1,2020-01-02 12:30:00,20.750000,2020-01-03 09:15:00,2020-01-02,2020-01-03,1899-12-30 12:30:00,1899-12-30 09:15:00,2020-01-02 22:52:30,0,0,0,0,0.000000,0,0,0,0,0,0,0,0.000000,0,0,0,0.289157,6,0,0,0.240964,5,0,0,0.000000,0,0,0,0.048193,1,0,0,1.048193,2,0.000000,0
1,2,2020-01-03 09:15:00,23.250000,2020-01-04 08:30:00,2020-01-03,2020-01-04,1899-12-30 09:15:00,1899-12-30 08:30:00,2020-01-03 20:52:30,0,0,0,0,0.000000,0,0,0,0,0,0,0,0.000000,0,0,0,0.043011,1,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.043011,1,0.000000,0
2,3,2020-01-04 08:30:00,24.000000,2020-01-05 08:30:00,2020-01-04,2020-01-05,1899-12-30 08:30:00,1899-12-30 08:30:00,2020-01-04 20:30:00,0,0,0,0,0.000000,0,0,0,0,0,0,0,0.000000,0,0,0,0.083333,2,0,0,0.083333,2,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0.000000,0
3,4,2020-01-05 08:30:00,25.250000,2020-01-06 09:45:00,2020-01-05,2020-01-06,1899-12-30 08:30:00,1899-12-30 09:45:00,2020-01-05 21:07:30,0,0,0,0,0.000000,0,0,0,0,0,0,0,0.000000,0,0,0,0.079208,2,0,0,0.039604,1,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0.000000,0
4,5,2020-01-06 09:45:00,11.250000,2020-01-06 21:00:00,2020-01-06,2020-01-06,1899-12-30 09:45:00,1899-12-30 21:00:00,2020-01-06 15:22:30,0,0,0,0,0.000000,0,0,0,0,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.088889,1,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0.000000,0
5,6,2020-01-08 11:45:00,22.000000,2020-01-09 09:45:00,2020-01-08,2020-01-09,1899-12-30 11:45:00,1899-12-30 09:45:00,2020-01-08 22:45:00,0,0,0,0,1.045455,2,0,0,0,0,0,0,0.045455,1,0,0,0.363636,8,0,0,0.272727,6,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0.000000,0
6,7,2020-01-09 09:45:00,23.750000,2020-01-10 09:30:00,2020-01-09,2020-01-10,1899-12-30 09:45:00,1899-12-30 09:30:00,2020-01-09 21:37:30,0,0,0,0,0.042105,1,0,0,0,0,0,0,0.000000,0,0,0,0.042105,1,0,0,0.000000,0,0,0,0.000000,0,0,0,0.168421,4,0,0,0.000000,0,0.000000,0
7,8,2020-01-13 10:45:00,22.500000,2020-01-14 09:15:00,2020-01-13,2020-01-14,1899-12-30 10:45:00,1899-12-30 09:15:00,2020-01-13 22:00:00,0,0,0,0,0.000000,0,0,0,0,0,0,0,0.000000,0,0,0,0.088889,2,0,0,0.088889,2,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0.000000,0
8,9,2020-01-14 09:15:00,25.250000,2020-01-15 10:30:00,2020-01-14,2020-01-15,1899-12-30 09:15:00,1899-12-30 10:30:00,2020-01-14 21:52:30,0,0,0,0,0.118812,3,0,0,0,0,0,0,0.000000,0,0,0,0.316832,8,0,0,0.118812,3,0,0,0.000000,0,0,0,0.079208,2,0,0,0.000000,0,0.000000,0
9,10,2020-01-15 10:30:00,22.500000,2020-01-16 09:00:00,2020-01-15,2020-01-16,1899-12-30 10:30:00,1899-12-30 09:00:00,2020-01-15 21:45:00,0,0,0,0,0.000000,0,0,0,0,0,0,0,0.000000,0,0,0,0.222222,5,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0.000000,0
10,11,2020-01-16 09:00:00,26.000000,2020-01-17 11:00:00,2020-01-16,2020-01-17,1899-12-30 09:00:00,1899-12-30 11:00:00,2020-01-16 22:00:00,0,0,0,0,0.000000,0,0,0,0,0,0,0,0.000000,0,0,0,0.038462,1,0,0,0.076923,2,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0.000000,0
11,12,2020-01-17 11:00:00,21.500000,2020-01-18 08:30:00,2020-01-17,2020-01-18,1899-12-30 11:00:00,1899-12-30 08:30:00,2020-01-17 21:45:00,0,0,0,0,0.046512,1,0,0,0,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.046512,1,0,0,0.000000,0,0,0,0.046512,1,0,0,0.046512,1,0.000000,0
12,13,2020-01-18 08:30:00,24.000000,2020-01-19 08:30:00,2020-01-18,2020-01-19,1899-12-30 08:30:00,1899-12-30 08:30:00,2020-01-18 20:30:00,0,0,0,0,0.125000,3,0,0,0,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.083333,2,0,0,0.041667,1,0.000000,0
13,14,2020-01-19 08:30:00,24.000000,2020-01-20 08:30:00,2020-01-19,2020-01-20,1899-12-30 08:30:00,1899-12-30 08:30:00,2020-01-19 20:30:00,0,0,0,0,0.083333,2,0,0,0,0,0,0,0.000000,0,0,0,0.041667,1,0,0,0.041667,1,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0.000000,0
14,15,2020-01-20 08:30:00,23.750000,2020-01-21 08:15:00,2020-01-20,2020-01-21,1899-12-30 08:30:00,1899-12-30 08:15:00,2020-01-20 20:22:30,0,0,0,0,0.168421,4,0,0,0,0,0,0,0.000000,0,0,0,0.126316,3,0,0,0.084211,2,0,0,0.000000,0,0,0,0.042105,1,0,0,0.042105,1,0.000000,0
15,16,2020-01-21 08:15:00,24.750000,2020-01-22 09:00:00,2020-01-21,2020-01-22,1899-12-30 08:15:00,1899-12-30 09:00:00,2020-01-21 20:37:30,0,0,0,0,0.282828,7,0,0,0,0,0,0,0.000000,0,0,0,0.040404,1,0,0,0.040404,1,0,0,0.000000,0,0,0,0.000000,0,0,0,0.080808,2,0.000000,0
16,17,2020-01-22 09:00:00,24.500000,2020-01-23 09:30:00,2020-01-22,2020-01-23,1899-12-30 09:00:00,1899-12-30 09:30:00,2020-01-22 21:15:00,0,0,0,0,1.326531,9,0,0,0,0,0,0,0.000000,0,0,0,0.081633,2,0,0,0.040816,1,0,0,0.000000,0,0,0,0.040816,1,0,0,0.000000,0,0.000000,0
17,18,2020-01-25 12:00:00,21.500000,2020-01-26 09:30:00,2020-01-25,2020-01-26,1899-12-30 12:00:00,1899-12-30 09:30:00,2020-01-25 22:45:00,0,0,0,0,1.674419,36,0,0,0,0,0,0,0.000000,0,0,0,0.046512,1,0,0,0.186047,4,0,0,0.000000,0,0,0,0.139535,3,0,0,0.000000,0,0.000000,0
18,19,2020-01-26 09:30:00,23.750000,2020-01-27 09:15:00,2020-01-26,2020-01-27,1899-12-30 09:30:00,1899-12-30 09:15:00,2020-01-26 21:22:30,0,0,0,0,1.389474,33,0,0,0,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.210526,5,0,0,0.000000,0,0,0,0.042105,1,0,0,0.126316,3,0.000000,0
19,20,2020-01-27 09:15:00,24.000000,2020-01-28 09:15:00,2020-01-27,2020-01-28,1899-12-30 09:15:00,1899-12-30 09:15:00,2020-01-27 21:15:00,0,0,0,0,0.458333,11,0,0,0,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.041667,1,0,0,0.000000,0,0,0,0.000000,0,0,0,0.041667,1,0.000000,0
20,21,2020-02-04 10:30:00,6.500000,2020-02-04 17:00:00,2020-02-04,2020-02-04,1899-12-30 10:30:00,1899-12-30 17:00:00,2020-02-04 13:45:00,0,0,0,0,0.461538,3,0,0,0,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0.000000,0
21,22,2020-02-11 11:30:00,22.500000,2020-02-12 10:00:00,2020-02-11,2020-02-12,1899-12-30 11:30:00,1899-12-30 10:00:00,2020-02-11 22:45:00,0,0,0,0,2.133333,48,0,0,0,0,0,0,0.000000,0,0,0,0.044444,1,0,0,0.488889,11,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0.000000,0
22,23,2020-02-12 10:00:00,23.000000,2020-02-13 09:00:00,2020-02-12,2020-02-13,1899-12-30 10:00:00,1899-12-30 09:00:00,2020-02-12 21:30:00,0,0,0,0,1.391304,32,0,0,0,0,0,0,0.000000,0,0,0,0.043478,1,0,0,1.391304,10,0,0,0.000000,0,0,0,0.000000,0,0,0,0.043478,1,0.000000,0
23,24,2020-02-13 09:00:00,24.000000,2020-02-14 09:00:00,2020-02-13,2020-02-14,1899-12-30 09:00:00,1899-12-30 09:00:00,2020-02-13 21:00:00,0,0,0,0,1.125000,27,0,0,0,0,0,0,0.000000,0,0,0,0.041667,1,0,0,0.166667,4,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0.000000,0
24,25,2020-02-14 09:00:00,24.500000,2020-02-15 09:30:00,2020-02-14,2020-02-15,1899-12-30 09:00:00,1899-12-30 09:30:00,2020-02-14 21:15:00,0,0,0,0,1.612245,16,0,0,0,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.081633,2,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0.000000,0
25,26,2020-02-15 09:30:00,24.000000,2020-02-16 09:30:00,2020-02-15,2020-02-16,1899-12-30 09:30:00,1899-12-30 09:30:00,2020-02-15 21:30:00,0,0,0,0,0.500000,12,0,0,0,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0.000000,0
26,27,2020-02-16 09:30:00,23.750000,2020-02-17 09:15:00,2020-02-16,2020-02-17,1899-12-30 09:30:00,1899-12-30 09:15:00,2020-02-16 21:22:30,0,0,0,0,0.463158,11,0,0,0,0,0,0,0.000000,0,0,0,0.042105,1,0,0,0.252632,6,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0.000000,0
27,28,2020-02-17 09:15:00,24.000000,2020-02-18 09:15:00,2020-02-17,2020-02-18,1899-12-30 09:15:00,1899-12-30 09:15:00,2020-02-17 21:15:00,0,0,0,0,0.708333,17,0,0,0,0,0,0,0.000000,0,0,0,0.083333,2,0,0,0.291667,7,0,0,0.000000,0,0,0,0.000000,0,0,0,0.125000,3,0.000000,0
28,29,2020-02-18 09:15:00,24.000000,2020-02-19 09:15:00,2020-02-18,2020-02-19,1899-12-30 09:15:00,1899-12-30 09:15:00,2020-02-18 21:15:00,0,0,0,0,1.500000,13,0,0,0,0,0,0,0.000000,0,0,0,0.125000,3,0,0,0.083333,2,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0.000000,0
29,30,2020-02-19 09:15:00,24.000000,2020-02-20 09:15:00,2020-02-19,2020-02-20,1899-12-30 09:15:00,1899-12-30 09:15:00,2020-02-19 21:15:00,0,0,0,0,0.333333,8,0,0,0,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.416667,10,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0.000000,0
30,31,2020-02-20 09:15:00,24.250000,2020-02-21 09:30:00,2020-02-20,2020-02-21,1899-12-30 09:15:00,1899-12-30 09:30:00,2020-02-20 21:22:30,0,0,0,0,0.041237,1,0,0,0,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.206186,5,0,0,0.000000,0,0,0,0.000000,0,0,0,0.041237,1,0.000000,0
31,32,2020-02-21 09:30:00,24.000000,2020-02-22 09:30:00,2020-02-21,2020-02-22,1899-12-30 09:30:00,1899-12-30 09:30:00,2020-02-21 21:30:00,0,0,0,0,0.041667,1,0,0,0,0,0,0,0.000000,0,0,0,0.000000,0,0,0,1.083333,26,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0.000000,0
32,33,2020-02-22 09:30:00,23.000000,2020-02-23 08:30:00,2020-02-22,2020-02-23,1899-12-30 09:30:00,1899-12-30 08:30:00,2020-02-22 21:00:00,0,0,0,0,0.173913,4,0,0,0,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.478261,11,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0.000000,0
33,34,2020-02-23 08:30:00,24.750000,2020-02-24 09:15:00,2020-02-23,2020-02-24,1899-12-30 08:30:00,1899-12-30 09:15:00,2020-02-23 20:52:30,0,0,0,0,0.161616,4,0,0,0,0,0,0,0.000000,0,0,0,0.121212,3,0,0,0.363636,9,0,0,0.000000,0,0,0,0.000000,0,0,0,0.040404,1,0.000000,0
34,35,2020-02-24 09:15:00,24.000000,2020-02-25 09:15:00,2020-02-24,2020-02-25,1899-12-30 09:15:00,1899-12-30 09:15:00,2020-02-24 21:15:00,0,0,0,0,0.000000,0,0,0,0,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.500000,12,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0.000000,0
35,36,2020-02-25 09:15:00,24.000000,2020-02-26 09:15:00,2020-02-25,2020-02-26,1899-12-30 09:15:00,1899-12-30 09:15:00,2020-02-25 21:15:00,0,0,0,0,0.041667,1,0,0,0,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.166667,4,0,0,0.000000,0,0,0,0.041667,1,0,0,0.000000,0,0.000000,0
36,37,2020-02-26 09:15:00,24.000000,2020-02-27 09:15:00,2020-02-26,2020-02-27,1899-12-30 09:15:00,1899-12-30 09:15:00,2020-02-26 21:15:00,0,0,0,0,0.458333,11,0,0,0,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.208333,5,0,0,0.000000,0,0,0,0.041667,1,0,0,0.000000,0,0.000000,0
37,38,2020-02-27 09:15:00,24.000000,2020-02-28 09:15:00,2020-02-27,2020-02-28,1899-12-30 09:15:00,1899-12-30 09:15:00,2020-02-27 21:15:00,0,0,0,0,0.458333,11,0,0,0,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.750000,18,0,0,0.000000,0,0,0,0.041667,1,0,0,0.041667,1,0.000000,0
38,39,2020-02-28 09:15:00,23.500000,2020-02-29 08:45:00,2020-02-28,2020-02-29,1899-12-30 09:15:00,1899-12-30 08:45:00,2020-02-28 21:00:00,0,0,0,0,0.085106,2,0,0,0,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.765957,18,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0.000000,0
39,40,2020-02-29 08:45:00,26.000000,2020-03-01 10:45:00,2020-02-29,2020-03-01,1899-12-30 08:45:00,1899-12-30 10:45:00,2020-02-29 21:45:00,0,0,0,0,0.192308,5,0,0,0,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.230769,6,0,0,0.000000,0,0,0,0.038462,1,0,0,0.000000,0,0.000000,0
40,41,2020-03-01 10:45:00,22.500000,2020-03-02 09:15:00,2020-03-01,2020-03-02,1899-12-30 10:45:00,1899-12-30 09:15:00,2020-03-01 22:00:00,0,0,0,0,0.044444,1,0,0,0,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.133333,3,0,0,0.000000,0,0,0,0.044444,1,0,0,0.000000,0,0.000000,0
41,42,2020-03-02 09:15:00,24.416667,2020-03-03 09:40:00,2020-03-02,2020-03-03,1899-12-30 09:15:00,1899-12-30 09:40:00,2020-03-02 21:27:30,0,0,0,0,0.122867,3,0,0,0,0,0,0,0.000000,0,0,0,0.081911,2,0,0,0.204778,5,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0.000000,0
42,43,2020-03-03 09:40:00,24.333333,2020-03-04 10:00:00,2020-03-03,2020-03-04,1899-12-30 09:40:00,1899-12-30 10:00:00,2020-03-03 21:50:00,0,0,0,0,0.369863,9,0,0,0,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.164384,4,0,0,0.000000,0,0,0,0.041096,1,0,0,0.123288,3,0.000000,0
43,44,2020-03-04 10:00:00,23.750000,2020-03-05 09:45:00,2020-03-04,2020-03-05,1899-12-30 10:00:00,1899-12-30 09:45:00,2020-03-04 21:52:30,0,0,0,0,0.084211,2,0,0,0,0,0,0,0.000000,0,0,0,0.042105,1,0,0,0.168421,4,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0.000000,0
44,45,2020-03-05 09:45:00,24.000000,2020-03-06 09:45:00,2020-03-05,2020-03-06,1899-12-30 09:45:00,1899-12-30 09:45:00,2020-03-05 21:45:00,0,0,0,0,0.083333,2,0,0,0,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.166667,4,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0.000000,0
45,46,2020-03-06 09:45:00,23.500000,2020-03-07 09:15:00,2020-03-06,2020-03-07,1899-12-30 09:45:00,1899-12-30 09:15:00,2020-03-06 21:30:00,0,0,0,0,0.170213,4,0,0,0,0,0,0,0.000000,0,0,0,0.042553,1,0,0,0.085106,2,0,0,0.000000,0,0,0,0.042553,1,0,0,0.000000,0,0.000000,0
46,47,2020-03-07 09:15:00,23.000000,2020-03-08 09:15:00,2020-03-07,2020-03-08,1899-12-30 09:15:00,1899-12-30 09:15:00,2020-03-07 20:45:00,0,0,0,0,0.086957,2,0,0,0,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.217391,5,0,0,0.000000,0,0,0,0.043478,1,0,0,0.000000,0,0.000000,0
47,48,2020-03-08 09:15:00,24.000000,2020-03-09 09:15:00,2020-03-08,2020-03-09,1899-12-30 09:15:00,1899-12-30 09:15:00,2020-03-08 21:15:00,0,0,0,0,0.208333,5,0,0,0,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.041667,1,0,0,0.000000,0,0,0,0.000000,0,0,0,0.041667,1,0.000000,0
48,49,2020-03-09 09:15:00,24.250000,2020-03-10 09:30:00,2020-03-09,2020-03-10,1899-12-30 09:15:00,1899-12-30 09:30:00,2020-03-09 21:22:30,0,0,0,0,0.247423,6,0,0,0,0,0,0,0.000000,0,0,0,0.082474,2,0,0,0.206186,5,0,0,0.000000,0,0,0,0.082474,2,0,0,0.000000,0,0.000000,0
49,50,2020-03-10 09:30:00,24.166667,2020-03-11 09:40:00,2020-03-10,2020-03-11,1899-12-30 09:30:00,1899-12-30 09:40:00,2020-03-10 21:35:00,0,0,0,0,0.455172,11,0,0,0,0,0,0,0.000000,0,0,0,0.041379,1,0,0,0.206897,5,0,0,0.000000,0,0,0,0.000000,0,0,0,0.082759,2,0.000000,0
50,51,2020-03-11 09:40:00,24.000000,2020-03-12 09:40:00,2020-03-11,2020-03-12,1899-12-30 09:40:00,1899-12-30 09:40:00,2020-03-11 21:40:00,0,0,0,0,0.333333,8,0,0,0,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.125000,3,0,0,0.000000,0,0,0,0.000000,0,0,0,0.041667,1,0.000000,0
51,52,2020-03-12 09:40:00,24.333333,2020-03-13 10:00:00,2020-03-12,2020-03-13,1899-12-30 09:40:00,1899-12-30 10:00:00,2020-03-12 21:50:00,0,0,0,0,3.684932,43,0,0,0,0,0,0,0.000000,0,0,0,0.041096,1,0,0,0.410959,10,0,0,0.000000,0,0,0,0.000000,0,0,0,0.123288,3,0.000000,0
52,53,2020-03-13 10:00:00,23.250000,2020-03-14 09:15:00,2020-03-13,2020-03-14,1899-12-30 10:00:00,1899-12-30 09:15:00,2020-03-13 21:37:30,0,0,0,0,1.118280,26,0,0,0,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.086022,2,0,0,0.000000,0,0,0,0.043011,1,0,0,0.000000,0,0.000000,0
53,54,2020-03-14 09:15:00,24.000000,2020-03-15 09:15:00,2020-03-14,2020-03-15,1899-12-30 09:15:00,1899-12-30 09:15:00,2020-03-14 21:15:00,0,0,0,0,0.375000,9,0,0,0,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.250000,6,0,0,0.000000,0,0,0,0.041667,1,0,0,0.000000,0,0.000000,0
54,55,2020-03-15 09:15:00,24.250000,2020-03-16 09:30:00,2020-03-15,2020-03-16,1899-12-30 09:15:00,1899-12-30 09:30:00,2020-03-15 21:22:30,0,0,0,0,0.907216,22,0,0,0,0,0,0,0.000000,0,0,0,0.082474,2,0,0,0.041237,1,0,0,0.082474,2,0,0,0.000000,0,0,0,0.082474,2,0.000000,0
55,56,2020-03-16 09:30:00,24.000000,2020-03-17 09:30:00,2020-03-16,2020-03-17,1899-12-30 09:30:00,1899-12-30 09:30:00,2020-03-16 21:30:00,0,0,0,0,0.833333,20,0,0,0,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.083333,2,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0.000000,0
56,57,2020-03-17 09:30:00,25.000000,2020-03-18 10:30:00,2020-03-17,2020-03-18,1899-12-30 09:30:00,1899-12-30 10:30:00,2020-03-17 22:00:00,0,0,0,0,1.000000,25,0,0,0,0,0,0,0.000000,0,0,0,0.040000,1,0,0,0.160000,4,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0.000000,0
57,58,2020-03-18 10:30:00,23.000000,2020-03-19 09:30:00,2020-03-18,2020-03-19,1899-12-30 10:30:00,1899-12-30 09:30:00,2020-03-18 22:00:00,0,0,0,0,0.739130,17,0,0,0,0,0,0,0.000000,0,0,0,0.086957,2,0,0,0.043478,1,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0.000000,0
58,59,2020-03-19 09:30:00,24.000000,2020-03-20 09:30:00,2020-03-19,2020-03-20,1899-12-30 09:30:00,1899-12-30 09:30:00,2020-03-19 21:30:00,0,0,0,0,6.166667,148,0,0,0,0,0,0,0.125000,3,0,0,0.000000,0,0,0,0.208333,5,0,0,0.000000,0,0,0,0.041667,1,0,0,0.083333,2,0.000000,0
59,60,2020-03-20 09:30:00,23.000000,2020-03-21 08:30:00,2020-03-20,2020-03-21,1899-12-30 09:30:00,1899-12-30 08:30:00,2020-03-20 21:00:00,0,0,0,0,10.304348,83,0,0,0,0,0,0,0.043478,1,0,0,0.043478,1,0,0,0.217391,5,0,0,0.000000,0,0,0,0.000000,0,0,0,0.043478,1,0.000000,0
60,61,2020-03-21 08:30:00,24.500000,2020-03-22 09:00:00,2020-03-21,2020-03-22,1899-12-30 08:30:00,1899-12-30 09:00:00,2020-03-21 20:45:00,0,0,0,0,5.551020,136,0,0,0,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.040816,1,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0.000000,0
61,62,2020-03-22 09:00:00,25.000000,2020-03-23 10:00:00,2020-03-22,2020-03-23,1899-12-30 09:00:00,1899-12-30 10:00:00,2020-03-22 21:30:00,0,0,0,0,7.880000,149,0,0,0,0,0,0,0.040000,1,0,0,0.000000,0,0,0,0.040000,1,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0.000000,0
62,63,2020-03-23 10:00:00,24.000000,2020-03-24 10:00:00,2020-03-23,2020-03-24,1899-12-30 10:00:00,1899-12-30 10:00:00,2020-03-23 22:00:00,0,0,0,0,12.666667,212,0,0,0,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0.000000,0
63,64,2020-03-24 10:00:00,24.250000,2020-03-25 10:15:00,2020-03-24,2020-03-25,1899-12-30 10:00:00,1899-12-30 10:15:00,2020-03-24 22:07:30,0,0,0,0,21.329897,215,0,0,0,0,0,0,0.000000,0,0,0,0.041237,1,0,0,0.206186,5,0,0,0.123711,3,0,0,0.000000,0,0,0,0.000000,0,0.000000,0
64,65,2020-03-25 10:15:00,1.750000,2020-03-25 12:00:00,2020-03-25,2020-03-25,1899-12-30 10:15:00,1899-12-30 12:00:00,2020-03-25 11:07:30,0,0,0,0,34.571429,59,0,0,0,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0.000000,0
65,66,2020-04-16 11:30:00,20.750000,2020-04-17 08:15:00,2020-04-16,2020-04-17,1899-12-30 11:30:00,1899-12-30 08:15:00,2020-04-16 21:52:30,0,0,0,0,4.373494,71,0,0,0,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.433735,9,0,0,0.337349,7,0,0,0.000000,0,0,0,0.000000,0,0.000000,0
66,67,2020-04-17 08:15:00,25.250000,2020-04-18 09:30:00,2020-04-17,2020-04-18,1899-12-30 08:15:00,1899-12-30 09:30:00,2020-04-17 20:52:30,0,0,0,0,7.633663,120,0,0,0,0,0,0,0.039604,1,0,0,0.079208,2,0,0,0.435644,11,0,0,0.118812,3,0,0,0.039604,1,0,0,0.000000,0,0.000000,0
67,68,2020-04-18 09:30:00,25.000000,2020-04-19 10:30:00,2020-04-18,2020-04-19,1899-12-30 09:30:00,1899-12-30 10:30:00,2020-04-18 22:00:00,0,0,0,0,10.040000,131,0,0,0,0,0,0,0.080000,2,0,0,0.000000,0,0,0,0.440000,11,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0.000000,0
68,69,2020-04-19 10:30:00,24.000000,2020-04-20 10:30:00,2020-04-19,2020-04-20,1899-12-30 10:30:00,1899-12-30 10:30:00,2020-04-19 22:30:00,0,0,0,0,0.333333,8,0,0,0,0,0,0,0.000000,0,0,0,0.041667,1,0,0,1.083333,26,0,0,0.000000,0,0,0,0.000000,0,0,0,0.083333,2,0.000000,0
69,70,2020-04-20 10:30:00,24.000000,2020-04-21 10:30:00,2020-04-20,2020-04-21,1899-12-30 10:30:00,1899-12-30 10:30:00,2020-04-20 22:30:00,0,0,0,0,1.916667,46,0,0,0,0,0,0,0.000000,0,0,0,0.000000,0,0,0,0.500000,12,0,0,0.000000,0,0,0,0.000000,0,0,0,0.000000,0,0.000000,0
70,71,2020-04-21 10:30:00,23.000000,2020-04-22 09:30:00,2020-04-21,2020-04-22,1899-12-30 10:30:00,1899-12-30 09:30:00,2020-04-21 22:00:00,0,0,0,0,5.913043,26,0,0,0,0,0,0,0.000000,0,0,0,0.043478,1,0,0,0.391304,9,0,0,0.173913,4,0,0,0.000000,0,0,0,0.000000,0,0.000000,0
71,72,2020-04-22 09:30:00,24.000000,2020-04-23 09:30:00,2020-04-22,2020-04-23,1899-12-30 09:30:00,1899-12-30 09:30:00,2020-04-22 21:30:00,0,0,0,0,5.791667,93,0,0,0,0,0,0,0.041667,1,0,0,0.000000,0,0,0,0.458333,11,0,0,0.041667,1,0,0,0.000000,0,0,0,0.000000,0,0.041667,1

In [21]:
df = pd.read_excel(data_string + "2012 Nisqually temp logger.xlsx", header=[0,1])
with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    display(df)

     Plot Title: Nisqually Trap                                            \
                               #     Time, GMT-08:00 DateValue       Date
0                              1 2012-01-05 08:05:58     40913 2012-01-05
1                              2 2012-01-05 08:06:03     40913 2012-01-05
2                              3 2012-01-05 09:05:58     40913 2012-01-05
3                              4 2012-01-05 10:05:58     40913 2012-01-05
4                              5 2012-01-05 11:05:58     40913 2012-01-05
5                              6 2012-01-05 12:05:58     40913 2012-01-05
6                              7 2012-01-05 13:05:58     40913 2012-01-05
7                              8 2012-01-05 14:05:58     40913 2012-01-05
8                              9 2012-01-05 15:05:58     40913 2012-01-05
9                             10 2012-01-05 16:05:58     40913 2012-01-05
10                            11 2012-01-05 17:05:58     40913 2012-01-05
11                            12 2012-01-05 18:05:58     40913 2012-01-05
12                            13 2012-01-05 19:05:58     40913 2012-01-05
13                            14 2012-01-05 20:05:58     40913 2012-01-05
14                            15 2012-01-05 21:05:58     40913 2012-01-05
15                            16 2012-01-05 22:05:58     40913 2012-01-05
16                            17 2012-01-05 23:05:58     40913 2012-01-05
17                            18 2012-01-06 00:05:58     40914 2012-01-06
18                            19 2012-01-06 01:05:58     40914 2012-01-06
19                            20 2012-01-06 02:05:58     40914 2012-01-06
20                            21 2012-01-06 03:05:58     40914 2012-01-06
21                            22 2012-01-06 04:05:58     40914 2012-01-06
22                            23 2012-01-06 05:05:58     40914 2012-01-06
23                            24 2012-01-06 06:05:58     40914 2012-01-06
24                            25 2012-01-06 07:05:58     40914 2012-01-06
25                            26 2012-01-06 08:05:58     40914 2012-01-06
26                            27 2012-01-06 09:05:58     40914 2012-01-06
27                            28 2012-01-06 10:05:58     40914 2012-01-06
28                            29 2012-01-06 11:05:58     40914 2012-01-06
29                            30 2012-01-06 12:05:58     40914 2012-01-06
30                            31 2012-01-06 13:05:58     40914 2012-01-06
31                            32 2012-01-06 14:05:58     40914 2012-01-06
32                            33 2012-01-06 15:05:58     40914 2012-01-06
33                            34 2012-01-06 16:05:58     40914 2012-01-06
34                            35 2012-01-06 17:05:58     40914 2012-01-06
35                            36 2012-01-06 18:05:58     40914 2012-01-06
36                            37 2012-01-06 19:05:58     40914 2012-01-06
37                            38 2012-01-06 20:05:58     40914 2012-01-06
38                            39 2012-01-06 21:05:58     40914 2012-01-06
39                            40 2012-01-06 22:05:58     40914 2012-01-06
40                            41 2012-01-06 23:05:58     40914 2012-01-06
41                            42 2012-01-07 00:05:58     40915 2012-01-07
42                            43 2012-01-07 01:05:58     40915 2012-01-07
43                            44 2012-01-07 02:05:58     40915 2012-01-07
44                            45 2012-01-07 03:05:58     40915 2012-01-07
45                            46 2012-01-07 04:05:58     40915 2012-01-07
46                            47 2012-01-07 05:05:58     40915 2012-01-07
47                            48 2012-01-07 06:05:58     40915 2012-01-07
48                            49 2012-01-07 07:05:58     40915 2012-01-07
49                            50 2012-01-07 08:05:58     40915 2012-01-07
50                            51 2012-01-07 09:05:58     40915 2012-01-07
51                            52 2012-01-07 10:05:58     40915 2012-01-07
52                            53 2012-01-07 11:05:58     40915 2012-01-07
53                            54 2012-01-07 12:05:58     40915 2012-01-07
54                            55 2012-01-07 13:05:58     40915 2012-01-07
55                            56 2012-01-07 14:05:58     40915 2012-01-07
56                            57 2012-01-07 15:05:58     40915 2012-01-07
57                            58 2012-01-07 16:05:58     40915 2012-01-07
58                            59 2012-01-07 17:05:58     40915 2012-01-07
59                            60 2012-01-07 18:05:58     40915 2012-01-07
60                            61 2012-01-07 19:05:58     40915 2012-01-07
61                            62 2012-01-07 20:05:58     40915 2012-01-07
62                            63 2012-01-07 21:05:58     40915 2012-01-07
63                            64 2012-01-07 22:05:58     40915 2012-01-07
64                            65 2012-01-07 23:05:58     40915 2012-01-07
65                            66 2012-01-08 00:05:58     40916 2012-01-08
66                            67 2012-01-08 01:05:58     40916 2012-01-08
67                            68 2012-01-08 02:05:58     40916 2012-01-08
68                            69 2012-01-08 03:05:58     40916 2012-01-08
69                            70 2012-01-08 04:05:58     40916 2012-01-08
70                            71 2012-01-08 05:05:58     40916 2012-01-08
71                            72 2012-01-08 06:05:58     40916 2012-01-08
72                            73 2012-01-08 07:05:58     40916 2012-01-08
73                            74 2012-01-08 08:05:58     40916 2012-01-08
74                            75 2012-01-08 09:05:58     40916 2012-01-08
75                            76 2012-01-08 10:05:58     40916 2012-01-08
76                            77 2012-01-08 11:05:58     40916 2012-01-08
77                            78 2012-01-08 12:05:58     40916 2012-01-08
78                            79 2012-01-08 13:05:58     40916 2012-01-08
79                            80 2012-01-08 14:05:58     40916 2012-01-08
80                            81 2012-01-08 15:05:58     40916 2012-01-08
81                            82 2012-01-08 16:05:58     40916 2012-01-08
82                            83 2012-01-08 17:05:58     40916 2012-01-08
83                            84 2012-01-08 18:05:58     40916 2012-01-08
84                            85 2012-01-08 19:05:58     40916 2012-01-08
85                            86 2012-01-08 20:05:58     40916 2012-01-08
86                            87 2012-01-08 21:05:58     40916 2012-01-08
87                            88 2012-01-08 22:05:58     40916 2012-01-08
88                            89 2012-01-08 23:05:58     40916 2012-01-08
89                            90 2012-01-09 00:05:58     40917 2012-01-09
90                            91 2012-01-09 01:05:58     40917 2012-01-09
91                            92 2012-01-09 02:05:58     40917 2012-01-09
92                            93 2012-01-09 03:05:58     40917 2012-01-09
93                            94 2012-01-09 04:05:58     40917 2012-01-09
94                            95 2012-01-09 05:05:58     40917 2012-01-09
95                            96 2012-01-09 06:05:58     40917 2012-01-09
96                            97 2012-01-09 07:05:58     40917 2012-01-09
97                            98 2012-01-09 08:05:58     40917 2012-01-09
98                            99 2012-01-09 09:05:58     40917 2012-01-09
99                           100 2012-01-09 10:05:58     40917 2012-01-09
100                          101 2012-01-09 11:05:58     40917 2012-01-09
101                          102 2012-01-09 12:05:58     40917 2012-01-09
102                          103 2012-01-09 13:05:58     40917 2012-01-09
103                          104 2012-01-09 14:05:58     40917 2012-01-09
104                          105 2012-01-09 15:05:58     40917 2012-01-09
105                          106 2012-01-09 16:05:58     40917 2012-01-09
106                          107 2012-01-09 17:05:58     40917 2012-01-09
107                          108 2012-01-09 18:05:58     40917 2012-01-09
108                          109 2012-01-09 19:05:58     40917 2012-01-09
109                          110 2012-01-09 20:05:58     40917 2012-01-09
110                          111 2012-01-09 21:05:58     40917 2012-01-09
111                          112 2012-01-09 22:05:58     40917 2012-01-09
112                          113 2012-01-09 23:05:58     40917 2012-01-09
113                          114 2012-01-10 00:05:58     40918 2012-01-10
114                          115 2012-01-10 01:05:58     40918 2012-01-10
115                          116 2012-01-10 02:05:58     40918 2012-01-10
116                          117 2012-01-10 03:05:58     40918 2012-01-10
117                          118 2012-01-10 04:05:58     40918 2012-01-10
118                          119 2012-01-10 05:05:58     40918 2012-01-10
119                          120 2012-01-10 06:05:58     40918 2012-01-10
120                          121 2012-01-10 07:05:58     40918 2012-01-10
121                          122 2012-01-10 08:05:58     40918 2012-01-10
122                          123 2012-01-10 09:05:58     40918 2012-01-10
123                          124 2012-01-10 10:05:58     40918 2012-01-10
124                          125 2012-01-10 11:05:58     40918 2012-01-10
125                          126 2012-01-10 12:05:58     40918 2012-01-10
126                          127 2012-01-10 13:05:58     40918 2012-01-10
127                          128 2012-01-10 14:05:58     40918 2012-01-10
128                          129 2012-01-10 15:05:58     40918 2012-01-10
129                          130 2012-01-10 16:05:58     40918 2012-01-10
130                          131 2012-01-10 17:05:58     40918 2012-01-10
131                          132 2012-01-10 18:05:58     40918 2012-01-10
132                          133 2012-01-10 19:05:58     40918 2012-01-10
133                          134 2012-01-10 20:05:58     40918 2012-01-10
134                          135 2012-01-10 21:05:58     40918 2012-01-10
135                          136 2012-01-10 22:05:58     40918 2012-01-10
136                          137 2012-01-10 23:05:58     40918 2012-01-10
137                          138 2012-01-11 00:05:58     40919 2012-01-11
138                          139 2012-01-11 01:05:58     40919 2012-01-11
139                          140 2012-01-11 02:05:58     40919 2012-01-11
140                          141 2012-01-11 03:05:58     40919 2012-01-11
141                          142 2012-01-11 04:05:58     40919 2012-01-11
142                          143 2012-01-11 05:05:58     40919 2012-01-11
143                          144 2012-01-11 06:05:58     40919 2012-01-11
144                          145 2012-01-11 07:05:58     40919 2012-01-11
145                          146 2012-01-11 08:05:58     40919 2012-01-11
146                          147 2012-01-11 09:05:58     40919 2012-01-11
147                          148 2012-01-11 10:05:58     40919 2012-01-11
148                          149 2012-01-11 11:05:58     40919 2012-01-11
149                          150 2012-01-11 12:05:58     40919 2012-01-11
150                          151 2012-01-11 13:05:58     40919 2012-01-11
151                          152 2012-01-11 14:05:58     40919 2012-01-11
152                          153 2012-01-11 15:05:58     40919 2012-01-11
153                          154 2012-01-11 16:05:58     40919 2012-01-11
154                          155 2012-01-11 17:05:58     40919 2012-01-11
155                          156 2012-01-11 18:05:58     40919 2012-01-11
156                          157 2012-01-11 19:05:58     40919 2012-01-11
157                          158 2012-01-11 20:05:58     40919 2012-01-11
158                          159 2012-01-11 21:05:58     40919 2012-01-11
159                          160 2012-01-11 22:05:58     40919 2012-01-11
160                          161 2012-01-11 23:05:58     40919 2012-01-11
161                          162 2012-01-12 00:05:58     40920 2012-01-12
162                          163 2012-01-12 01:05:58     40920 2012-01-12
163                          164 2012-01-12 02:05:58     40920 2012-01-12
164                          165 2012-01-12 03:05:58     40920 2012-01-12
165                          166 2012-01-12 04:05:58     40920 2012-01-12
166                          167 2012-01-12 05:05:58     40920 2012-01-12
167                          168 2012-01-12 06:05:58     40920 2012-01-12
168                          169 2012-01-12 07:05:58     40920 2012-01-12
169                          170 2012-01-12 08:05:58     40920 2012-01-12
170                          171 2012-01-12 09:05:58     40920 2012-01-12
171                          172 2012-01-12 10:05:58     40920 2012-01-12
172                          173 2012-01-12 11:05:58     40920 2012-01-12
173                          174 2012-01-12 12:05:58     40920 2012-01-12
174                          175 2012-01-12 13:05:58     40920 2012-01-12
175                          176 2012-01-12 14:05:58     40920 2012-01-12
176                          177 2012-01-12 15:05:58     40920 2012-01-12
177                          178 2012-01-12 16:05:58     40920 2012-01-12
178                          179 2012-01-12 17:05:58     40920 2012-01-12
179                          180 2012-01-12 18:05:58     40920 2012-01-12
180                          181 2012-01-12 19:05:58     40920 2012-01-12
181                          182 2012-01-12 20:05:58     40920 2012-01-12
182                          183 2012-01-12 21:05:58     40920 2012-01-12
183                          184 2012-01-12 22:05:58     40920 2012-01-12
184                          185 2012-01-12 23:05:58     40920 2012-01-12
185                          186 2012-01-13 00:05:58     40921 2012-01-13
186                          187 2012-01-13 01:05:58     40921 2012-01-13
187                          188 2012-01-13 02:05:58     40921 2012-01-13
188                          189 2012-01-13 03:05:58     40921 2012-01-13
189                          190 2012-01-13 04:05:58     40921 2012-01-13
190                          191 2012-01-13 05:05:58     40921 2012-01-13
191                          192 2012-01-13 06:05:58     40921 2012-01-13
192                          193 2012-01-13 07:05:58     40921 2012-01-13
193                          194 2012-01-13 08:05:58     40921 2012-01-13
194                          195 2012-01-13 09:05:58     40921 2012-01-13
195                          196 2012-01-13 10:05:58     40921 2012-01-13
196                          197 2012-01-13 11:05:58     40921 2012-01-13
197                          198 2012-01-13 12:05:58     40921 2012-01-13
198                          199 2012-01-13 13:05:58     40921 2012-01-13
199                          200 2012-01-13 14:05:58     40921 2012-01-13
200                          201 2012-01-13 15:05:58     40921 2012-01-13
201                          202 2012-01-13 16:05:58     40921 2012-01-13
202                          203 2012-01-13 17:05:58     40921 2012-01-13
203                          204 2012-01-13 18:05:58     40921 2012-01-13
204                          205 2012-01-13 19:05:58     40921 2012-01-13
205                          206 2012-01-13 20:05:58     40921 2012-01-13
206                          207 2012-01-13 21:05:58     40921 2012-01-13
207                          208 2012-01-13 22:05:58     40921 2012-01-13
208                          209 2012-01-13 23:05:58     40921 2012-01-13
209                          210 2012-01-14 00:05:58     40922 2012-01-14
210                          211 2012-01-14 01:05:58     40922 2012-01-14
211                          212 2012-01-14 02:05:58     40922 2012-01-14
212                          213 2012-01-14 03:05:58     40922 2012-01-14
213                          214 2012-01-14 04:05:58     40922 2012-01-14
214                          215 2012-01-14 05:05:58     40922 2012-01-14
215                          216 2012-01-14 06:05:58     40922 2012-01-14
216                          217 2012-01-14 07:05:58     40922 2012-01-14
217                          218 2012-01-14 08:05:58     40922 2012-01-14
218                          219 2012-01-14 09:05:58     40922 2012-01-14
219                          220 2012-01-14 10:05:58     40922 2012-01-14
220                          221 2012-01-14 11:05:58     40922 2012-01-14
221                          222 2012-01-14 12:05:58     40922 2012-01-14
222                          223 2012-01-14 13:05:58     40922 2012-01-14
223                          224 2012-01-14 14:05:58     40922 2012-01-14
224                          225 2012-01-14 15:05:58     40922 2012-01-14
225                          226 2012-01-14 16:05:58     40922 2012-01-14
226                          227 2012-01-14 17:05:58     40922 2012-01-14
227                          228 2012-01-14 18:05:58     40922 2012-01-14
228                          229 2012-01-14 19:05:58     40922 2012-01-14
229                          230 2012-01-14 20:05:58     40922 2012-01-14
230                          231 2012-01-14 21:05:58     40922 2012-01-14
231                          232 2012-01-14 22:05:58     40922 2012-01-14
232                          233 2012-01-14 23:05:58     40922 2012-01-14
233                          234 2012-01-15 00:05:58     40923 2012-01-15
234                          235 2012-01-15 01:05:58     40923 2012-01-15
235                          236 2012-01-15 02:05:58     40923 2012-01-15
236                          237 2012-01-15 03:05:58     40923 2012-01-15
237                          238 2012-01-15 04:05:58     40923 2012-01-15
238                          239 2012-01-15 05:05:58     40923 2012-01-15
239                          240 2012-01-15 06:05:58     40923 2012-01-15
240                          241 2012-01-15 07:05:58     40923 2012-01-15
241                          242 2012-01-15 08:05:58     40923 2012-01-15
242                          243 2012-01-15 09:05:58     40923 2012-01-15
243                          244 2012-01-15 10:05:58     40923 2012-01-15
244                          245 2012-01-15 11:05:58     40923 2012-01-15
245                          246 2012-01-15 12:05:58     40923 2012-01-15
246                          247 2012-01-15 13:05:58     40923 2012-01-15
247                          248 2012-01-15 14:05:58     40923 2012-01-15
248                          249 2012-01-15 15:05:58     40923 2012-01-15
249                          250 2012-01-15 16:05:58     40923 2012-01-15
250                          251 2012-01-15 17:05:58     40923 2012-01-15
251                          252 2012-01-15 18:05:58     40923 2012-01-15
252                          253 2012-01-15 19:05:58     40923 2012-01-15
253                          254 2012-01-15 20:05:58     40923 2012-01-15
254                          255 2012-01-15 21:05:58     40923 2012-01-15
255                          256 2012-01-15 22:05:58     40923 2012-01-15
256                          257 2012-01-15 23:05:58     40923 2012-01-15
257                          258 2012-01-16 00:05:58     40924 2012-01-16
258                          259 2012-01-16 01:05:58     40924 2012-01-16
259                          260 2012-01-16 02:05:58     40924 2012-01-16
260                          261 2012-01-16 03:05:58     40924 2012-01-16
261                          262 2012-01-16 04:05:58     40924 2012-01-16
262                          263 2012-01-16 05:05:58     40924 2012-01-16
263                          264 2012-01-16 06:05:58     40924 2012-01-16
264                          265 2012-01-16 07:05:58     40924 2012-01-16
265                          266 2012-01-16 08:05:58     40924 2012-01-16
266                          267 2012-01-16 09:05:58     40924 2012-01-16
267                          268 2012-01-16 10:05:58     40924 2012-01-16

In [ ]:
plot(df['Date'])