In [1]:
#imports

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from urllib.request import urlopen
from bs4 import BeautifulSoup
from sys import platform
import io
import datetime

if platform == "linux" or platform == "linux2":
    data_string = "/home/maria/Documents/data/pied_piper/puyallup/"
    output_string = "/home/maria/Documents/output/pied_piper/puyallup/"

elif platform == "win32"or platform == "win64":
    data_string = "C:/Users/maria/OneDrive/Documents/data/pied_piper/puyallup/"
    output_string = "C:/Users/maria/OneDrive/Documents/output/pied_piper/puyallup/"

In [11]:
# #read file in Windows
try:
    df = pd.read_excel(
   io=data_string + "puyallup_chinook_2004-2018.xlsx",
   sheet_name ='2014_edited',
    header = [3]
)
except PermissionError:
    print("Permission Error. Close the file, if it is open.")
    

df.head()

,Date,flow,In-Out_day,secchi_depth_day,turbidity,chinook0_wild_num_day,trap_efficiency_day,chinook0_wild_num_day_estimate,In-Out_night,secchi_depth_night,...,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,chinook0_hatchery_num_night,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,chinook0_hatchery_num
0,2014-01-23,1430,1415-1515,211,NaN,0,0.0191,0.0,1515-745,211,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0
1,2014-01-24,1340,745-1700,212,NaN,0,0.0187,0.0,1700-745,214,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0
2,2014-01-25,1260,745-1700,207,NaN,0,0.0194,0.0,1715-800,212,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0
3,2014-01-26,1210,800-1645,207,NaN,0,0.0200,0.0,1645-745,206,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0
4,2014-01-27,1160,745-1645,205,NaN,0,0.0203,0.0,1645-745,205,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0

In [12]:
pd.unique(df['In-Out_day']) #'-','OUT'
pd.unique(df['In-Out_night']) #'-','OUT'


df.columns

Index(['Date', 'flow', 'In-Out_day', 'secchi_depth_day', 'turbidity',
       'chinook0_wild_num_day', 'trap_efficiency_day',
       'chinook0_wild_num_day_estimate', 'In-Out_night', 'secchi_depth_night',
       'Unnamed: 10', 'chinook0_wild_num_night', 'trap_efficiency_night',
       'chinook0_wild_num_night_estimate', 'secchi_depth', 'Unnamed: 15',
       'chinook0_wild_num', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22',
       'chinook0_hatchery_num_day', 'Unnamed: 24', 'Unnamed: 25',
       'Unnamed: 26', 'Unnamed: 27', 'chinook0_hatchery_num_night',
       'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32',
       'chinook0_hatchery_num'],
      dtype='object')

In [13]:
df['In_day_edited'] = df['In-Out_day']
df['In_day_edited'][df['In-Out_day'] == '-'] = np.nan
df['In_day_edited'][df['In-Out_day'] == 'OUT'] = np.nan
df['In_day_edited'].unique()

<ipython-input-13-7d56c4d5901f>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['In_day_edited'][df['In-Out_day'] == '-'] = np.nan
<ipython-input-13-7d56c4d5901f>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['In_day_edited'][df['In-Out_day'] == 'OUT'] = np.nan

array(['1415-1515', '745-1700', '800-1645', '745-1645', '800-1730',
       '745-1630', '815-1700', nan, '730-1645', '815-1600', '600-1645',
       '830-1700', '800-1700', '745-1715', '715-1730', '730-1700',
       '730-1730', '800-1800', '715-1715', '800-1715', '730-1715',
       '700-1730', '700-1900', '700-1830', '745-1830', '845-1900',
       '700-2000', '700-1845', '715-1830', '915-1830', '845-1845',
       '715-1900', '730-1900', '730-1845', '815-1900', '745-1845',
       '830-1745', '845-1745', '800-1945', '730-1915', '745-1915',
       '800-1930', '715-1915', '700-1930', '845-1930', '700-1915',
       '730-1930', '815-1830', '715-1930', '800-1915', '1145-1945',
       '830-2000', '815-2000', '730-1945', '730-2000', '1230-2000',
       '815-1130', '715-1945', '730-1530', '800-1845', '800-1630',
       '730-1400', '745-2000', '1115-2115', '715-2015', '730-2015',
       '700-1945', '2000-2000', '745-1945', '715-1800', '715-1330',
       '645-1900', '630-1945', '715-2045', '715-2030', '730-1230',
       '900-2045', '700-2030', '1830-2130', '715-2100', '730-2045',
       '715-2000', '745-2030', '715-2130', '615-1800', '1140-2045',
       '730-1430', '730-1245'], dtype=object)

In [14]:
df['In_night_edited'] = df['In-Out_night']
df['In_night_edited'][df['In-Out_night'] == '-'] = np.nan
df['In_night_edited'][df['In-Out_night'] == 'OUT'] = np.nan
df['In_night_edited'].unique()

<ipython-input-14-026a1cd207de>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['In_night_edited'][df['In-Out_night'] == '-'] = np.nan
<ipython-input-14-026a1cd207de>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['In_night_edited'][df['In-Out_night'] == 'OUT'] = np.nan

array(['1515-745', '1700-745', '1715-800', '1645-745', '1830-745',
       '1630-800', '1715-730', '745-715', '1700-800', '1630-545', nan,
       '1700-815', '1715-815', '1715-745', '1730-700', '1745-745',
       '1745-800', '1615-715', '1730-730', '1730-800', '1815-730',
       '1730-715', '1715-715', '1900-730', '1845-730', '1930-830',
       '1845-830', '2000-815', '2000-930', '1900-715', '1830-900',
       '1830-845', '1900-700', '1915-715', '1900-815', '1915-730',
       '1800-845', '1945-715', '1930-730', '1930-800', '1930-845',
       '1845-715', '1930-715', '1915-700', '1930-700', '1930-745',
       '1845-745', '1845-700', '1945-745', '1945-1130', '2000-715',
       '1915-815', '2015-800', '2015-715', '2000-615', '2000-230',
       '2100-700', '1530-715', '745-745', '1915-745', '1645-715',
       '1415-715', '2015-745', '2030-645', '2300-700', '1945-700',
       '2130-700', '2030-715', '2000-700', '2000-645', '2000-2000',
       '2015-700', '2000-2330', '2330-730', '1815-700', '100-630',
       '1915-615', '2100-715', '745-700', '2045-700', '715-515',
       '530-645', '700-645', '700-715', '1230-845', '2030-800',
       '2145-715', '2115-700', '715-715', '2045-915', '915-715',
       '2000-730', '2045-645', '700-700', '2115-800', '815-815',
       '830-700', '2145-700', '730-730', '745-645', '2015-530', '545-600',
       '615-600', '230-645', '2015-645', '700-745', '800-800', '2045-715',
       '1430-645'], dtype=object)

In [15]:
df['In_time_day'] = pd.to_datetime(df['In_day_edited'].str.split('-',n=2, expand = True)[0], 
                                   format = '%H%M').dt.time
df['Out_time_day'] = pd.to_datetime(df['In_day_edited'].str.split('-',n=2, expand = True)[1], 
                                    format = '%H%M').dt.time
# df['Out_date_day'] = df['Date']+pd.Timedelta(days=1)
# df['Out_datetime_day'] = pd.to_datetime(df['Date'].astype(str) + ' ' + df['Out_time_day'].astype(str) , 
#                                         errors='coerce')
# df['In_datetime_day'] = pd.to_datetime(df['Date'].astype(str) + ' ' + df['In_time_day'].astype(str), 
#                                         errors='coerce')
# df['In_day'] = (df['Out_datetime_day'] - df['In_datetime_day']).astype('timedelta64[h]')
# df['In_day']

df['In_time_night'] = pd.to_datetime(df['In_night_edited'].str.split('-',n=2, expand = True)[0], format = '%H%M').dt.time
df['Out_time_night'] = pd.to_datetime(df['In_night_edited'].str.split('-',n=2, expand = True)[1], format = '%H%M').dt.time
# df['Out_date_night'] = df['Date']+pd.Timedelta(days=1)
# df['Out_datetime_night'] = pd.to_datetime(df['Out_date_night'].astype(str) + ' ' + df['Out_time_night'].astype(str) , 
#                                         errors='coerce')
df['In_datetime_night'] = pd.to_datetime(df['Date'].astype(str) + ' ' + df['In_time_night'].astype(str), 
                                        errors='coerce')

df['In_datetime_day'] = pd.to_datetime(df['Date'].astype(str) + ' ' + df['In_time_day'].astype(str), 
                                        errors='coerce')

In [16]:
def adjust_date_night(row):
    if(row['Out_time_night'] > row['In_time_night']):
        return(row['Date'])
    else:
        return(row['Date'] + pd.DateOffset(days = 1))
    
def adjust_date_day(row):
    if(row['Out_time_day'] > row['In_time_day']):
        return(row['Date'])
    else:
        return(row['Date'] + pd.DateOffset(days = 1))
    
    
df['Out_date_night'] = df.apply(adjust_date_night,axis=1)

df['Out_date_day'] = df.apply(adjust_date_day,axis=1)

df['Out_datetime_night'] = pd.to_datetime(df['Out_date_night'].astype(str) + ' ' + df['Out_time_night'].astype(str) , 
                                        errors='coerce')

df['Out_datetime_day'] = pd.to_datetime(df['Out_date_day'].astype(str) + ' ' + df['Out_time_day'].astype(str) , 
                                        errors='coerce')

df['In_night'] = (df['Out_datetime_night'] - df['In_datetime_night']).dt.total_seconds() / 3600

df['In_day'] = (df['Out_datetime_day'] - df['In_datetime_day']).dt.total_seconds() / 3600

In [17]:
df.columns

Index(['Date', 'flow', 'In-Out_day', 'secchi_depth_day', 'turbidity',
       'chinook0_wild_num_day', 'trap_efficiency_day',
       'chinook0_wild_num_day_estimate', 'In-Out_night', 'secchi_depth_night',
       'Unnamed: 10', 'chinook0_wild_num_night', 'trap_efficiency_night',
       'chinook0_wild_num_night_estimate', 'secchi_depth', 'Unnamed: 15',
       'chinook0_wild_num', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22',
       'chinook0_hatchery_num_day', 'Unnamed: 24', 'Unnamed: 25',
       'Unnamed: 26', 'Unnamed: 27', 'chinook0_hatchery_num_night',
       'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32',
       'chinook0_hatchery_num', 'In_day_edited', 'In_night_edited',
       'In_time_day', 'Out_time_day', 'In_time_night', 'Out_time_night',
       'In_datetime_night', 'In_datetime_day', 'Out_date_night',
       'Out_date_day', 'Out_datetime_night', 'Out_datetime_day', 'In_night',
       'In_day'],
      dtype='object')

In [18]:
df_subset = df[['Date','flow','secchi_depth_day','In_day','In_night', 'secchi_depth_night',
                'chinook0_wild_num_day', 'trap_efficiency_day',
                       'chinook0_wild_num_day_estimate', 'chinook0_wild_num_night_estimate',
                'chinook0_wild_num_night',
                       'chinook0_wild_num',
                'chinook0_hatchery_num_day',
                'chinook0_hatchery_num_night', 'chinook0_hatchery_num','trap_efficiency_night']]

df_subset['flow_day'] = df_subset['flow']
df_subset['flow_night'] = df_subset['flow']

df_subset['In'] = df_subset['In_day'].fillna(0) + df_subset['In_night'].fillna(0)
df_subset['In'] = df_subset['In'].replace(0, np.nan)

df_subset.drop(df_subset.tail(2).index,inplace = True)

<ipython-input-18-912ad25dd8da>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['flow_day'] = df_subset['flow']
<ipython-input-18-912ad25dd8da>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['flow_night'] = df_subset['flow']
<ipython-input-18-912ad25dd8da>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['In'] = df_subset['In_day'].fillna(0) + df_subset['In_night'].fillna(0)
<ipython-input-18-912ad25dd8da>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['In'] = df_subset['In'].replace(0, np.nan)
/home/maria/miniconda3/envs/analysis/lib/python3.8/site-packages/pandas/core/frame.py:3990: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [20]:

#if In day is nan, then chinook0_wild_num_day and chinook0_wild_num_day should be nan

df_subset.loc[pd.isna(df_subset['In_day']),'chinook0_wild_num_day'] =np.nan
df_subset.loc[pd.isna(df_subset['In_day']),'chinook0_wild_num_day_estimate'] =np.nan

df_subset.loc[pd.isna(df_subset['In_day']),'chinook0_hatchery_num_day'] =np.nan

df_subset.loc[pd.isna(df_subset['In_night']),'chinook0_wild_num_night'] =np.nan
df_subset.loc[pd.isna(df_subset['In_night']),'chinook0_wild_num_night_estimate'] =np.nan

df_subset.loc[pd.isna(df_subset['In_night']),'chinook0_hatchery_num_day'] =np.nan

df_subset['chinook0_wild_perhour_day'] = df_subset['chinook0_wild_num_day']/df_subset['In_day']
df_subset['chinook0_wild_perhour_night'] = df_subset['chinook0_wild_num_night']/df_subset['In_night']

df_subset['chinook0_hatchery_perhour_day'] = df_subset['chinook0_hatchery_num_day']/df_subset['In_day']
df_subset['chinook0_hatchery_perhour_night'] = df_subset['chinook0_hatchery_num_night']/df_subset['In_night']

# df_subset['chinook0_wild_num_day_estimate'] = df_subset['chinook0_wild_num_day']/df_subset['trap_efficiency']
# df_subset['chinook0_wild_num_night_estimate'] = df_subset['chinook0_wild_num_night']/df_subset['trap_efficiency']

df_subset['chinook0_wild_perhour_day_estimate'] = (df_subset['chinook0_wild_perhour_day']/
                                                   df_subset['trap_efficiency_day'])
df_subset['chinook0_wild_perhour_night_estimate'] = (df_subset['chinook0_wild_perhour_night']/
                                                   df_subset['trap_efficiency_night'])


df_subset['chinook0_wild_perhour'] = df_subset['chinook0_wild_num']/df_subset['In']
df_subset['chinook0_hatchery_perhour'] = df_subset['chinook0_hatchery_num']/df_subset['In']

df_subset['chinook0_wild_perhour_estimate'] = (df_subset['chinook0_wild_perhour']/
                                                   df_subset['trap_efficiency_night'])



df_subset['chinook0_hatchery_num_day_estimate'] = df_subset['chinook0_hatchery_num_day']/df_subset['trap_efficiency_day']
df_subset['chinook0_hatchery_num_night_estimate'] = df_subset['chinook0_hatchery_num_night']/df_subset['trap_efficiency_night']


df_subset['chinook0_hatchery_perhour_day_estimate'] = (df_subset['chinook0_hatchery_num_day_estimate']/
                                                   df_subset['In_day'])
df_subset['chinook0_hatchery_perhour_night_estimate'] = (df_subset['chinook0_hatchery_num_night_estimate']/
                                                   df_subset['In_night'])
df_subset['chinook0_hatchery_perhour_estimate'] = (df_subset['chinook0_hatchery_perhour']/
                                                   df_subset['trap_efficiency_night'])

/home/maria/miniconda3/envs/analysis/lib/python3.8/site-packages/pandas/core/indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s
<ipython-input-20-a73b7cab4a05>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['chinook0_wild_perhour_day'] = df_subset['chinook0_wild_num_day']/df_subset['In_day']
<ipython-input-20-a73b7cab4a05>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['chinook0_wild_perhour_night'] = df_subset['chinook0_wild_num_night']/df_subset['In_night']
<ipython-input-20-a73b7cab4a05>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['chinook0_hatchery_perhour_day'] = df_subset['chinook0_hatchery_num_day']/df_subset['In_day']
<ipython-input-20-a73b7cab4a05>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['chinook0_hatchery_perhour_night'] = df_subset['chinook0_hatchery_num_night']/df_subset['In_night']
<ipython-input-20-a73b7cab4a05>:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['chinook0_wild_perhour_day_estimate'] = (df_subset['chinook0_wild_perhour_day']/
<ipython-input-20-a73b7cab4a05>:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['chinook0_wild_perhour_night_estimate'] = (df_subset['chinook0_wild_perhour_night']/
<ipython-input-20-a73b7cab4a05>:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['chinook0_wild_perhour'] = df_subset['chinook0_wild_num']/df_subset['In']
<ipython-input-20-a73b7cab4a05>:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['chinook0_hatchery_perhour'] = df_subset['chinook0_hatchery_num']/df_subset['In']
<ipython-input-20-a73b7cab4a05>:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['chinook0_wild_perhour_estimate'] = (df_subset['chinook0_wild_perhour']/
<ipython-input-20-a73b7cab4a05>:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['chinook0_hatchery_num_day_estimate'] = df_subset['chinook0_hatchery_num_day']/df_subset['trap_efficiency_day']
<ipython-input-20-a73b7cab4a05>:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['chinook0_hatchery_num_night_estimate'] = df_subset['chinook0_hatchery_num_night']/df_subset['trap_efficiency_night']
<ipython-input-20-a73b7cab4a05>:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['chinook0_hatchery_perhour_day_estimate'] = (df_subset['chinook0_hatchery_num_day_estimate']/
<ipython-input-20-a73b7cab4a05>:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['chinook0_hatchery_perhour_night_estimate'] = (df_subset['chinook0_hatchery_num_night_estimate']/
<ipython-input-20-a73b7cab4a05>:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['chinook0_hatchery_perhour_estimate'] = (df_subset['chinook0_hatchery_perhour']/

In [22]:

df_subset['chinook0_wild_perhour_total'] = (df_subset['chinook0_wild_perhour_day'] + 
                                            df_subset['chinook0_wild_perhour_night'])

df_subset['chinook0_hatchery_perhour_total'] = (df_subset['chinook0_hatchery_perhour_day'] + 
                                            df_subset['chinook0_hatchery_perhour_night'])

df_subset['chinook0_wild_day_fraction'] = np.nan
df_subset['chinook0_hatchery_day_fraction'] = np.nan
n = len(df_subset['chinook0_wild_perhour_total'])

for i in range(n):
    if df_subset['chinook0_wild_perhour_day'].loc[i]==0 and df_subset['chinook0_wild_perhour_total'].loc[i] == 0:
        df_subset['chinook0_wild_day_fraction'].loc[i] = np.nan
        
    else:
        df_subset['chinook0_wild_day_fraction'].loc[i] = (df_subset['chinook0_wild_perhour_day'].loc[i]/
                                                          df_subset['chinook0_wild_perhour_total'].loc[i])
        
    if df_subset['chinook0_hatchery_perhour_day'].loc[i]==0 and df_subset['chinook0_hatchery_perhour_total'].loc[i] == 0:
        df_subset['chinook0_hatchery_day_fraction'].loc[i] = np.nan
        
    else:
        df_subset['chinook0_hatchery_day_fraction'].loc[i] = (df_subset['chinook0_hatchery_perhour_day'].loc[i]/
                                                          df_subset['chinook0_hatchery_perhour_total'].loc[i])
        
df_subset = df_subset.drop(['chinook0_wild_perhour_total','chinook0_hatchery_perhour_total'],axis = 1)

<ipython-input-22-01955418e995>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['chinook0_wild_perhour_total'] = (df_subset['chinook0_wild_perhour_day'] +
<ipython-input-22-01955418e995>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['chinook0_hatchery_perhour_total'] = (df_subset['chinook0_hatchery_perhour_day'] +
<ipython-input-22-01955418e995>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['chinook0_wild_day_fraction'] = np.nan
<ipython-input-22-01955418e995>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['chinook0_hatchery_day_fraction'] = np.nan
/home/maria/miniconda3/envs/analysis/lib/python3.8/site-packages/pandas/core/indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)
<ipython-input-22-01955418e995>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['chinook0_wild_day_fraction'].loc[i] = np.nan
<ipython-input-22-01955418e995>:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['chinook0_hatchery_day_fraction'].loc[i] = np.nan
<ipython-input-22-01955418e995>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['chinook0_wild_day_fraction'].loc[i] = (df_subset['chinook0_wild_perhour_day'].loc[i]/
<ipython-input-22-01955418e995>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['chinook0_hatchery_day_fraction'].loc[i] = (df_subset['chinook0_hatchery_perhour_day'].loc[i]/

In [23]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    display(df_subset)

,Date,flow,secchi_depth_day,In_day,In_night,secchi_depth_night,chinook0_wild_num_day,trap_efficiency_day,chinook0_wild_num_day_estimate,chinook0_wild_num_night_estimate,chinook0_wild_num_night,chinook0_wild_num,chinook0_hatchery_num_day,chinook0_hatchery_num_night,chinook0_hatchery_num,trap_efficiency_night,flow_day,flow_night,In,chinook0_wild_perhour_day,chinook0_wild_perhour_night,chinook0_hatchery_perhour_day,chinook0_hatchery_perhour_night,chinook0_wild_perhour_day_estimate,chinook0_wild_perhour_night_estimate,chinook0_wild_perhour,chinook0_hatchery_perhour,chinook0_wild_perhour_estimate,chinook0_hatchery_num_day_estimate,chinook0_hatchery_num_night_estimate,chinook0_hatchery_perhour_day_estimate,chinook0_hatchery_perhour_night_estimate,chinook0_hatchery_perhour_estimate,chinook0_wild_day_fraction,chinook0_hatchery_day_fraction
0,2014-01-23,1430,211,1.000000,16.50,211,0,0.01910,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.01910,1430,1430,17.500000,0,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN
1,2014-01-24,1340,212,9.250000,14.75,214,0,0.01870,0.000000,106.951872,2.0,2.0,0.0,0.0,0.0,0.01870,1340,1340,24.000000,0,0.135593,0.000000,0.000000,0,7.250974,0.083333,0.000000,4.456328,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
2,2014-01-25,1260,207,9.250000,14.75,212,0,0.01940,0.000000,206.185567,4.0,4.0,0.0,0.0,0.0,0.01940,1260,1260,24.000000,0,0.271186,0.000000,0.000000,0,13.978683,0.166667,0.000000,8.591065,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
3,2014-01-26,1210,207,8.750000,15.00,206,0,0.02000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.02000,1210,1210,23.750000,0,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN
4,2014-01-27,1160,205,9.000000,15.00,205,0,0.02030,0.000000,49.261084,1.0,1.0,0.0,0.0,0.0,0.02030,1160,1160,24.000000,0,0.066667,0.000000,0.000000,0,3.284072,0.041667,0.000000,2.052545,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
5,2014-01-28,1140,201,9.250000,14.75,101,0,0.03110,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.03110,1140,1140,24.000000,0,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN
6,2014-01-29,2180,59,9.500000,13.25,59,4,0.04950,80.808081,484.848485,24.0,28.0,0.0,0.0,0.0,0.04950,2180,2180,22.750000,0.421053,1.811321,0.000000,0.000000,8.50611,36.592338,1.230769,0.000000,24.864025,0.000000,0.000000,0.000000,0.000000,0.000000,0.188612,NaN
7,2014-01-30,3070,96,8.750000,15.50,127,3,0.03900,76.923077,179.487179,7.0,10.0,0.0,0.0,0.0,0.03900,3070,3070,24.250000,0.342857,0.451613,0.000000,0.000000,8.79121,11.579818,0.412371,0.000000,10.573619,0.000000,0.000000,0.000000,0.000000,0.000000,0.431555,NaN
8,2014-01-31,2400,157,8.750000,14.75,188,1,0.02680,37.313433,37.313433,1.0,2.0,0.0,0.0,0.0,0.02680,2400,2400,23.500000,0.114286,0.067797,0.000000,0.000000,4.26439,2.529724,0.085106,0.000000,3.175611,0.000000,0.000000,0.000000,0.000000,0.000000,0.627660,NaN
9,2014-02-01,2090,181,8.750000,14.25,218,1,0.02140,46.728972,327.102804,7.0,8.0,0.0,0.0,0.0,0.02140,2090,2090,23.000000,0.114286,0.491228,0.000000,0.000000,5.34045,22.954583,0.347826,0.000000,16.253555,0.000000,0.000000,0.000000,0.000000,0.000000,0.188742,NaN
10,2014-02-02,1820,-,NaN,23.50,220,NaN,0.01730,NaN,231.213873,4.0,4.0,NaN,0.0,0.0,0.01730,1820,1820,23.500000,NaN,0.170213,NaN,0.000000,NaN,9.838888,0.170213,0.000000,9.838888,NaN,0.000000,NaN,0.000000,0.000000,NaN,NaN
11,2014-02-03,1640,217,9.250000,15.00,212,1,0.01840,54.347826,163.043478,3.0,4.0,0.0,0.0,0.0,0.01840,1640,1640,24.250000,0.108108,0.200000,0.000000,0.000000,5.87544,10.869565,0.164948,0.000000,8.964590,0.000000,0.000000,0.000000,0.000000,0.000000,0.350877,NaN
12,2014-02-04,1470,212,7.750000,13.25,-,1,0.01890,52.910053,105.820106,2.0,3.0,0.0,0.0,0.0,0.01890,1470,1470,21.000000,0.129032,0.150943,0.000000,0.000000,6.8271,7.986423,0.142857,0.000000,7.558579,0.000000,0.000000,0.000000,0.000000,0.000000,0.460870,NaN
13,2014-02-05,1330,200,10.750000,14.75,194,1,0.02190,45.662100,45.662100,1.0,2.0,0.0,0.0,0.0,0.02190,1330,1330,25.500000,0.0930233,0.067797,0.000000,0.000000,4.24764,3.095736,0.078431,0.000000,3.581341,0.000000,0.000000,0.000000,0.000000,0.000000,0.578431,NaN
14,2014-02-06,1190,-,NaN,NaN,197,NaN,0.02190,NaN,NaN,NaN,1.0,NaN,0.0,0.0,0.02190,1190,1190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN
15,2014-02-07,1200,205,9.250000,15.25,194,0,0.02140,0.000000,46.728972,1.0,1.0,0.0,0.0,0.0,0.02140,1200,1200,24.500000,0,0.065574,0.000000,0.000000,0,3.064195,0.040816,0.000000,1.907305,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
16,2014-02-08,1170,196,8.500000,15.00,192,1,0.02250,44.444444,0.000000,0.0,1.0,0.0,0.0,0.0,0.02250,1170,1170,23.500000,0.117647,0.000000,0.000000,0.000000,5.22876,0.000000,0.042553,0.000000,1.891253,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,NaN
17,2014-02-09,1130,191,8.500000,14.50,195,1,0.02270,44.052863,0.000000,0.0,1.0,0.0,0.0,0.0,0.02270,1130,1130,23.000000,0.117647,0.000000,0.000000,0.000000,5.18269,0.000000,0.043478,0.000000,1.915342,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,NaN
18,2014-02-10,1190,133,9.000000,14.25,125,0,0.03550,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.03550,1190,1190,23.250000,0,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN
19,2014-02-11,1720,135,9.500000,13.50,140,4,0.03380,118.343195,0.000000,0.0,4.0,0.0,0.0,0.0,0.03380,1720,1720,23.000000,0.421053,0.000000,0.000000,0.000000,12.4572,0.000000,0.173913,0.000000,5.145356,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,NaN
20,2014-02-12,1960,117,10.250000,14.00,115,1,0.03810,26.246719,26.246719,1.0,2.0,0.0,0.0,0.0,0.03810,1960,1960,24.250000,0.097561,0.071429,0.000000,0.000000,2.56066,1.874766,0.082474,0.000000,2.164678,0.000000,0.000000,0.000000,0.000000,0.000000,0.577320,NaN
21,2014-02-13,2340,102,9.500000,14.25,176,4,0.03350,119.402985,0.000000,0.0,4.0,0.0,0.0,0.0,0.03350,2340,2340,23.750000,0.421053,0.000000,0.000000,0.000000,12.5687,0.000000,0.168421,0.000000,5.027494,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,NaN
22,2014-02-14,2270,162,7.750000,15.00,170,1,0.02810,35.587189,106.761566,3.0,4.0,0.0,0.0,0.0,0.02810,2270,2270,22.750000,0.129032,0.200000,0.000000,0.000000,4.5919,7.117438,0.175824,0.000000,6.257088,0.000000,0.000000,0.000000,0.000000,0.000000,0.392157,NaN
23,2014-02-15,2320,155,9.500000,14.25,68,0,0.03900,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.03900,2320,2320,23.750000,0,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN
24,2014-02-16,2870,120,9.000000,NaN,24,6,0.04690,127.931770,NaN,NaN,48.0,NaN,0.0,0.0,0.04690,2870,2870,9.000000,0.666667,NaN,NaN,NaN,14.2146,NaN,5.333333,0.000000,113.717129,NaN,0.000000,NaN,NaN,0.000000,NaN,NaN
25,2014-02-17,4990,-,9.500000,NaN,56,16,0.05010,319.361277,NaN,NaN,58.0,NaN,0.0,0.0,0.05010,4990,4990,9.500000,1.68421,NaN,NaN,NaN,33.617,NaN,6.105263,0.000000,121.861540,NaN,0.000000,NaN,NaN,0.000000,NaN,NaN
26,2014-02-18,4610,75,10.000000,14.00,-,16,0.04630,345.572354,1814.254860,84.0,100.0,0.0,0.0,0.0,0.04630,4610,4610,24.000000,1.6,6.000000,0.000000,0.000000,34.5572,129.589633,4.166667,0.000000,89.992801,0.000000,0.000000,0.000000,0.000000,0.000000,0.210526,NaN
27,2014-02-19,4130,-,NaN,14.00,-,NaN,0.04250,NaN,141.176471,6.0,18.0,NaN,0.0,0.0,0.04250,4130,4130,14.000000,NaN,0.428571,NaN,0.000000,NaN,10.084034,1.285714,0.000000,30.252101,NaN,0.000000,NaN,0.000000,0.000000,NaN,NaN
28,2014-02-20,3350,105,9.250000,14.75,121,9,0.03870,232.558140,155.038760,6.0,15.0,0.0,0.0,0.0,0.03870,3350,3350,24.000000,0.972973,0.406780,0.000000,0.000000,25.1414,10.511102,0.625000,0.000000,16.149871,0.000000,0.000000,0.000000,0.000000,0.000000,0.705179,NaN
29,2014-02-21,2890,121,9.000000,14.75,157,2,0.03350,59.701493,298.507463,10.0,12.0,0.0,0.0,0.0,0.03350,2890,2890,23.750000,0.222222,0.677966,0.000000,0.000000,6.6335,20.237794,0.505263,0.000000,15.082482,0.000000,0.000000,0.000000,0.000000,0.000000,0.246862,NaN
30,2014-02-22,2400,171,9.500000,14.50,198,2,0.02440,81.967213,81.967213,2.0,4.0,0.0,0.0,0.0,0.02440,2400,2400,24.000000,0.210526,0.137931,0.000000,0.000000,8.62813,5.652911,0.166667,0.000000,6.830601,0.000000,0.000000,0.000000,0.000000,0.000000,0.604167,NaN
31,2014-02-23,2140,172,10.000000,13.25,182,1,0.02590,38.610039,38.610039,1.0,2.0,0.0,0.0,0.0,0.02590,2140,2140,23.250000,0.1,0.075472,0.000000,0.000000,3.861,2.913965,0.086022,0.000000,3.321294,0.000000,0.000000,0.000000,0.000000,0.000000,0.569892,NaN
32,2014-02-24,2210,144,9.250000,14.25,84,0,0.03850,0.000000,207.792208,8.0,8.0,0.0,0.0,0.0,0.03850,2210,2210,23.500000,0,0.561404,0.000000,0.000000,0,14.581909,0.340426,0.000000,8.842222,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
33,2014-02-25,3290,86,9.500000,13.75,99,6,0.04280,140.186916,163.551402,7.0,13.0,0.0,0.0,0.0,0.04280,3290,3290,23.250000,0.631579,0.509091,0.000000,0.000000,14.7565,11.894647,0.559140,0.000000,13.064014,0.000000,0.000000,0.000000,0.000000,0.000000,0.553691,NaN
34,2014-02-26,3300,122,9.500000,14.00,156,4,0.03350,119.402985,179.104478,6.0,10.0,0.0,0.0,0.0,0.03350,3300,3300,23.500000,0.421053,0.428571,0.000000,0.000000,12.5687,12.793177,0.425532,0.000000,12.702445,0.000000,0.000000,0.000000,0.000000,0.000000,0.495575,NaN
35,2014-02-27,3020,161,10.000000,14.50,201,2,0.02510,79.681275,239.043825,6.0,8.0,0.0,0.0,0.0,0.02510,3020,3020,24.500000,0.2,0.413793,0.000000,0.000000,7.96813,16.485781,0.326531,0.000000,13.009188,0.000000,0.000000,0.000000,0.000000,0.000000,0.325843,NaN
36,2014-02-28,2650,202,9.000000,14.50,230,1,0.01810,55.248619,55.248619,1.0,2.0,0.0,0.0,0.0,0.01810,2650,2650,23.500000,0.111111,0.068966,0.000000,0.000000,6.13874,3.810250,0.085106,0.000000,4.702010,0.000000,0.000000,0.000000,0.000000,0.000000,0.617021,NaN
37,2014-03-01,2340,232,9.250000,13.75,250,3,0.01310,229.007634,229.007634,3.0,6.0,0.0,0.0,0.0,0.01310,2340,2340,23.000000,0.324324,0.218182,0.000000,0.000000,24.7576,16.655101,0.260870,0.000000,19.913707,0.000000,0.000000,0.000000,0.000000,0.000000,0.597826,NaN
38,2014-03-02,2180,238,9.750000,13.75,101,2,0.02740,72.992701,291.970803,8.0,10.0,0.0,0.0,0.0,0.02740,2180,2180,23.500000,0.205128,0.581818,0.000000,0.000000,7.48643,21.234240,0.425532,0.000000,15.530362,0.000000,0.000000,0.000000,0.000000,0.000000,0.260664,NaN
39,2014-03-03,3300,83,10.000000,NaN,-,14,0.04470,313.199105,NaN,NaN,29.0,NaN,0.0,0.0,0.04470,3300,3300,10.000000,1.4,NaN,NaN,NaN,31.3199,NaN,2.900000,0.000000,64.876957,NaN,0.000000,NaN,NaN,0.000000,NaN,NaN
40,2014-03-04,4700,-,NaN,NaN,-,NaN,0.04925,NaN,NaN,NaN,90.0,NaN,0.0,0.0,0.04925,4700,4700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN
41,2014-03-05,5420,50,NaN,13.50,25,NaN,0.05380,NaN,408.921933,22.0,97.0,NaN,0.0,0.0,0.05380,5420,5420,13.500000,NaN,1.629630,NaN,0.000000,NaN,30.290514,7.185185,0.000000,133.553628,NaN,0.000000,NaN,0.000000,0.000000,NaN,NaN
42,2014-03-06,7370,23,10.500000,NaN,-,137,0.05670,2416.225750,NaN,NaN,166.0,NaN,0.0,0.0,0.05670,7370,7370,10.500000,13.0476,NaN,NaN,NaN,230.117,NaN,15.809524,0.000000,278.827580,NaN,0.000000,NaN,NaN,0.000000,NaN,NaN
43,2014-03-07,5250,-,NaN,NaN,-,NaN,0.05520,NaN,NaN,NaN,105.0,NaN,0.0,0.0,0.05520,5250,5250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN
44,2014-03-08,3900,62,10.500000,13.50,14,15,0.05370,279.329609,670.391061,36.0,51.0,0.0,0.0,0.0,0.05370,3900,3900,24.000000,1.42857,2.666667,0.000000,0.000000,26.6028,49.658597,2.125000,0.000000,39.571695,0.000000,0.000000,0.000000,0.000000,0.000000,0.348837,NaN
45,2014-03-09,8470,14,NaN,NaN,-,NaN,0.05850,NaN,NaN,NaN,418.0,NaN,0.0,0.0,0.05850,8470,8470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN
46,2014-03-10,8620,12,12.000000,NaN,-,455,0.05890,7724.957555,NaN,NaN,638.0,NaN,0.0,0.0,0.05890,8620,8620,12.000000,37.9167,NaN,NaN,NaN,643.746,NaN,53.166667,0.000000,902.659875,NaN,0.000000,NaN,NaN,0.000000,NaN,NaN
47,2014-03-11,6490,31,12.000000,12.50,39,69,0.05430,1270.718232,6095.764273,331.0,400.0,0.0,0.0,0.0,0.05430,6490,6490,24.500000,5.75,26.480000,0.000000,0.000000,105.893,487.661142,16.326531,0.000000,300.672755,0.000000,0.000000,0.000000,0.000000,0.000000,0.178405,NaN
48,2014-03-12,4580,62,11.500000,12.75,77,18,0.04740,379.746835,421.940928,20.0,38.0,0.0,0.0,0.0,0.04740,4580,4580,24.250000,1.56522,1.568627,0.000000,0.000000,33.0215,33.093406,1.567010,0.000000,33.059289,0.000000,0.000000,0.000000,0.000000,0.000000,0.499456,NaN
49,2014-03-13,3550,90,12.000000,13.00,90,8,0.04330,184.757506,207.852194,9.0,17.0,0.0,0.0,0.0,0.04330,3550,3550,25.000000,0.666667,0.692308,0.000000,0.000000,15.3965,15.988630,0.680000,0.000000,15.704388,0.000000,0.000000,0.000000,0.000000,0.000000,0.490566,NaN
50,2014-03-14,3520,56,12.000000,12.50,95,9,0.04620,194.805195,0.000000,0.0,9.0,0.0,0.0,0.0,0.04620,3520,3520,24.500000,0.75,0.000000,0.000000,0.000000,16.2338,0.000000,0.367347,0.000000,7.951232,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,NaN
51,2014-03-15,3270,103,10.750000,13.75,89,4,0.04210,95.011876,23.752969,1.0,5.0,0.0,0.0,0.0,0.04210,3270,3270,24.500000,0.372093,0.072727,0.000000,0.000000,8.83831,1.727489,0.204082,0.000000,4.847545,0.000000,0.000000,0.000000,0.000000,0.000000,0.836502,NaN
52,2014-03-16,3870,52,10.250000,NaN,44,1,0.05170,19.342360,NaN,NaN,29.0,NaN,0.0,0.0,0.05170,3870,3870,10.250000,0.097561,NaN,NaN,NaN,1.88706,NaN,2.829268,0.000000,54.724725,NaN,0.000000,NaN,NaN,0.000000,NaN,NaN
53,2014-03-17,5340,36,12.000000,12.50,84,50,0.04930,1014.198783,1095.334686,54.0,104.0,0.0,0.0,0.0,0.04930,5340,5340,24.500000,4.16667,4.320000,0.000000,0.000000,84.5166,87.626775,4.244898,0.000000,86.103407,0.000000,0.000000,0.000000,0.000000,0.000000,0.490966,NaN
54,2014-03-18,3880,87,13.000000,12.25,112,4,0.04140,96.618357,96.618357,4.0,8.0,0.0,0.0,0.0,0.04140,3880,3880,25.250000,0.307692,0.326531,0.000000,0.000000,7.43218,7.887213,0.316832,0.000000,7.652939,0.000000,0.000000,0.000000,0.000000,0.000000,0.485149,NaN
55,2014-03-19,3380,105,NaN,13.50,122,NaN,0.03860,NaN,129.533679,5.0,7.5,NaN,0.0,0.0,0.03860,3380,3380,13.500000,NaN,0.370370,NaN,0.000000,NaN,9.595087,0.555556,0.000000,14.392631,NaN,0.000000,NaN,0.000000,0.000000,NaN,NaN
56,2014-03-20,3060,134,11.750000,12.25,125,1,0.03540,28.248588,197.740113,7.0,8.0,0.0,0.0,0.0,0.03540,3060,3060,24.000000,0.0851064,0.571429,0.000000,0.000000,2.40414,16.142050,0.333333,0.000000,9.416196,0.000000,0.000000,0.000000,0.000000,0.000000,0.129630,NaN
57,2014-03-21,2600,131,11.250000,14.50,130,1,0.03520,28.409091,28.409091,1.0,2.0,0.0,0.0,0.0,0.03520,2600,2600,25.750000,0.0888889,0.068966,0.000000,0.000000,2.52525,1.959248,0.077670,0.000000,2.206531,0.000000,0.000000,0.000000,0.000000,0.000000,0.563107,NaN
58,2014-03-22,2280,161,9.250000,14.25,165,0,0.02870,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.02870,2280,2280,23.500000,0,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN
59,2014-03-23,2060,171,10.000000,12.00,187,0,0.02550,0.000000,39.215686,1.0,1.0,0.0,0.0,0.0,0.02550,2060,2060,22.000000,0,0.083333,0.000000,0.000000,0,3.267974,0.045455,0.000000,1.782531,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
60,2014-03-24,1880,182,12.000000,12.00,193,1,0.02380,42.016807,42.016807,1.0,2.0,0.0,0.0,0.0,0.02380,1880,1880,24.000000,0.0833333,0.083333,0.000000,0.000000,3.5014,3.501401,0.083333,0.000000,3.501401,0.000000,0.000000,0.000000,0.000000,0.000000,0.500000,NaN
61,2014-03-25,1800,184,11.750000,12.25,198,1,0.02310,43.290043,86.580087,2.0,3.0,0.0,0.0,0.0,0.02310,1800,1800,24.000000,0.0851064,0.163265,0.000000,0.000000,3.68426,7.067762,0.125000,0.000000,5.411255,0.000000,0.000000,0.000000,0.000000,0.000000,0.342657,NaN
62,2014-03-26,1810,184,11.500000,12.50,220,2,0.02090,95.693780,95.693780,2.0,4.0,0.0,0.0,0.0,0.02090,1810,1810,24.000000,0.173913,0.160000,0.000000,0.000000,8.3212,7.655502,0.166667,0.000000,7.974482,0.000000,0.000000,0.000000,0.000000,0.000000,0.520833,NaN
63,2014-03-27,1770,192,11.250000,13.25,151,0,0.02700,0.000000,37.037037,1.0,1.0,0.0,0.0,0.0,0.02700,1770,1770,24.500000,0,0.075472,0.000000,0.000000,0,2.795248,0.040816,0.000000,1.511716,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
64,2014-03-28,2030,167,10.750000,12.25,153,1,0.02930,34.129693,307.167235,9.0,10.0,0.0,0.0,0.0,0.02930,2030,2030,23.000000,0.0930233,0.734694,0.000000,0.000000,3.17486,25.074876,0.434783,0.000000,14.838997,0.000000,0.000000,0.000000,0.000000,0.000000,0.112385,NaN
65,2014-03-29,2370,113,10.750000,12.75,138,4,0.03620,110.497238,0.000000,0.0,4.0,0.0,0.0,0.0,0.03620,2370,2370,23.500000,0.372093,0.000000,0.000000,0.000000,10.2788,0.000000,0.170213,0.000000,4.702010,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,NaN
66,2014-03-30,2440,147,11.000000,13.25,187,0,0.02790,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.02790,2440,2440,24.250000,0,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN
67,2014-03-31,2200,219,9.250000,14.75,227,0,0.01670,0.000000,59.880240,1.0,1.0,0.0,0.0,0.0,0.01670,2200,2200,24.000000,0,0.067797,0.000000,0.000000,0,4.059677,0.041667,0.000000,2.495010,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
68,2014-04-01,1950,237,9.000000,14.00,230,1,0.01460,68.493151,0.000000,0.0,1.0,0.0,0.0,0.0,0.01460,1950,1950,23.000000,0.111111,0.000000,0.000000,0.000000,7.61035,0.000000,0.043478,0.000000,2.977963,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,NaN
69,2014-04-02,1760,215,11.750000,11.50,216,0,0.01820,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.01820,1760,1760,23.250000,0,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN
70,2014-04-03,1600,222,11.750000,12.00,221,0,0.01700,0.000000,117.647059,2.0,2.0,0.0,0.0,0.0,0.01700,1600,1600,23.750000,0,0.166667,0.000000,0.000000,0,9.803922,0.084211,0.000000,4.953560,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
71,2014-04-04,1580,225,11.500000,12.50,228,1,0.01600,62.500000,0.000000,0.0,1.0,0.0,0.0,0.0,0.01600,1580,1580,24.000000,0.0869565,0.000000,0.000000,0.000000,5.43478,0.000000,0.041667,0.000000,2.604167,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,NaN
72,2014-04-05,1570,228,11.500000,13.25,98,0,0.02870,0.000000,557.491289,16.0,16.0,0.0,0.0,0.0,0.02870,1570,1570,24.750000,0,1.207547,0.000000,0.000000,0,42.074814,0.646465,0.000000,22.524901,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
73,2014-04-06,2360,167,9.250000,12.50,162,2,0.02840,70.422535,176.056338,5.0,7.0,0.0,0.0,0.0,0.02840,2360,2360,21.750000,0.216216,0.400000,0.000000,0.000000,7.61325,14.084507,0.321839,0.000000,11.332362,0.000000,0.000000,0.000000,0.000000,0.000000,0.350877,NaN
74,2014-04-07,2270,200,11.750000,11.75,203,3,0.02100,142.857143,0.000000,0.0,3.0,0.0,0.0,0.0,0.02100,2270,2270,23.500000,0.255319,0.000000,0.000000,0.000000,12.1581,0.000000,0.127660,0.000000,6.079027,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,NaN
75,2014-04-08,2220,202,12.000000,12.00,70,0,0.03410,0.000000,146.627566,5.0,5.0,0.0,0.0,0.0,0.03410,2220,2220,24.000000,0,0.416667,0.000000,0.000000,0,12.218964,0.208333,0.000000,6.109482,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
76,2014-04-09,2950,133,11.750000,11.75,187,6,0.02930,204.778157,0.000000,0.0,6.0,0.0,0.0,0.0,0.02930,2950,2950,23.500000,0.510638,0.000000,0.000000,0.000000,17.4279,0.000000,0.255319,0.000000,8.713964,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,NaN
77,2014-04-10,2430,227,12.500000,13.25,221,0,0.01650,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.01650,2430,2430,25.750000,0,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN

In [25]:
#save csv

df_subset.to_csv(data_string + "2014_puyallup.csv")