### read 2009 data

In [1]:
#imports

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from urllib.request import urlopen
from bs4 import BeautifulSoup
from sys import platform
import io
import datetime

if platform == "linux" or platform == "linux2":
    data_string = "/home/maria/Documents/data/pied_piper/puyallup/"
    output_string = "/home/maria/Documents/output/pied_piper/puyallup/"

elif platform == "win32"or platform == "win64":
    data_string = "C:/Users/maria/OneDrive/Documents/data/pied_piper/puyallup/"
    output_string = "C:/Users/maria/OneDrive/Documents/output/pied_piper/puyallup/"

In [2]:
# #read file in Windows
try:
    df = pd.read_excel(
   io=data_string + "puyallup_chinook_2004-2018.xlsx",
   sheet_name ='2009_edited',
    header = [4]
)
except PermissionError:
    print("Permission Error. Close the file, if it is open.")
    

df.head()

,Date,flow,In_day,secchi_depth,chinook0_wild_num_day,trap_efficiency,chinook0_wild_day_num_estimate,In_night,secchi_depth_night,chinook0_wild_num_night,...,In_day.1,secchi_depth.1,chinook0_hatchery_num_day,trap_efficiency.1,In_night.1,secchi_depth_night.1,chinook0_hatchery_num_night,trap_efficiency.2,In.1,chinook0_hatchery_num
0,2009-02-03,1060.0,-,-,-,0.02797,0.0,-,165,-,...,-,-,0,0.02797,-,165,0,0.023331,20,0
1,2009-02-04,1050.0,10,165,0,0.02797,0.0,13.5,168,0,...,10,165,0,0.02797,13.5,168,0,0.023005,23.5,0
2,2009-02-05,1040.0,10.25,167,0,0.02797,0.0,13.25,168,0,...,10.25,167,0,0.02797,13.25,168,0,0.022676,23.5,0
3,2009-02-06,1030.0,10,164,0,0.02797,0.0,15.25,161,0,...,10,164,0,0.02797,15.25,161,0,0.022344,25.25,0
4,2009-02-07,1020.0,-,-,-,0.02797,0.0,-,160,-,...,-,-,0,0.02797,-,160,0,0.022008,24,0

In [7]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    display(df)

,Date,flow,In_day,secchi_depth,chinook0_wild_num_day,trap_efficiency,chinook0_wild_day_num_estimate,In_night,secchi_depth_night,chinook0_wild_num_night,trap_efficiency_night,chinook0_wild_night_num_estimate,In,secchi_depth_average,chinook0_wild_num,chinook0_wild_num_estimate,Unnamed: 16,Unnamed: 17,Unnamed: 18,Date.1,flow.1,In_day.1,secchi_depth.1,chinook0_hatchery_num_day,trap_efficiency.1,In_night.1,secchi_depth_night.1,chinook0_hatchery_num_night,trap_efficiency.2,In.1,chinook0_hatchery_num
0,2009-02-03,1060.000000,-,-,-,0.02797,0.000000,-,165,-,0.023331,0.000000,20,165.00,0,0.000000,NaN,NaN,NaN,2009-02-03,1060.000000,-,-,0,0.02797,-,165,0,0.023331,20,0
1,2009-02-04,1050.000000,10,165,0,0.02797,0.000000,13.5,168,0,0.023005,0.000000,23.5,166.50,0,0.000000,NaN,NaN,NaN,2009-02-04,1050.000000,10,165,0,0.02797,13.5,168,0,0.023005,23.5,0
2,2009-02-05,1040.000000,10.25,167,0,0.02797,0.000000,13.25,168,0,0.022676,0.000000,23.5,167.50,0,0.000000,NaN,NaN,NaN,2009-02-05,1040.000000,10.25,167,0,0.02797,13.25,168,0,0.022676,23.5,0
3,2009-02-06,1030.000000,10,164,0,0.02797,0.000000,15.25,161,0,0.022344,0.000000,25.25,162.50,0,0.000000,NaN,NaN,NaN,2009-02-06,1030.000000,10,164,0,0.02797,15.25,161,0,0.022344,25.25,0
4,2009-02-07,1020.000000,-,-,-,0.02797,0.000000,-,160,-,0.022008,0.000000,24,160.00,0,0.000000,NaN,NaN,NaN,2009-02-07,1020.000000,-,-,0,0.02797,-,160,0,0.022008,24,0
5,2009-02-08,1010.000000,-,-,-,0.02797,0.000000,-,160,-,0.021669,0.000000,22.25,160.00,0,0.000000,NaN,NaN,NaN,2009-02-08,1010.000000,-,-,0,0.02797,-,160,0,0.021669,22.25,0
6,2009-02-09,969.000000,10,160,0,0.02797,0.000000,13,157,0,0.020244,0.000000,23,158.50,0,0.000000,NaN,NaN,NaN,2009-02-09,969.000000,10,160,0,0.02797,13,157,0,0.020244,23,0
7,2009-02-10,969.000000,-,-,-,0.02797,0.000000,-,155,-,0.020244,0.000000,23.75,155.00,0,0.000000,NaN,NaN,NaN,2009-02-10,969.000000,-,-,0,0.02797,-,155,0,0.020244,23.75,0
8,2009-02-11,947.000000,-,-,-,0.02797,0.000000,-,155,-,0.019453,0.000000,24.25,155.00,0,0.000000,NaN,NaN,NaN,2009-02-11,947.000000,-,-,0,0.02797,-,155,0,0.019453,24.25,0
9,2009-02-12,900.000000,-,-,-,0.02797,0.000000,-,150,-,0.017702,0.000000,24,150.00,0,0.000000,NaN,NaN,NaN,2009-02-12,900.000000,-,-,0,0.02797,-,150,0,0.017702,24,0
10,2009-02-13,862.000000,-,-,-,0.02797,0.000000,-,147,-,0.016218,0.000000,23.75,147.00,0,0.000000,NaN,NaN,NaN,2009-02-13,862.000000,-,-,0,0.02797,-,147,0,0.016218,23.75,0
11,2009-02-14,806.000000,-,-,-,0.02797,0.000000,-,150,-,0.013908,0.000000,23.75,150.00,0,0.000000,NaN,NaN,NaN,2009-02-14,806.000000,-,-,0,0.02797,-,150,0,0.013908,23.75,0
12,2009-02-15,784.000000,-,-,-,0.02797,0.000000,-,145,-,0.012956,0.000000,25,145.00,0,0.000000,NaN,NaN,NaN,2009-02-15,784.000000,-,-,0,0.02797,-,145,0,0.012956,25,0
13,2009-02-16,764.000000,-,-,-,0.02797,0.000000,-,143,-,0.012067,0.000000,17.5,143.00,0,0.000000,NaN,NaN,NaN,2009-02-16,764.000000,-,-,0,0.02797,-,143,0,0.012067,17.5,0
14,2009-02-17,749.000000,-,-,-,0.02797,0.000000,-,143,-,0.011385,0.000000,23.25,143.00,0,0.000000,NaN,NaN,NaN,2009-02-17,749.000000,-,-,0,0.02797,-,143,0,0.011385,23.25,0
15,2009-02-18,729.000000,-,-,-,0.02797,0.000000,-,146,-,0.010454,0.000000,24,146.00,0,0.000000,NaN,NaN,NaN,2009-02-18,729.000000,-,-,0,0.02797,-,146,0,0.010454,24,0
16,2009-02-19,707.000000,-,-,-,0.02797,0.000000,-,144,-,0.009399,0.000000,24,144.00,0,0.000000,NaN,NaN,NaN,2009-02-19,707.000000,-,-,0,0.02797,-,144,0,0.009399,24,0
17,2009-02-20,690.000000,-,-,-,0.02797,0.000000,-,141,-,0.008562,0.000000,25,141.00,0,0.000000,NaN,NaN,NaN,2009-02-20,690.000000,-,-,0,0.02797,-,141,0,0.008562,25,0
18,2009-02-21,680.000000,-,-,-,0.02797,0.000000,-,139,-,0.008060,0.000000,23.75,139.00,0,0.000000,NaN,NaN,NaN,2009-02-21,680.000000,-,-,0,0.02797,-,139,0,0.008060,23.75,0
19,2009-02-22,681.000000,-,-,-,0.02797,0.000000,-,143,-,0.008111,0.000000,22.25,143.00,0,0.000000,NaN,NaN,NaN,2009-02-22,681.000000,-,-,0,0.02797,-,143,0,0.008111,22.25,0
20,2009-02-23,748.000000,10.25,143,0,0.02797,0.000000,13.25,151,0,0.011339,0.000000,23.5,147.00,0,0.000000,NaN,NaN,NaN,2009-02-23,748.000000,10.25,143,0,0.02797,13.25,151,0,0.011339,23.5,0
21,2009-02-24,887.000000,10.25,75,0,0.02797,0.000000,13,156,0,0.017202,0.000000,23.25,115.50,0,0.000000,NaN,NaN,NaN,2009-02-24,887.000000,10.25,75,0,0.02797,13,156,0,0.017202,23.25,0
22,2009-02-25,1010.000000,11,-,0,0.02797,0.000000,12,100,0,0.021669,0.000000,23,100.00,0,0.000000,NaN,NaN,NaN,2009-02-25,1010.000000,11,-,0,0.02797,12,100,0,0.021669,23,0
23,2009-02-26,1050.000000,10.75,112,0,0.02797,0.000000,13.25,151,0,0.023005,0.000000,24,131.50,0,0.000000,NaN,NaN,NaN,2009-02-26,1050.000000,10.75,112,0,0.02797,13.25,151,0,0.023005,24,0
24,2009-02-27,892.000000,-,-,-,0.02797,0.000000,-,146,-,0.017395,0.000000,26,146.00,0,0.000000,NaN,NaN,NaN,2009-02-27,892.000000,-,-,0,0.02797,-,146,0,0.017395,26,0
25,2009-02-28,845.000000,7.75,147,0,0.02797,0.000000,15.75,149,0,0.015533,0.000000,23.5,148.00,0,0.000000,NaN,NaN,NaN,2009-02-28,845.000000,7.75,147,0,0.02797,15.75,149,0,0.015533,23.5,0
26,2009-03-01,921.000000,9.25,154,0,0.02797,0.000000,12,152,0,0.018496,0.000000,21.25,153.00,0,0.000000,NaN,NaN,NaN,2009-03-01,921.000000,9.25,154,0,0.02797,12,152,0,0.018496,21.25,0
27,2009-03-02,1210.000000,12,118,0,0.02797,0.000000,14,-,1,0.027884,35.862704,26,118.00,1,35.862704,NaN,NaN,NaN,2009-03-02,1210.000000,12,118,0,0.02797,14,-,0,0.027884,26,0
28,2009-03-03,1275.846154,11.5,152,0,0.02797,0.000000,14.75,160,0,0.029707,0.000000,26.25,156.00,0,0.000000,NaN,NaN,NaN,2009-03-03,1275.846154,11.5,152,0,0.02797,14.75,160,0,0.029707,26.25,0
29,2009-03-04,1213.589744,-,-,-,0.02797,0.000000,-,162,1,0.027986,35.732118,23.25,162.00,1,35.732118,NaN,NaN,NaN,2009-03-04,1213.589744,-,-,0,0.02797,-,162,0,0.027986,23.25,0
30,2009-03-05,1151.333333,11,-,0,0.02797,0.000000,12,166,1,0.026174,38.205191,23,166.00,1,38.205191,NaN,NaN,NaN,2009-03-05,1151.333333,11,-,0,0.02797,12,166,0,0.026174,23,0
31,2009-03-06,1070.000000,11.75,162,0,0.02797,0.000000,11.75,163,0,0.023654,0.000000,23.5,162.50,0,0.000000,NaN,NaN,NaN,2009-03-06,1070.000000,11.75,162,0,0.02797,11.75,163,0,0.023654,23.5,0
32,2009-03-07,993.000000,10.75,160,0,0.02797,0.000000,14.25,158,0,0.021085,0.000000,25,159.00,0,0.000000,NaN,NaN,NaN,2009-03-07,993.000000,10.75,160,0,0.02797,14.25,158,0,0.021085,25,0
33,2009-03-08,943.000000,11.5,157,0,0.02797,0.000000,12.5,155,0,0.019308,0.000000,24,156.00,0,0.000000,NaN,NaN,NaN,2009-03-08,943.000000,11.5,157,0,0.02797,12.5,155,0,0.019308,24,0
34,2009-03-09,926.000000,10.75,155,0,0.02797,0.000000,12.25,151,0,0.018682,0.000000,23,153.00,0,0.000000,NaN,NaN,NaN,2009-03-09,926.000000,10.75,155,0,0.02797,12.25,151,0,0.018682,23,0
35,2009-03-10,871.000000,11.5,153,0,0.02797,0.000000,12.25,150,0,0.016576,0.000000,23.75,151.50,0,0.000000,NaN,NaN,NaN,2009-03-10,871.000000,11.5,153,0,0.02797,12.25,150,0,0.016576,23.75,0
36,2009-03-11,823.000000,10.5,149,0,0.02797,0.000000,12.75,148,0,0.014626,0.000000,23.25,148.50,0,0.000000,NaN,NaN,NaN,2009-03-11,823.000000,10.5,149,0,0.02797,12.75,148,0,0.014626,23.25,0
37,2009-03-12,786.000000,10.25,147,0,0.02797,0.000000,13.25,148,0,0.013043,0.000000,23.5,147.50,0,0.000000,NaN,NaN,NaN,2009-03-12,786.000000,10.25,147,0,0.02797,13.25,148,0,0.013043,23.5,0
38,2009-03-13,790.000000,10.25,148,0,0.02797,0.000000,14.25,150,0,0.013218,0.000000,24.5,149.00,0,0.000000,NaN,NaN,NaN,2009-03-13,790.000000,10.25,148,0,0.02797,14.25,150,0,0.013218,24.5,0
39,2009-03-14,819.000000,9.75,-,0,0.02797,0.000000,9.75,151,0,0.014458,0.000000,19.5,151.00,0,0.000000,NaN,NaN,NaN,2009-03-14,819.000000,9.75,-,0,0.02797,9.75,151,0,0.014458,19.5,0
40,2009-03-15,1020.000000,9.5,140,0,0.02797,0.000000,12.25,103,0,0.022008,0.000000,21.75,121.50,0,0.000000,NaN,NaN,NaN,2009-03-15,1020.000000,9.5,140,0,0.02797,12.25,103,0,0.022008,21.75,0
41,2009-03-16,1170.000000,11.5,106,0,0.02797,0.000000,12,89,0,0.026728,0.000000,23.5,97.50,0,0.000000,NaN,NaN,NaN,2009-03-16,1170.000000,11.5,106,0,0.02797,12,89,0,0.026728,23.5,0
42,2009-03-17,1130.000000,11,158,0,0.02797,0.000000,12.5,166,0,0.025531,0.000000,23.5,162.00,0,0.000000,NaN,NaN,NaN,2009-03-17,1130.000000,11,158,0,0.02797,12.5,166,0,0.025531,23.5,0
43,2009-03-18,1100.000000,11.25,159,0,0.02797,0.000000,13,153,0,0.024605,0.000000,24.25,156.00,0,0.000000,NaN,NaN,NaN,2009-03-18,1100.000000,11.25,159,0,0.02797,13,153,0,0.024605,24.25,0
44,2009-03-19,1070.000000,11.5,162,0,0.02797,0.000000,11.75,163,0,0.023654,0.000000,23.25,162.50,0,0.000000,NaN,NaN,NaN,2009-03-19,1070.000000,11.5,162,0,0.02797,11.75,163,0,0.023654,23.25,0
45,2009-03-20,1180.000000,11.75,132,0,0.02797,0.000000,13.25,76,0,0.027020,0.000000,25,104.00,0,0.000000,NaN,NaN,NaN,2009-03-20,1180.000000,11.75,132,0,0.02797,13.25,76,0,0.027020,25,0
46,2009-03-21,1520.000000,11,-,0,0.02797,0.000000,12.25,166,0,0.035730,0.000000,23.25,166.00,0,0.000000,NaN,NaN,NaN,2009-03-21,1520.000000,11,-,0,0.02797,12.25,166,0,0.035730,23.25,0
47,2009-03-22,1350.000000,9.5,170,0,0.02797,0.000000,12.75,177,0,0.031650,0.000000,22.25,173.50,0,0.000000,NaN,NaN,NaN,2009-03-22,1350.000000,9.5,170,0,0.02797,12.75,177,0,0.031650,22.25,0
48,2009-03-23,1230.000000,11.5,160,0,0.02797,0.000000,12,173,0,0.028448,0.000000,23.5,166.50,0,0.000000,NaN,NaN,NaN,2009-03-23,1230.000000,11.5,160,0,0.02797,12,173,0,0.028448,23.5,0
49,2009-03-24,1230.000000,6.25,170,0,0.02797,0.000000,17,170,0,0.028448,0.000000,23.25,170.00,0,0.000000,NaN,NaN,NaN,2009-03-24,1230.000000,6.25,170,0,0.02797,17,170,0,0.028448,23.25,0
50,2009-03-25,1620.000000,11.75,60,0,0.02797,0.000000,12,70,0,0.037922,0.000000,23.75,65.00,0,0.000000,NaN,NaN,NaN,2009-03-25,1620.000000,11.75,60,0,0.02797,12,70,0,0.037922,23.75,0
51,2009-03-26,1690.000000,9.5,108,0,0.02797,0.000000,13.75,129,0,0.039377,0.000000,23.25,118.50,0,0.000000,NaN,NaN,NaN,2009-03-26,1690.000000,9.5,108,0,0.02797,13.75,129,0,0.039377,23.25,0
52,2009-03-27,1480.000000,7.75,161,0,0.02797,0.000000,18.5,158,0,0.034813,0.000000,26.25,159.50,0,0.000000,NaN,NaN,NaN,2009-03-27,1480.000000,7.75,161,0,0.02797,18.5,158,0,0.034813,26.25,0
53,2009-03-28,1490.000000,9.5,100,0,0.02797,0.000000,13.5,110,0,0.035045,0.000000,23,105.00,0,0.000000,NaN,NaN,NaN,2009-03-28,1490.000000,9.5,100,0,0.02797,13.5,110,0,0.035045,23,0
54,2009-03-29,1650.000000,10.25,125,0,0.02797,0.000000,12,137,0,0.038553,0.000000,22.25,131.00,0,0.000000,NaN,NaN,NaN,2009-03-29,1650.000000,10.25,125,0,0.02797,12,137,0,0.038553,22.25,0
55,2009-03-30,1520.000000,11,151,0,0.02797,0.000000,12.25,167,0,0.035730,0.000000,23.25,159.00,0,0.000000,NaN,NaN,NaN,2009-03-30,1520.000000,11,151,0,0.02797,12.25,167,0,0.035730,23.25,0
56,2009-03-31,1640.000000,11.75,75,0,0.02797,0.000000,10,102,0,0.038344,0.000000,21.75,88.50,0,0.000000,NaN,NaN,NaN,2009-03-31,1640.000000,11.75,75,0,0.02797,10,102,0,0.038344,21.75,0
57,2009-04-01,1710.000000,8.75,134,0,0.02797,0.000000,14.75,99,0,0.039782,0.000000,23.5,116.50,0,0.000000,NaN,NaN,NaN,2009-04-01,1710.000000,8.75,134,0,0.02797,14.75,99,0,0.039782,23.5,0
58,2009-04-02,2160.000000,11.75,58,0,0.02797,0.000000,-,54,0,0.047819,0.000000,24,56.00,0,0.000000,NaN,NaN,NaN,2009-04-02,2160.000000,11.75,58,0,0.02797,-,54,0,0.047819,24,0
59,2009-04-03,2310.000000,10.75,81,1,0.02797,35.752516,12.75,104,0,0.050128,0.000000,23.5,92.50,1,35.752516,NaN,NaN,NaN,2009-04-03,2310.000000,10.75,81,0,0.02797,12.75,104,0,0.050128,23.5,0
60,2009-04-04,1870.000000,11.25,127,0,0.02797,0.000000,13,150,0,0.042859,0.000000,24.25,138.50,0,0.000000,NaN,NaN,NaN,2009-04-04,1870.000000,11.25,127,0,0.02797,13,150,0,0.042859,24.25,0
61,2009-04-05,1660.000000,10.5,160,0,0.02797,0.000000,12.5,147,0,0.038761,0.000000,23,153.50,0,0.000000,NaN,NaN,NaN,2009-04-05,1660.000000,10.5,160,0,0.02797,12.5,147,0,0.038761,23,0
62,2009-04-06,1580.000000,11.25,159,0,0.02797,0.000000,12.5,140,0,0.037062,0.000000,23.75,149.50,0,0.000000,NaN,NaN,NaN,2009-04-06,1580.000000,11.25,159,0,0.02797,12.5,140,0,0.037062,23.75,0
63,2009-04-07,1680.000000,12,150,0,0.02797,0.000000,10.25,170,0,0.039173,0.000000,22.25,160.00,0,0.000000,NaN,NaN,NaN,2009-04-07,1680.000000,12,150,0,0.02797,10.25,170,0,0.039173,22.25,0
64,2009-04-08,1870.000000,-,170,0,0.02797,0.000000,11.25,132,0,0.042859,0.000000,24,151.00,0,0.000000,NaN,NaN,NaN,2009-04-08,1870.000000,-,170,0,0.02797,11.25,132,0,0.042859,24,0
65,2009-04-09,1810.000000,13.5,153,0,0.02797,0.000000,11,166,0,0.041737,0.000000,24.5,159.50,0,0.000000,NaN,NaN,NaN,2009-04-09,1810.000000,13.5,153,0,0.02797,11,166,0,0.041737,24.5,0
66,2009-04-10,1700.000000,11.75,180,0,0.02797,0.000000,12.5,172,0,0.039580,0.000000,24.25,176.00,0,0.000000,NaN,NaN,NaN,2009-04-10,1700.000000,11.75,180,1,0.02797,12.5,172,0,0.039580,24.25,0
67,2009-04-11,1610.000000,11.75,190,0,0.02797,0.000000,13.25,180,0,0.037709,0.000000,25,185.00,0,0.000000,NaN,NaN,NaN,2009-04-11,1610.000000,11.75,190,1,0.02797,13.25,180,1,0.037709,25,2
68,2009-04-12,1640.000000,9.75,132,0,0.02797,0.000000,-,-,0,0.038344,0.000000,24,132.00,0,0.000000,NaN,NaN,NaN,2009-04-12,1640.000000,9.75,132,0,0.02797,-,-,1,0.038344,24,1
69,2009-04-13,2740.000000,-,69,0,0.02797,0.000000,10.75,77,0,0.056001,0.000000,24,73.00,0,0.000000,NaN,NaN,NaN,2009-04-13,2740.000000,-,69,0,0.02797,10.75,77,2,0.056001,24,2
70,2009-04-14,2320.000000,11.5,102,0,0.02797,0.000000,12.5,122,1,0.050277,19.889932,24,112.00,1,19.889932,NaN,NaN,NaN,2009-04-14,2320.000000,11.5,102,6,0.02797,12.5,122,2,0.050277,24,8
71,2009-04-15,2020.000000,11.5,131,0,0.02797,0.000000,11,180,0,0.045513,0.000000,22.5,155.50,0,0.000000,NaN,NaN,NaN,2009-04-15,2020.000000,11.5,131,1,0.02797,11,180,0,0.045513,22.5,1
72,2009-04-16,1750.000000,12.5,170,1,0.02797,35.752516,11.5,190,0,0.040578,0.000000,24,180.00,1,35.752516,NaN,NaN,NaN,2009-04-16,1750.000000,12.5,170,1,0.02797,11.5,190,16,0.040578,24,17
73,2009-04-17,1790.000000,12,165,0,0.02797,0.000000,12.25,138,0,0.041355,0.000000,24.25,151.50,0,0.000000,NaN,NaN,NaN,2009-04-17,1790.000000,12,165,9,0.02797,12.25,138,41,0.041355,24.25,50
74,2009-04-18,2000.000000,11.5,160,1,0.02797,35.752516,11.25,173,1,0.045171,22.138076,22.75,166.50,2,57.890591,NaN,NaN,NaN,2009-04-18,2000.000000,11.5,160,5,0.02797,11.25,173,4,0.045171,22.75,9
75,2009-04-19,1820.000000,12.25,175,0,0.02797,0.000000,11.25,170,0,0.041927,0.000000,23.5,172.50,0,0.000000,NaN,NaN,NaN,2009-04-19,1820.000000,12.25,175,3,0.02797,11.25,>170,1,0.041927,23.5,4
76,2009-04-20,1930.000000,11.75,170,0,0.02797,0.000000,10.5,114,0,0.043945,0.000000,22.25,142.00,0,0.000000,NaN,NaN,NaN,2009-04-20,1930.000000,11.75,170,1,0.02797,10.5,114,0,0.043945,22.25,1
77,2009-04-21,2360.000000,11.5,111,0,0.02797,0.000000,12.25,99,0,0.050865,0.000000,23.75,105.00,0,0.000000,NaN,NaN,NaN,2009-04-21,2360.000000,11.5,111,5,0.02797,12.25,99,0,0.050865,23.75,5
78,2009-04-22,2670.000000,12,106,0,0.02797,0.000000,10.75,130,2,0.055110,36.290869,22.75,118.00,2,36.290869,NaN,NaN,NaN,2009-04-22,2670.000000,12,106,6,0.02797,10.75,130,1,0.055110,22.75,7
79,2009-04-23,2420.000000,13.25,162,1,0.02797,35.752516,11.5,196,1,0.051728,19.331746,24.75,179.00,2,55.084262,NaN,NaN,NaN,2009-04-23,2420.000000,13.25,162,3,0.02797,11.5,196,1,0.051728,24.75,4
80,2009-04-24,2190.000000,12.5,210,0,0.02797,0.000000,13,201,0,0.048293,0.000000,25.5,205.50,0,0.000000,NaN,NaN,NaN,2009-04-24,2190.000000,12.5,210,0,0.02797,13,201,2,0.048293,25.5,2
81,2009-04-25,2110.000000,10.25,200,0,0.02797,0.000000,12.75,210,1,0.047013,21.270782,23,205.00,1,21.270782,NaN,NaN,NaN,2009-04-25,2110.000000,10.25,200,0,0.02797,12.75,210,0,0.047013,23,0
82,2009-04-26,1990.000000,11,220,0,0.02797,0.000000,11.75,221,1,0.044999,22.222907,22.75,220.50,1,22.222907,NaN,NaN,NaN,2009-04-26,1990.000000,11,220,0,0.02797,11.75,221,0,0.044999,22.75,0
83,2009-04-27,1870.000000,12.5,225,0,0.02797,0.000000,11.5,222,0,0.042859,0.000000,24,223.50,0,0.000000,NaN,NaN,NaN,2009-04-27,1870.000000,12.5,225,0,0.02797,11.5,222,0,0.042859,24,0
84,2009-04-28,1850.000000,12.5,210,1,0.02797,35.752516,11.5,205,0,0.042489,0.000000,24,207.50,1,35.752516,NaN,NaN,NaN,2009-04-28,1850.000000,12.5,210,0,0.02797,11.5,205,0,0.042489,24,0
85,2009-04-29,1860.000000,13,223,0,0.02797,0.000000,10.75,220,0,0.042675,0.000000,23.75,221.50,0,0.000000,NaN,NaN,NaN,2009-04-29,1860.000000,13,223,0,0.02797,10.75,220,0,0.042675,23.75,0
86,2009-04-30,1760.000000,12.25,215,1,0.02797,35.752516,11.25,203,0,0.040774,0.000000,23.5,209.00,1,35.752516,NaN,NaN,NaN,2009-04-30,1760.000000,12.25,215,0,0.02797,11.25,203,2,0.040774,23.5,2
87,2009-05-01,1670.000000,10.75,215,0,0.02797,0.000000,14.25,212,0,0.038968,0.000000,25,213.50,0,0.000000,NaN,NaN,NaN,2009-05-01,1670.000000,10.75,215,0,0.02797,14.25,212,1,0.038968,25,1
88,2009-05-02,1730.000000,11.5,217,0,0.02797,0.000000,10.75,202,1,0.040182,24.886667,22.25,209.50,1,24.886667,NaN,NaN,NaN,2009-05-02,1730.000000,10.75,217,0,0.02797,10.75,202,1,0.040182,22.25,1
89,2009-05-03,1980.000000,11.75,200,1,0.02797,35.752516,11.75,210,1,0.044825,22.308824,23.5,205.00,2,58.061339,NaN,NaN,NaN,2009-05-03,1980.000000,11.75,200,0,0.02797,11.75,210,0,0.044825,23.5,0
90,2009-05-04,1950.000000,11.75,-,1,0.02797,35.752516,11.5,164,1,0.044300,22.573306,23.25,164.00,2,58.325822,NaN,NaN,NaN,2009-05-04,1950.000000,11.75,-,0,0.02797,11.5,164,1,0.044300,23.25,1
91,2009-05-05,2290.000000,4,116,0,0.02797,0.000000,7.75,118,0,0.049829,0.000000,11.75,117.00,0,0.000000,NaN,NaN,NaN,2009-05-05,2290.000000,4,116,0,0.02797,7.75,118,0,0.049829,11.75,0
92,2009-05-06,2530.000000,6.75,140,2,0.02797,71.505031,1.5,81,0,0.053258,0.000000,8.25,110.50,2,71.505031,NaN,NaN,NaN,2009-05-06,2530.000000,6.75,140,2,0.02797,1.5,81,0,0.053258,8.25,2
93,2009-05-07,3280.000000,8.75,81,2,0.02797,71.505031,12.5,111,1,0.062189,16.080119,21.25,96.00,3,87.585150,NaN,NaN,NaN,2009-05-07,3280.000000,8.75,81,4,0.02797,12.5,111,4,0.062189,21.25,8
94,2009-05-08,2910.000000,12.5,138,1,0.02797,35.752516,12.25,175,0,0.058071,0.000000,24.75,156.50,1,35.752516,NaN,NaN,NaN,2009-05-08,2910.000000,12.5,138,0,0.02797,12.25,175,2,0.058071,24.75,2
95,2009-05-09,2480.000000,12.5,170,0,0.02797,0.000000,12.25,205,0,0.052571,0.000000,24.75,187.50,0,0.000000,NaN,NaN,NaN,2009-05-09,2480.000000,12.5,170,0,0.02797,12.25,205,1,0.052571,24.75,1
96,2009-05-10,2290.000000,10.5,200,0,0.02797,0.000000,11.75,226,0,0.049829,0.000000,22.25,213.00,0,0.000000,NaN,NaN,NaN,2009-05-10,2290.000000,10.5,200,0,0.02797,11.75,226,0,0.049829,22.25,0
97,2009-05-11,2450.000000,12.5,190,0,0.02797,0.000000,11.25,141,1,0.052152,19.174643,23.75,165.50,1,19.174643,NaN,NaN,NaN,2009-05-11,2450.000000,12.5,190,0,0.02797,11.25,141,0,0.052152,23.75,0
98,2009-05-12,2860.000000,12,148,5,0.02797,178.762578,12.25,162,2,0.057475,34.797711,24.25,155.00,7,213.560288,NaN,NaN,NaN,2009-05-12,2860.000000,12,148,0,0.02797,12.25,162,1,0.057475,24.25,1
99,2009-05-13,2720.000000,11,181,0,0.02797,0.000000,11.75,150,1,0.055749,17.937696,22.75,165.50,1,17.937696,NaN,NaN,NaN,2009-05-13,2720.000000,11,181,1,0.02797,11.75,150,1,0.055749,22.75,2
100,2009-05-14,3060.000000,-,160,1,0.02797,35.752516,9.75,124,2,0.059800,33.444674,24,142.00,3,69.197189,NaN,NaN,NaN,2009-05-14,3060.000000,-,160,1,0.02797,9.75,124,1,0.059800,24,2
101,2009-05-15,3070.000000,14.5,140,1,0.02797,35.752516,11.5,178,0,0.059912,0.000000,26,159.00,1,35.752516,NaN,NaN,NaN,2009-05-15,3070.000000,14.5,140,1,0.02797,11.5,178,0,0.059912,26,1
102,2009-05-16,2780.000000,11.25,180,2,0.02797,71.505031,11.75,-,0,0.056499,0.000000,23,180.00,2,71.505031,NaN,NaN,NaN,2009-05-16,2780.000000,11.25,180,0,0.02797,11.75,-,0,0.056499,23,0
103,2009-05-17,3000.000000,10.5,132,1,0.02797,35.752516,12.5,-,3,0.059119,50.745069,23,132.00,4,86.497585,NaN,NaN,NaN,2009-05-17,3000.000000,10.5,132,0,0.02797,12.5,-,0,0.059119,23,0
104,2009-05-18,3640.000000,-,117,1,0.02797,35.752516,-,70,0,0.065771,0.000000,24,93.50,1,35.752516,NaN,NaN,NaN,2009-05-18,3640.000000,-,117,0,0.02797,-,70,0,0.065771,24,0
105,2009-05-19,4030.000000,-,117,1,0.02797,35.752516,-,100,1,0.069272,14.435775,24,108.50,2,50.188291,NaN,NaN,NaN,2009-05-19,4030.000000,-,117,0,0.02797,-,100,0,0.069272,24,0

In [13]:
#some checks
pd.unique(df['In_day'])
np.where(df['In_day']!=df['In_day.1'])
np.where(df['In_night']!=df['In_night.1'])
np.where(df['secchi_depth']!=df['secchi_depth_night'])
# np.where(df['secchi_depth']-df['secchi_depth_night']>30)
#need to keep secchi_depth_night
#need to calculate CPUE
#need to change day_num to num_day

(array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
         66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
         79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
         92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
        105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
        118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 129, 130, 131,
        132, 133, 134, 135, 136, 137, 138, 140, 141, 142, 143, 144, 145,
        146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158,
        159, 160, 161, 163, 164, 165, 166, 167, 169, 170, 171, 173, 174]),)

In [ ]:
df = df.replace({'-':np.nan})
df = df.replace({'ST':np.nan})
df = df.replace({'Out':np.nan})
df = df.replace({'OUT':np.nan})

df_subset.loc[(df_subset['In_day'] == np.nan),'chinook0_wild_num_day':'chinook0_wild_perhour_day'] =np.nan

df_subset.loc[(df_subset['In_day'] == np.nan),'chinook0_hatchery_num_day':'chinook0_hatchery_perhour_day'] =np.nan

df_subset.loc[(df_subset['In_night'] == np.nan),'chinook0_wild_num_night':'chinook0_wild_perhour_night'] =np.nan

df_subset.loc[(df_subset['In_night'] == np.nan),'chinook0_hatchery_num_day':'chinook0_hatchery_perhour_night'] =np.nan

#need to edit these

In [18]:
1895/29

65.34482758620689