#### Goal - read 2006 puyallup data

In [1]:
#imports

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from urllib.request import urlopen
from bs4 import BeautifulSoup
from sys import platform
import io
import datetime

if platform == "linux" or platform == "linux2":
    data_string = "/home/maria/Documents/data/pied_piper/puyallup/"
    output_string = "/home/maria/Documents/output/pied_piper/puyallup/"

elif platform == "win32"or platform == "win64":
    data_string = "C:/Users/maria/OneDrive/Documents/data/pied_piper/puyallup/"
    output_string = "C:/Users/maria/OneDrive/Documents/output/pied_piper/puyallup/"

In [4]:
# #read file in Windows
try:
    df = pd.read_excel(
   io=data_string + "puyallup_chinook_2004-2018.xlsx",
   sheet_name ='2006_edited',
    header = [2]
)
except PermissionError:
    print("Permission Error. Close the file, if it is open.")
    

df.head()

,Date,Flow (cfs),Hours of Day,Secchi Depth Day (cm),# of Fish Caught (Day),CPUE (Day),Estimated Production Day,Hours of Night,Secchi Depth Night (cm),# of Fish Caught (Night),...,Hours of Night,Secchi Depth Night (cm).1,# of Fish Caught (Night).1,CPUE (Night).1,Estimated Production Night.1,Total Hours.1,Total Fish Captured,Total CPUE.1,Daily Production Estimates.1,Unnamed: 34
0,2006-02-24,1590.0,-,-,-,-,0.000000,15,145,1,...,-,145,0,15,0.0,15,0.0,0,0.0,NaN
1,2006-02-25,1370.0,-,109,-,-,0.000000,-,109,-,...,-,109,-,-,0.0,12,0.0,0,0.0,NaN
2,2006-02-26,1330.0,8.5,101,0,0,0.000000,14.5,101,0,...,14.5,101,0,0,0.0,23,0.0,0,0.0,NaN
3,2006-02-27,1640.0,10,115,0,0,0.000000,13.25,107,2,...,13.25,107,0,0,0.0,23.25,0.0,0,0.0,NaN
4,2006-02-28,2220.0,8.75,91,2,0.228571,329.489292,12.5,129.5,4,...,12.5,129.5,0,0,0.0,21.25,0.0,0,0.0,NaN

In [7]:
list(df)

df_rename = df.rename(columns = {
    'Flow (cfs)':'flow',
    'Secchi Depth Day (cm)':'secchi_depth',
    'Hours of Day':'In_day',
    '# of Fish Caught (Day)':'chinook0_wild_num_day',
    'CPUE (Day)':'chinook0_wild_perhour_day',
    'Estimated Production Day':'chinook0_wild_day_num_estimate',
    
    'Hours of Night':'In_night',
    
    '# of Fish Caught (Night)': 'chinook0_wild_num_night',
    'CPUE (Night)':'chinook0_wild_perhour_night',
    'Estimated Production Night':'chinook0_wild_night_num_estimate',
    
    'Total CPUE':'chinook0_wild_perhour',
    'Total fish captured':'chinook0_wild_num',
    'Daily Production Estimates':'chinook0_wild_num_estimate',
    
    'Total Hours':'In',
    
    '# of Fish Caught (Day).1':'chinook0_hatchery_num_day',
    'CPUE (Day).1':'chinook0_hatchery_perhour_day',
    'Estimated Production Day.1':'chinook0_hatchery_day_num_estimate',
    
    'Hours of Night':'In_night',
    
    '# of Fish Caught (Night).1':'chinook0_hatchery_num_night',
    'CPUE (Night).1':'chinook0_hatchery_perhour_night',
    'Estimated Production Night.1':'chinook0_hatchery_night_num_estimate',
    
    'Total CPUE.1':'chinook0_hatchery_perhour',
    'Total Fish Captured':'chinook0_hatchery_num',
    'Daily Production Estimates.1':'chinook0_hatchery_num_estimate'
    
}, inplace = False)

df_rename.head()

,Date,flow,In_day,secchi_depth,chinook0_wild_num_day,chinook0_wild_perhour_day,chinook0_wild_day_num_estimate,In_night,Secchi Depth Night (cm),chinook0_wild_num_night,...,Hours of Night,Secchi Depth Night (cm).1,chinook0_hatchery_num_night,chinook0_hatchery_perhour_night,chinook0_hatchery_night_num_estimate,Total Hours.1,chinook0_hatchery_num,chinook0_hatchery_perhour,chinook0_hatchery_num_estimate,Unnamed: 34
0,2006-02-24,1590.0,-,-,-,-,0.000000,15,145,1,...,-,145,0,15,0.0,15,0.0,0,0.0,NaN
1,2006-02-25,1370.0,-,109,-,-,0.000000,-,109,-,...,-,109,-,-,0.0,12,0.0,0,0.0,NaN
2,2006-02-26,1330.0,8.5,101,0,0,0.000000,14.5,101,0,...,14.5,101,0,0,0.0,23,0.0,0,0.0,NaN
3,2006-02-27,1640.0,10,115,0,0,0.000000,13.25,107,2,...,13.25,107,0,0,0.0,23.25,0.0,0,0.0,NaN
4,2006-02-28,2220.0,8.75,91,2,0.228571,329.489292,12.5,129.5,4,...,12.5,129.5,0,0,0.0,21.25,0.0,0,0.0,NaN

In [19]:
#note to self - need flow and secchi depth even on days the trap was not in!!!!

df_subset = df_rename[['Date', 'flow', 'secchi_depth','In_day','In_night','In',
                'chinook0_wild_num_day','chinook0_wild_perhour_day',
                'chinook0_wild_num_night','chinook0_wild_perhour_night',
                'chinook0_hatchery_num_day','chinook0_hatchery_perhour_day',
                'chinook0_hatchery_num_night','chinook0_hatchery_perhour_night',
                'chinook0_wild_perhour','chinook0_hatchery_perhour',
                'chinook0_wild_day_num_estimate','chinook0_wild_night_num_estimate',
               'chinook0_hatchery_day_num_estimate','chinook0_hatchery_night_num_estimate']]

df_subset.loc[(df_subset['In_day'] == '-'),'In_day':'chinook0_hatchery_night_num_estimate'] =np.nan
df_subset.loc[(df_subset['In_day'] == 'Out'),'In_day':'chinook0_hatchery_night_num_estimate'] =np.nan
df_subset.loc[(df_subset['In_day'] == 'Out '),'In_day':'chinook0_hatchery_night_num_estimate'] =np.nan
df_subset.loc[(df_subset['In_day'] == 'OUT'),'In_day':'chinook0_hatchery_night_num_estimate'] =np.nan
df_subset.loc[(df_subset['In_day'] == 'ST'),'In_day':'chinook0_hatchery_night_num_estimate'] =np.nan

df_subset.loc[(df_subset['In_night'] == '-'),'In_day':'chinook0_hatchery_night_num_estimate'] =np.nan
df_subset.loc[(df_subset['In_night'] == 'ST'),'In_day':'chinook0_hatchery_night_num_estimate'] =np.nan
df_subset.loc[(df_subset['In_night'] == 'Out'),'In_day':'chinook0_hatchery_night_num_estimate'] =np.nan
df_subset.loc[(df_subset['In_night'] == 'Out '),'In_day':'chinook0_hatchery_night_num_estimate'] =np.nan
df_subset.loc[(df_subset['In_night'] == 'OUT'),'In_day':'chinook0_hatchery_night_num_estimate'] =np.nan

df_subset['chinook0_wild_perhour_day_estimate'] = (df_subset['chinook0_wild_day_num_estimate']/
                                                   df_subset['In_day'])
df_subset['chinook0_wild_perhour_night_estimate'] = (df_subset['chinook0_wild_night_num_estimate']/
                                                   df_subset['In_night'])
df_subset['chinook0_wild_perhour_estimate'] = ((df_subset['chinook0_wild_day_num_estimate']+df_subset['chinook0_wild_night_num_estimate'])/
                                                   df_subset['In'])

df_subset['chinook0_hatchery_perhour_day_estimate'] = (df_subset['chinook0_hatchery_day_num_estimate']/
                                                   df_subset['In_day'])
df_subset['chinook0_hatchery_perhour_night_estimate'] = (df_subset['chinook0_hatchery_night_num_estimate']/
                                                   df_subset['In_night'])
df_subset['chinook0_hatchery_perhour_estimate'] = ((df_subset['chinook0_hatchery_day_num_estimate']+df_subset['chinook0_hatchery_night_num_estimate'])/
                                                   df_subset['In'])

with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    display(df_subset)

C:\Users\maria\anaconda3\lib\site-packages\pandas\core\indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)
C:\Users\maria\AppData\Local\Temp/ipykernel_2748/4041813101.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['chinook0_wild_perhour_day_estimate'] = (df_subset['chinook0_wild_day_num_estimate']/
C:\Users\maria\AppData\Local\Temp/ipykernel_2748/4041813101.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['chinook0_wild_perhour_night_estimate'] = (df_subset['chinook0_wild_night_num_estimate']/
C:\Users\maria\AppData\Local\Temp/ipykernel_2748/4041813101.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['chinook0_wild_perhour_estimate'] = ((df_subset['chinook0_wild_day_num_estimate']+df_subset['chinook0_wild_night_num_estimate'])/
C:\Users\maria\AppData\Local\Temp/ipykernel_2748/4041813101.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['chinook0_hatchery_perhour_day_estimate'] = (df_subset['chinook0_hatchery_day_num_estimate']/
C:\Users\maria\AppData\Local\Temp/ipykernel_2748/4041813101.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['chinook0_hatchery_perhour_night_estimate'] = (df_subset['chinook0_hatchery_night_num_estimate']/
C:\Users\maria\AppData\Local\Temp/ipykernel_2748/4041813101.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['chinook0_hatchery_perhour_estimate'] = ((df_subset['chinook0_hatchery_day_num_estimate']+df_subset['chinook0_hatchery_night_num_estimate'])/

,Date,flow,secchi_depth,In_day,In_night,In,chinook0_wild_num_day,chinook0_wild_perhour_day,chinook0_wild_num_night,chinook0_wild_perhour_night,chinook0_hatchery_num_day,chinook0_hatchery_perhour_day,chinook0_hatchery_num_night,chinook0_hatchery_perhour_night,chinook0_wild_perhour,chinook0_hatchery_perhour,chinook0_wild_day_num_estimate,chinook0_wild_night_num_estimate,chinook0_hatchery_day_num_estimate,chinook0_hatchery_night_num_estimate,chinook0_wild_perhour_day_estimate,chinook0_wild_perhour_night_estimate,chinook0_wild_perhour_estimate,chinook0_hatchery_perhour_day_estimate,chinook0_hatchery_perhour_night_estimate,chinook0_hatchery_perhour_estimate
0,2006-02-24,1590.0000,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2006-02-25,1370.0000,109,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2006-02-26,1330.0000,101,8.5,14.5,23,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
3,2006-02-27,1640.0000,115,10,13.25,23.25,0,0,2,0.150943,0,0,0,0,0.086022,0,0.000000,99.304866,0.000000,0.000000,0.0,7.494707,4.271177,0.0,0.0,0.0
4,2006-02-28,2220.0000,91,8.75,12.5,21.25,2,0.228571,4,0.32,0,0,0,0,0.282353,0,329.489292,198.609732,0.000000,0.000000,37.655919,15.888779,24.851719,0.0,0.0,0.0
5,2006-03-01,2000.0000,168,9,13.75,22.75,0,0,1,0.072727,0,0,0,0,0.043956,0,0.000000,49.652433,0.000000,0.000000,0.0,3.611086,2.182525,0.0,0.0,0.0
6,2006-03-02,1830.0000,195,9,14.75,23.75,0,0,1,0.067797,0,0,0,0,0.042105,0,0.000000,49.652433,0.000000,0.000000,0.0,3.366267,2.090629,0.0,0.0,0.0
7,2006-03-03,1650.0000,210,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2006-03-04,1550.0000,113,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2006-03-05,1470.0000,215,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2006-03-06,1410.0000,204,10.25,13.5,23.75,0,0,1,0.074074,0,0,0,0,0.042105,0,0.000000,49.652433,0.000000,0.000000,0.0,3.677958,2.090629,0.0,0.0,0.0
11,2006-03-07,1390.0000,210,9.25,13.25,22.5,0,0,1,0.075472,0,0,0,0,0.044444,0,0.000000,49.652433,0.000000,0.000000,0.0,3.747353,2.206775,0.0,0.0,0.0
12,2006-03-08,1410.0000,89,8.75,14.25,23,0,0,1,0.070175,0,0,0,0,0.043478,0,0.000000,49.652433,0.000000,0.000000,0.0,3.484381,2.158801,0.0,0.0,0.0
13,2006-03-09,1510.0000,210,9.25,14,23.25,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
14,2006-03-10,1400.0000,206,9.5,15,24.5,0,0,2,0.133333,0,0,0,0,0.081633,0,0.000000,99.304866,0.000000,0.000000,0.0,6.620324,4.05326,0.0,0.0,0.0
15,2006-03-11,1350.0000,201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2006-03-12,1300.0000,202,8.5,13.75,22.25,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
17,2006-03-13,1270.0000,192,9.5,13.5,23,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
18,2006-03-14,1260.0000,192,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2006-03-15,1230.0000,201,9.25,14,23.25,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
20,2006-03-16,1220.0000,195,9.75,13.75,23.5,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
21,2006-03-17,1210.0000,196,10,15.25,25.25,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
22,2006-03-18,1290.0000,205,8.25,12.25,20.5,0,0,1,0.081633,0,0,0,0,0.04878,0,0.000000,49.652433,0.000000,0.000000,0.0,4.05326,2.42207,0.0,0.0,0.0
23,2006-03-19,1270.0000,185,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2006-03-20,1230.0000,198,10.5,13,23.5,1,0.095238,0,0,0,0,0,0,0.042553,0,164.744646,0.000000,0.000000,0.000000,15.689966,0.0,7.01041,0.0,0.0,0.0
25,2006-03-21,1210.0000,192,7.5,15,22.5,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
26,2006-03-22,1190.0000,190,10.25,15,25.25,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
27,2006-03-23,1180.0000,187,10.5,13,23.5,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
28,2006-03-24,1230.0000,190,9.5,13.5,23,0,0,2,0.148148,0,0,0,0,0.086957,0,0.000000,99.304866,0.000000,0.000000,0.0,7.355916,4.317603,0.0,0.0,0.0
29,2006-03-25,1240.0000,190,7.5,14.25,21.75,1,0.133333,1,0.070175,0,0,0,0,0.091954,0,164.744646,49.652433,0.000000,0.000000,21.965953,3.484381,9.857337,0.0,0.0,0.0
30,2006-03-26,1200.0000,192,8,15,23,0,0,1,0.066667,0,0,0,0,0.043478,0,0.000000,49.652433,0.000000,0.000000,0.0,3.310162,2.158801,0.0,0.0,0.0
31,2006-03-27,1180.0000,188,11,12.5,23.5,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
32,2006-03-28,1190.0000,190,10.25,13,23.25,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
33,2006-03-29,1210.0000,190,9.5,14,23.5,0,0,1,0.071429,0,0,0,0,0.042553,0,0.000000,49.652433,0.000000,0.000000,0.0,3.546602,2.112869,0.0,0.0,0.0
34,2006-03-30,1210.0000,190,10,13.25,23.25,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
35,2006-03-31,1210.0000,191.5,9.5,14.25,23.75,0,0,1,0.070175,0,0,0,0,0.042105,0,0.000000,49.652433,0.000000,0.000000,0.0,3.484381,2.090629,0.0,0.0,0.0
36,2006-04-01,1370.0000,200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,2006-04-02,1350.0000,190,8.5,11.25,19.75,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
38,2006-04-03,1290.0000,197,12,10.25,22.25,0,0,2,0.195122,0,0,0,0,0.089888,0,0.000000,99.304866,0.000000,0.000000,0.0,9.68828,4.46314,0.0,0.0,0.0
39,2006-04-04,1350.0000,202,13,13,26,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
40,2006-04-05,1302.0000,198,10.5,12.5,23,0,0,1,0.08,0,0,0,0,0.043478,0,0.000000,49.652433,0.000000,0.000000,0.0,3.972195,2.158801,0.0,0.0,0.0
41,2006-04-06,1274.0000,195,10.5,13,23.5,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
42,2006-04-07,1254.0000,195,10.75,12.75,23.5,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
43,2006-04-08,1299.0000,196.5,10.5,15,25.5,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
44,2006-04-09,1501.0000,200,11.75,13,24.75,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
45,2006-04-10,1399.0000,198,11,11.25,22.25,0,0,1,0.088889,0,0,0,0,0.044944,0,0.000000,49.652433,0.000000,0.000000,0.0,4.41355,2.23157,0.0,0.0,0.0
46,2006-04-11,1340.0000,195,11.75,12,23.75,2,0.170213,1,0.083333,0,0,0,0,0.126316,0,329.489292,49.652433,0.000000,0.000000,28.041642,4.137703,15.963862,0.0,0.0,0.0
47,2006-04-12,1361.0000,201,12.25,11,23.25,1,0.081633,0,0,0,0,0,0,0.043011,0,164.744646,0.000000,0.000000,0.000000,13.448543,0.0,7.085791,0.0,0.0,0.0
48,2006-04-13,1431.0000,146,11.25,13,24.25,1,0.088889,0,0,0,0,0,0,0.041237,0,164.744646,0.000000,0.000000,0.000000,14.643969,0.0,6.793594,0.0,0.0,0.0
49,2006-04-14,2251.0000,100.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,2006-04-15,2547.0000,110,7.5,12.75,20.25,0,0,2,0.156863,0,0,0,0,0.098765,0,0.000000,99.304866,0.000000,0.000000,0.0,7.788617,4.903944,0.0,0.0,0.0
51,2006-04-16,2126.0000,181,10.25,10,20.25,0,0,1,0.1,0,0,0,0,0.049383,0,0.000000,49.652433,0.000000,0.000000,0.0,4.965243,2.451972,0.0,0.0,0.0
52,2006-04-17,1843.0000,200,10.75,12.5,23.25,0,0,1,0.08,0,0,0,0,0.043011,0,0.000000,49.652433,0.000000,0.000000,0.0,3.972195,2.135589,0.0,0.0,0.0
53,2006-04-18,1680.0000,206,10.5,12,22.5,0,0,2,0.166667,0,0,0,0,0.088889,0,0.000000,99.304866,0.000000,0.000000,0.0,8.275405,4.41355,0.0,0.0,0.0
54,2006-04-19,1538.0000,202,10,12.25,22.25,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
55,2006-04-20,1476.0000,195,9,14,23,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
56,2006-04-21,1623.0000,202,13,12,25,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
57,2006-04-22,1549.0000,190,9.75,11.25,21,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
58,2006-04-23,1467.0000,192.5,11.75,10.75,22.5,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
59,2006-04-24,1435.0000,193,11,11.5,22.5,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
60,2006-04-25,1429.0000,194,11.25,11.75,23,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
61,2006-04-26,1445.0000,190,11.25,12,23.25,0,0,1,0.083333,0,0,0,0,0.043011,0,0.000000,49.652433,0.000000,0.000000,0.0,4.137703,2.135589,0.0,0.0,0.0
62,2006-04-27,1416.0000,188,12,13,25,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
63,2006-04-28,1529.0000,203,11.25,17,28.25,0,0,4,0.235294,0,0,0,0,0.141593,0,0.000000,198.609732,0.000000,0.000000,0.0,11.682925,7.030433,0.0,0.0,0.0
64,2006-04-29,2078.0000,124,7.75,4.25,12,0,0,2,0.470588,0,0,0,0,0.166667,0,0.000000,99.304866,0.000000,0.000000,0.0,23.365851,8.275405,0.0,0.0,0.0
65,2006-04-30,2254.0000,250,10,10.25,20.25,1,0.1,0,0,0,0,0,0,0.049383,0,164.744646,0.000000,0.000000,0.000000,16.474465,0.0,8.135538,0.0,0.0,0.0
66,2006-05-01,1806.0000,198,12.25,11,23.25,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
67,2006-05-02,1541.0000,190,11,12,23,0,0,8,0.666667,0,0,2,0.166667,0.347826,0.086957,0.000000,397.219464,0.000000,99.304866,0.0,33.101622,17.270411,0.0,8.275405,4.317603
68,2006-05-03,1406.0000,190,11,12.75,23.75,0,0,2,0.156863,0,0,0,0,0.084211,0,0.000000,99.304866,0.000000,0.000000,0.0,7.788617,4.181258,0.0,0.0,0.0
69,2006-05-04,1229.3470,189,12,11.75,23.75,1,0.083333,0,0,0,0,0,0,0.042105,0,164.744646,0.000000,0.000000,0.000000,13.72872,0.0,6.936617,0.0,0.0,0.0
70,2006-05-05,1265.5210,197,12,13,25,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
71,2006-05-06,1354.7650,190,10,13.25,23.25,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
72,2006-05-07,1386.8680,190,11,12,23,0,0,4,0.333333,0,0,0,0,0.173913,0,0.000000,198.609732,0.000000,0.000000,0.0,16.550811,8.635206,0.0,0.0,0.0
73,2006-05-08,1422.2030,185,11.25,11.5,22.75,0,0,9,0.782609,0,0,0,0,0.395604,0,0.000000,446.871897,0.000000,0.000000,0.0,38.858426,19.642721,0.0,0.0,0.0
74,2006-05-09,1245.4720,192,12.5,11,23.5,0,0,1,0.090909,0,0,0,0,0.042553,0,0.000000,49.652433,0.000000,0.000000,0.0,4.513858,2.112869,0.0,0.0,0.0
75,2006-05-10,1163.3980,193.5,12.25,11.5,23.75,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
76,2006-05-11,1195.0280,194,11.75,11.5,23.25,0,0,0,0,1,0.085106,0,0,0,0.043011,0.000000,0.000000,164.744646,0.000000,0.0,0.0,0.0,14.020821,0.0,7.085791
77,2006-05-12,1243.8050,194,12,12,24,0,0,3,0.25,0,0,0,0,0.125,0,0.000000,148.957299,0.000000,0.000000,0.0,12.413108,6.206554,0.0,0.0,0.0
78,2006-05-13,1172.4940,191,10.25,14.25,24.5,1,0.097561,1,0.070175,0,0,0,0,0.081633,0,164.744646,49.652433,0.000000,0.000000,16.072648,3.484381,8.750901,0.0,0.0,0.0
79,2006-05-14,1147.9200,196,8,13.75,21.75,0,0,3,0.218182,0,0,0,0,0.137931,0,0.000000,148.957299,0.000000,0.000000,0.0,10.833258,6.848611,0.0,0.0,0.0
80,2006-05-15,1337.2240,145,11.5,13.75,25.25,0,0,5,0.363636,0,0,0,0,0.19802,0,0.000000,248.262165,0.000000,0.000000,0.0,18.05543,9.832165,0.0,0.0,0.0
81,2006-05-16,2263.0470,76,12,14,26,1,0.083333,0,0,0,0,0,0,0.038462,0,164.744646,0.000000,0.000000,0.000000,13.72872,0.0,6.336333,0.0,0.0,0.0
82,2006-05-17,2787.4190,38.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,2006-05-18,2985.9200,37,9.75,12,21.75,4,0.410256,13,1.083333,0,0,0,0,0.781609,0,198.609732,273.972603,0.000000,0.000000,20.370229,22.83105,21.727923,0.0,0.0,0.0
84,2006-05-19,2778.8010,50,12,11,23,4,0.333333,8,0.727273,0,0,0,0,0.521739,0,198.609732,168.598525,0.000000,0.000000,16.550811,15.327139,15.965576,0.0,0.0,0.0
85,2006-05-20,2548.2980,50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,2006-05-21,2110.3740,51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,2006-05-22,2072.3720,55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,2006-05-23,2100.0000,60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,2006-05-24,2215.0000,79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,2006-05-25,1991.0000,97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,2006-05-26,1946.0000,64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,2006-05-27,2351.0000,77,10.25,13,23.25,36,3.512195,26,2,0,0,4,0.307692,2.666667,0.172043,5930.807249,1290.963257,0.000000,198.609732,578.615341,99.304866,310.613785,0.0,15.277672,8.542354
93,2006-05-28,5602.0000,69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,2006-05-29,5084.0000,69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,2006-05-30,3181.0000,60,9.75,11.75,21.5,3,0.307692,29,2.468085,329,33.74359,5075,431.914894,1.488372,251.348837,148.957299,1439.920556,16335.650447,251986.097319,15.277672,122.54643,73.901296,1675.451328,21445.625304,12480.081291
96,2006-05-31,2520.0000,90,12.75,10.5,23.25,0,0,10,0.952381,114,8.941176,1130,110.243902,0.430108,54.086957,0.000000,496.524330,18780.889621,56107.249255,0.0,47.288031,21.355885,1473.010951,5343.547548,3220.99522
97,2006-06-01,2560.0000,50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,2006-06-02,4287.0000,33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,2006-06-03,4508.0000,33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,2006-06-04,3942.0000,27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,2006-06-05,3915.0000,36,11.25,10.75,22,14,1.244444,14,1.302326,91,8.088889,250,23.255814,1.272727,15.5,695.134062,295.047418,4518.371400,5268.703899,61.789694,27.446271,45.008249,401.633013,490.111991,444.867059
102,2006-06-06,3016.0000,85,11.5,12,23.5,6,0.521739,9,0.75,55,4.782609,114,9.5,0.638298,7.191489,988.467875,446.871897,9060.955519,5660.377358,85.953728,37.239325,61.078288,787.909176,471.698113,626.439697
103,2006-06-07,2535.0000,90,12,11.75,23.75,0,0,4,0.340426,30,2.5,56,4.765957,0.168421,3.621053,0.000000,198.609732,4942.339374,2780.536246,0.0,16.902956,8.362515,411.861614,236.641383,325.17371
104,2006-06-08,2238.0000,100,12,11.5,23.5,0,0,5,0.434783,21,1.75,28,2.434783,0.212766,2.085106,0.000000,248.262165,3459.637562,1390.268123,0.0,21.588014,10.564347,288.30313,120.89288,206.378965
105,2006-06-09,2099.0000,75,12,12.5,24.5,0,0,0,0,27,2.25,41,3.28,0,2.77551,0.000000,0.000000,4448.105437,2035.749752,0.0,0.0,0.0,370.675453,162.85998,264.647151
106,2006-06-10,2015.0000,70,11,12.75,23.75,0,0,0,0,18,1.636364,48,3.764706,0,2.778947,0.000000,0.000000,2965.403624,1011.591149,0.0,0.0,0.0,269.582148,79.340482,167.452411
107,2006-06-11,1903.0000,50,12.25,12.5,24.75,0,0,6,0.48,23,1.877551,39,3.12,0.242424,2.505051,0.000000,126.448894,1142.005958,821.917808,0.0,10.115911,5.109046,93.224976,65.753425,79.350455
108,2006-06-12,2034.0000,65,14,14,28,2,0.142857,9,0.642857,17,1.214286,69,4.928571,0.392857,3.071429,329.489292,189.673340,2800.658979,1454.162276,23.534949,13.548096,18.541523,200.04707,103.868734,151.957902
109,2006-06-13,2325.0000,40,11.25,12,23.25,4,0.355556,9,0.75,26,2.311111,36,3,0.55914,2.666667,198.609732,189.673340,1290.963257,758.693361,17.654198,15.806112,16.700347,114.75229,63.224447,88.157274
110,2006-06-14,2316.0000,40,12.25,11,23.25,0,0,0,0,58,4.734694,113,10.272727,0,7.354839,0.000000,0.000000,2879.841112,2381.454162,0.0,0.0,0.0,235.08907,216.495833,226.29227
111,2006-06-15,2250.1390,52,12,11.75,23.75,6,0.5,12,1.021277,31,2.583333,38,3.234043,0.757895,2.905263,297.914598,252.897787,1539.225422,800.842993,24.826216,21.523216,23.1921,128.268785,68.15685,98.529196
112,2006-06-16,2299.0710,52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113,2006-06-17,2292.8830,44,12,12,24,4,0.333333,0,0,14,1.166667,15,1.25,0.166667,1.208333,198.609732,0.000000,695.134062,316.122234,16.550811,0.0,8.275405,57.927838,26.343519,42.135679
114,2006-06-18,1895.9180,40,11.75,12.5,24.25,0,0,4,0.32,17,1.446809,11,0.88,0.164948,1.154639,0.000000,84.299262,844.091360,231.822972,0.0,6.743941,3.476258,71.837563,18.545838,44.367601
115,2006-06-19,1659.1270,80,12,11,23,1,0.083333,2,0.181818,3,0.25,3,0.272727,0.130435,0.26087,164.744646,42.149631,494.233937,63.224447,13.72872,3.831785,8.995403,41.186161,5.747677,24.237321
116,2006-06-20,1534.5730,97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,2006-06-21,1476.4280,72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,2006-06-22,1402.3420,78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,2006-06-23,1395.5210,52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,2006-06-24,1442.7230,33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121,2006-06-25,1586.3260,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,2006-06-26,1810.7180,21,12.25,12,24.25,9,0.734694,22,1.833333,0,0,2,0.166667,1.278351,0.082474,446.871897,463.645943,0.000000,42.149631,36.479339,38.637162,37.547127,0.0,3.512469,1.738129
123,2006-06-27,1964.9070,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124,2006-06-28,1901.0300,18,12,11.75,23.75,4,0.333333,12,1.021277,7,0.583333,8,0.680851,0.673684,0.631579,198.609732,252.897787,347.567031,168.598525,16.550811,21.523216,19.010843,28.963919,14.348811,21.733287
125,2006-06-29,1596.2600,27,11.75,11.5,23.25,2,0.170213,0,0,1,0.085106,124,10.782609,0.086022,5.376344,99.304866,0.000000,49.652433,2613.277134,8.451478,0.0,4.271177,4.225739,227.24149,114.534605
126,2006-06-30,1446.0280,25,12,12.75,24.75,1,0.083333,2,0.156863,5,0.416667,9,0.705882,0.121212,0.565657,49.652433,42.149631,248.262165,189.673340,4.137703,3.305853,3.709174,20.688514,14.87634,17.694364
127,2006-07-01,1556.4430,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128,2006-07-02,1539.0370,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
129,2006-07-03,1602.8490,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,2006-07-04,1764.4270,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
131,2006-07-05,1772.8260,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132,2006-07-06,1605.1260,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
133,2006-07-07,1361.6280,30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134,2006-07-08,1272.4580,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
135,2006-07-09,1385.5600,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
df_subset['chinook0_wild_perhour_total'] = (df_subset['chinook0_wild_perhour_day'] + 
                                            df_subset['chinook0_wild_perhour_night'])

df_subset['chinook0_hatchery_perhour_total'] = (df_subset['chinook0_hatchery_perhour_day'] + 
                                            df_subset['chinook0_hatchery_perhour_night'])

df_subset['chinook0_wild_day_fraction'] = np.nan
df_subset['chinook0_hatchery_day_fraction'] = np.nan
n = len(df_subset['chinook0_wild_perhour_total'])

for i in range(n):
#     print(i)
    if df_subset['chinook0_wild_perhour_day'].loc[i]==0 and df_subset['chinook0_wild_perhour_total'].loc[i] == 0:
        df_subset['chinook0_wild_day_fraction'].loc[i] = np.nan
    
    elif df_subset['chinook0_wild_perhour_day'].loc[i]==np.nan and df_subset['chinook0_wild_perhour_total'].loc[i] == np.nan:
        df_subset['chinook0_wild_day_fraction'].loc[i] = np.nan
        
    elif df_subset['chinook0_wild_perhour_day'].loc[i]=='-' or df_subset['chinook0_wild_perhour_total'].loc[i] == '-':
        df_subset['chinook0_wild_day_fraction'].loc[i] = np.nan
        
    else:
        df_subset['chinook0_wild_day_fraction'].loc[i] = (df_subset['chinook0_wild_perhour_day'].loc[i]/
                                                          df_subset['chinook0_wild_perhour_total'].loc[i])
        
    if df_subset['chinook0_hatchery_perhour_day'].loc[i]==0 and df_subset['chinook0_hatchery_perhour_total'].loc[i] == 0:
        df_subset['chinook0_hatchery_day_fraction'].loc[i] = np.nan
        
    elif df_subset['chinook0_hatchery_perhour_day'].loc[i]==np.nan and df_subset['chinook0_hatchery_perhour_total'].loc[i] == np.nan:
        df_subset['chinook0_hatchery_day_fraction'].loc[i] = np.nan
        
    elif df_subset['chinook0_hatchery_perhour_day'].loc[i]=='-' or df_subset['chinook0_hatchery_perhour_total'].loc[i] == '-':
        df_subset['chinook0_hatchery_day_fraction'].loc[i] = np.nan
        
    else:
        df_subset['chinook0_hatchery_day_fraction'].loc[i] = (df_subset['chinook0_hatchery_perhour_day'].loc[i]/
                                                          df_subset['chinook0_hatchery_perhour_total'].loc[i])
        
with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    display(df_subset)

C:\Users\maria\AppData\Local\Temp/ipykernel_2748/3419875960.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['chinook0_wild_perhour_total'] = (df_subset['chinook0_wild_perhour_day'] +
C:\Users\maria\AppData\Local\Temp/ipykernel_2748/3419875960.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['chinook0_hatchery_perhour_total'] = (df_subset['chinook0_hatchery_perhour_day'] +
C:\Users\maria\AppData\Local\Temp/ipykernel_2748/3419875960.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['chinook0_wild_day_fraction'] = np.nan
C:\Users\maria\AppData\Local\Temp/ipykernel_2748/3419875960.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['chinook0_hatchery_day_fraction'] = np.nan
C:\Users\maria\anaconda3\lib\site-packages\pandas\core\indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

,Date,flow,secchi_depth,In_day,In_night,In,chinook0_wild_num_day,chinook0_wild_perhour_day,chinook0_wild_num_night,chinook0_wild_perhour_night,chinook0_hatchery_num_day,chinook0_hatchery_perhour_day,chinook0_hatchery_num_night,chinook0_hatchery_perhour_night,chinook0_wild_perhour,chinook0_hatchery_perhour,chinook0_wild_day_num_estimate,chinook0_wild_night_num_estimate,chinook0_hatchery_day_num_estimate,chinook0_hatchery_night_num_estimate,chinook0_wild_perhour_day_estimate,chinook0_wild_perhour_night_estimate,chinook0_wild_perhour_estimate,chinook0_hatchery_perhour_day_estimate,chinook0_hatchery_perhour_night_estimate,chinook0_hatchery_perhour_estimate,chinook0_wild_perhour_total,chinook0_hatchery_perhour_total,chinook0_wild_day_fraction,chinook0_hatchery_day_fraction
0,2006-02-24,1590.0000,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2006-02-25,1370.0000,109,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2006-02-26,1330.0000,101,8.5,14.5,23,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
3,2006-02-27,1640.0000,115,10,13.25,23.25,0,0,2,0.150943,0,0,0,0,0.086022,0,0.000000,99.304866,0.000000,0.000000,0.0,7.494707,4.271177,0.0,0.0,0.0,0.150943,0,0.000000,NaN
4,2006-02-28,2220.0000,91,8.75,12.5,21.25,2,0.228571,4,0.32,0,0,0,0,0.282353,0,329.489292,198.609732,0.000000,0.000000,37.655919,15.888779,24.851719,0.0,0.0,0.0,0.548571,0,0.416667,NaN
5,2006-03-01,2000.0000,168,9,13.75,22.75,0,0,1,0.072727,0,0,0,0,0.043956,0,0.000000,49.652433,0.000000,0.000000,0.0,3.611086,2.182525,0.0,0.0,0.0,0.072727,0,0.000000,NaN
6,2006-03-02,1830.0000,195,9,14.75,23.75,0,0,1,0.067797,0,0,0,0,0.042105,0,0.000000,49.652433,0.000000,0.000000,0.0,3.366267,2.090629,0.0,0.0,0.0,0.067797,0,0.000000,NaN
7,2006-03-03,1650.0000,210,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2006-03-04,1550.0000,113,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2006-03-05,1470.0000,215,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2006-03-06,1410.0000,204,10.25,13.5,23.75,0,0,1,0.074074,0,0,0,0,0.042105,0,0.000000,49.652433,0.000000,0.000000,0.0,3.677958,2.090629,0.0,0.0,0.0,0.074074,0,0.000000,NaN
11,2006-03-07,1390.0000,210,9.25,13.25,22.5,0,0,1,0.075472,0,0,0,0,0.044444,0,0.000000,49.652433,0.000000,0.000000,0.0,3.747353,2.206775,0.0,0.0,0.0,0.075472,0,0.000000,NaN
12,2006-03-08,1410.0000,89,8.75,14.25,23,0,0,1,0.070175,0,0,0,0,0.043478,0,0.000000,49.652433,0.000000,0.000000,0.0,3.484381,2.158801,0.0,0.0,0.0,0.070175,0,0.000000,NaN
13,2006-03-09,1510.0000,210,9.25,14,23.25,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
14,2006-03-10,1400.0000,206,9.5,15,24.5,0,0,2,0.133333,0,0,0,0,0.081633,0,0.000000,99.304866,0.000000,0.000000,0.0,6.620324,4.05326,0.0,0.0,0.0,0.133333,0,0.000000,NaN
15,2006-03-11,1350.0000,201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2006-03-12,1300.0000,202,8.5,13.75,22.25,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
17,2006-03-13,1270.0000,192,9.5,13.5,23,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
18,2006-03-14,1260.0000,192,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2006-03-15,1230.0000,201,9.25,14,23.25,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
20,2006-03-16,1220.0000,195,9.75,13.75,23.5,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
21,2006-03-17,1210.0000,196,10,15.25,25.25,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
22,2006-03-18,1290.0000,205,8.25,12.25,20.5,0,0,1,0.081633,0,0,0,0,0.04878,0,0.000000,49.652433,0.000000,0.000000,0.0,4.05326,2.42207,0.0,0.0,0.0,0.081633,0,0.000000,NaN
23,2006-03-19,1270.0000,185,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2006-03-20,1230.0000,198,10.5,13,23.5,1,0.095238,0,0,0,0,0,0,0.042553,0,164.744646,0.000000,0.000000,0.000000,15.689966,0.0,7.01041,0.0,0.0,0.0,0.095238,0,1.000000,NaN
25,2006-03-21,1210.0000,192,7.5,15,22.5,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
26,2006-03-22,1190.0000,190,10.25,15,25.25,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
27,2006-03-23,1180.0000,187,10.5,13,23.5,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
28,2006-03-24,1230.0000,190,9.5,13.5,23,0,0,2,0.148148,0,0,0,0,0.086957,0,0.000000,99.304866,0.000000,0.000000,0.0,7.355916,4.317603,0.0,0.0,0.0,0.148148,0,0.000000,NaN
29,2006-03-25,1240.0000,190,7.5,14.25,21.75,1,0.133333,1,0.070175,0,0,0,0,0.091954,0,164.744646,49.652433,0.000000,0.000000,21.965953,3.484381,9.857337,0.0,0.0,0.0,0.203509,0,0.655172,NaN
30,2006-03-26,1200.0000,192,8,15,23,0,0,1,0.066667,0,0,0,0,0.043478,0,0.000000,49.652433,0.000000,0.000000,0.0,3.310162,2.158801,0.0,0.0,0.0,0.066667,0,0.000000,NaN
31,2006-03-27,1180.0000,188,11,12.5,23.5,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
32,2006-03-28,1190.0000,190,10.25,13,23.25,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
33,2006-03-29,1210.0000,190,9.5,14,23.5,0,0,1,0.071429,0,0,0,0,0.042553,0,0.000000,49.652433,0.000000,0.000000,0.0,3.546602,2.112869,0.0,0.0,0.0,0.071429,0,0.000000,NaN
34,2006-03-30,1210.0000,190,10,13.25,23.25,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
35,2006-03-31,1210.0000,191.5,9.5,14.25,23.75,0,0,1,0.070175,0,0,0,0,0.042105,0,0.000000,49.652433,0.000000,0.000000,0.0,3.484381,2.090629,0.0,0.0,0.0,0.070175,0,0.000000,NaN
36,2006-04-01,1370.0000,200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,2006-04-02,1350.0000,190,8.5,11.25,19.75,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
38,2006-04-03,1290.0000,197,12,10.25,22.25,0,0,2,0.195122,0,0,0,0,0.089888,0,0.000000,99.304866,0.000000,0.000000,0.0,9.68828,4.46314,0.0,0.0,0.0,0.195122,0,0.000000,NaN
39,2006-04-04,1350.0000,202,13,13,26,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
40,2006-04-05,1302.0000,198,10.5,12.5,23,0,0,1,0.08,0,0,0,0,0.043478,0,0.000000,49.652433,0.000000,0.000000,0.0,3.972195,2.158801,0.0,0.0,0.0,0.08,0,0.000000,NaN
41,2006-04-06,1274.0000,195,10.5,13,23.5,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
42,2006-04-07,1254.0000,195,10.75,12.75,23.5,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
43,2006-04-08,1299.0000,196.5,10.5,15,25.5,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
44,2006-04-09,1501.0000,200,11.75,13,24.75,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
45,2006-04-10,1399.0000,198,11,11.25,22.25,0,0,1,0.088889,0,0,0,0,0.044944,0,0.000000,49.652433,0.000000,0.000000,0.0,4.41355,2.23157,0.0,0.0,0.0,0.088889,0,0.000000,NaN
46,2006-04-11,1340.0000,195,11.75,12,23.75,2,0.170213,1,0.083333,0,0,0,0,0.126316,0,329.489292,49.652433,0.000000,0.000000,28.041642,4.137703,15.963862,0.0,0.0,0.0,0.253546,0,0.671329,NaN
47,2006-04-12,1361.0000,201,12.25,11,23.25,1,0.081633,0,0,0,0,0,0,0.043011,0,164.744646,0.000000,0.000000,0.000000,13.448543,0.0,7.085791,0.0,0.0,0.0,0.081633,0,1.000000,NaN
48,2006-04-13,1431.0000,146,11.25,13,24.25,1,0.088889,0,0,0,0,0,0,0.041237,0,164.744646,0.000000,0.000000,0.000000,14.643969,0.0,6.793594,0.0,0.0,0.0,0.088889,0,1.000000,NaN
49,2006-04-14,2251.0000,100.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,2006-04-15,2547.0000,110,7.5,12.75,20.25,0,0,2,0.156863,0,0,0,0,0.098765,0,0.000000,99.304866,0.000000,0.000000,0.0,7.788617,4.903944,0.0,0.0,0.0,0.156863,0,0.000000,NaN
51,2006-04-16,2126.0000,181,10.25,10,20.25,0,0,1,0.1,0,0,0,0,0.049383,0,0.000000,49.652433,0.000000,0.000000,0.0,4.965243,2.451972,0.0,0.0,0.0,0.1,0,0.000000,NaN
52,2006-04-17,1843.0000,200,10.75,12.5,23.25,0,0,1,0.08,0,0,0,0,0.043011,0,0.000000,49.652433,0.000000,0.000000,0.0,3.972195,2.135589,0.0,0.0,0.0,0.08,0,0.000000,NaN
53,2006-04-18,1680.0000,206,10.5,12,22.5,0,0,2,0.166667,0,0,0,0,0.088889,0,0.000000,99.304866,0.000000,0.000000,0.0,8.275405,4.41355,0.0,0.0,0.0,0.166667,0,0.000000,NaN
54,2006-04-19,1538.0000,202,10,12.25,22.25,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
55,2006-04-20,1476.0000,195,9,14,23,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
56,2006-04-21,1623.0000,202,13,12,25,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
57,2006-04-22,1549.0000,190,9.75,11.25,21,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
58,2006-04-23,1467.0000,192.5,11.75,10.75,22.5,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
59,2006-04-24,1435.0000,193,11,11.5,22.5,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
60,2006-04-25,1429.0000,194,11.25,11.75,23,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
61,2006-04-26,1445.0000,190,11.25,12,23.25,0,0,1,0.083333,0,0,0,0,0.043011,0,0.000000,49.652433,0.000000,0.000000,0.0,4.137703,2.135589,0.0,0.0,0.0,0.083333,0,0.000000,NaN
62,2006-04-27,1416.0000,188,12,13,25,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
63,2006-04-28,1529.0000,203,11.25,17,28.25,0,0,4,0.235294,0,0,0,0,0.141593,0,0.000000,198.609732,0.000000,0.000000,0.0,11.682925,7.030433,0.0,0.0,0.0,0.235294,0,0.000000,NaN
64,2006-04-29,2078.0000,124,7.75,4.25,12,0,0,2,0.470588,0,0,0,0,0.166667,0,0.000000,99.304866,0.000000,0.000000,0.0,23.365851,8.275405,0.0,0.0,0.0,0.470588,0,0.000000,NaN
65,2006-04-30,2254.0000,250,10,10.25,20.25,1,0.1,0,0,0,0,0,0,0.049383,0,164.744646,0.000000,0.000000,0.000000,16.474465,0.0,8.135538,0.0,0.0,0.0,0.1,0,1.000000,NaN
66,2006-05-01,1806.0000,198,12.25,11,23.25,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
67,2006-05-02,1541.0000,190,11,12,23,0,0,8,0.666667,0,0,2,0.166667,0.347826,0.086957,0.000000,397.219464,0.000000,99.304866,0.0,33.101622,17.270411,0.0,8.275405,4.317603,0.666667,0.166667,0.000000,0.000000
68,2006-05-03,1406.0000,190,11,12.75,23.75,0,0,2,0.156863,0,0,0,0,0.084211,0,0.000000,99.304866,0.000000,0.000000,0.0,7.788617,4.181258,0.0,0.0,0.0,0.156863,0,0.000000,NaN
69,2006-05-04,1229.3470,189,12,11.75,23.75,1,0.083333,0,0,0,0,0,0,0.042105,0,164.744646,0.000000,0.000000,0.000000,13.72872,0.0,6.936617,0.0,0.0,0.0,0.083333,0,1.000000,NaN
70,2006-05-05,1265.5210,197,12,13,25,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
71,2006-05-06,1354.7650,190,10,13.25,23.25,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
72,2006-05-07,1386.8680,190,11,12,23,0,0,4,0.333333,0,0,0,0,0.173913,0,0.000000,198.609732,0.000000,0.000000,0.0,16.550811,8.635206,0.0,0.0,0.0,0.333333,0,0.000000,NaN
73,2006-05-08,1422.2030,185,11.25,11.5,22.75,0,0,9,0.782609,0,0,0,0,0.395604,0,0.000000,446.871897,0.000000,0.000000,0.0,38.858426,19.642721,0.0,0.0,0.0,0.782609,0,0.000000,NaN
74,2006-05-09,1245.4720,192,12.5,11,23.5,0,0,1,0.090909,0,0,0,0,0.042553,0,0.000000,49.652433,0.000000,0.000000,0.0,4.513858,2.112869,0.0,0.0,0.0,0.090909,0,0.000000,NaN
75,2006-05-10,1163.3980,193.5,12.25,11.5,23.75,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
76,2006-05-11,1195.0280,194,11.75,11.5,23.25,0,0,0,0,1,0.085106,0,0,0,0.043011,0.000000,0.000000,164.744646,0.000000,0.0,0.0,0.0,14.020821,0.0,7.085791,0,0.085106,NaN,1.000000
77,2006-05-12,1243.8050,194,12,12,24,0,0,3,0.25,0,0,0,0,0.125,0,0.000000,148.957299,0.000000,0.000000,0.0,12.413108,6.206554,0.0,0.0,0.0,0.25,0,0.000000,NaN
78,2006-05-13,1172.4940,191,10.25,14.25,24.5,1,0.097561,1,0.070175,0,0,0,0,0.081633,0,164.744646,49.652433,0.000000,0.000000,16.072648,3.484381,8.750901,0.0,0.0,0.0,0.167736,0,0.581633,NaN
79,2006-05-14,1147.9200,196,8,13.75,21.75,0,0,3,0.218182,0,0,0,0,0.137931,0,0.000000,148.957299,0.000000,0.000000,0.0,10.833258,6.848611,0.0,0.0,0.0,0.218182,0,0.000000,NaN
80,2006-05-15,1337.2240,145,11.5,13.75,25.25,0,0,5,0.363636,0,0,0,0,0.19802,0,0.000000,248.262165,0.000000,0.000000,0.0,18.05543,9.832165,0.0,0.0,0.0,0.363636,0,0.000000,NaN
81,2006-05-16,2263.0470,76,12,14,26,1,0.083333,0,0,0,0,0,0,0.038462,0,164.744646,0.000000,0.000000,0.000000,13.72872,0.0,6.336333,0.0,0.0,0.0,0.083333,0,1.000000,NaN
82,2006-05-17,2787.4190,38.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,2006-05-18,2985.9200,37,9.75,12,21.75,4,0.410256,13,1.083333,0,0,0,0,0.781609,0,198.609732,273.972603,0.000000,0.000000,20.370229,22.83105,21.727923,0.0,0.0,0.0,1.49359,0,0.274678,NaN
84,2006-05-19,2778.8010,50,12,11,23,4,0.333333,8,0.727273,0,0,0,0,0.521739,0,198.609732,168.598525,0.000000,0.000000,16.550811,15.327139,15.965576,0.0,0.0,0.0,1.060606,0,0.314286,NaN
85,2006-05-20,2548.2980,50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,2006-05-21,2110.3740,51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,2006-05-22,2072.3720,55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,2006-05-23,2100.0000,60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,2006-05-24,2215.0000,79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,2006-05-25,1991.0000,97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,2006-05-26,1946.0000,64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,2006-05-27,2351.0000,77,10.25,13,23.25,36,3.512195,26,2,0,0,4,0.307692,2.666667,0.172043,5930.807249,1290.963257,0.000000,198.609732,578.615341,99.304866,310.613785,0.0,15.277672,8.542354,5.512195,0.307692,0.637168,0.000000
93,2006-05-28,5602.0000,69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,2006-05-29,5084.0000,69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,2006-05-30,3181.0000,60,9.75,11.75,21.5,3,0.307692,29,2.468085,329,33.74359,5075,431.914894,1.488372,251.348837,148.957299,1439.920556,16335.650447,251986.097319,15.277672,122.54643,73.901296,1675.451328,21445.625304,12480.081291,2.775777,465.658483,0.110849,0.072464
96,2006-05-31,2520.0000,90,12.75,10.5,23.25,0,0,10,0.952381,114,8.941176,1130,110.243902,0.430108,54.086957,0.000000,496.524330,18780.889621,56107.249255,0.0,47.288031,21.355885,1473.010951,5343.547548,3220.99522,0.952381,119.185079,0.000000,0.075019
97,2006-06-01,2560.0000,50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,2006-06-02,4287.0000,33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,2006-06-03,4508.0000,33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,2006-06-04,3942.0000,27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,2006-06-05,3915.0000,36,11.25,10.75,22,14,1.244444,14,1.302326,91,8.088889,250,23.255814,1.272727,15.5,695.134062,295.047418,4518.371400,5268.703899,61.789694,27.446271,45.008249,401.633013,490.111991,444.867059,2.54677,31.344703,0.488636,0.258062
102,2006-06-06,3016.0000,85,11.5,12,23.5,6,0.521739,9,0.75,55,4.782609,114,9.5,0.638298,7.191489,988.467875,446.871897,9060.955519,5660.377358,85.953728,37.239325,61.078288,787.909176,471.698113,626.439697,1.271739,14.282609,0.410256,0.334855
103,2006-06-07,2535.0000,90,12,11.75,23.75,0,0,4,0.340426,30,2.5,56,4.765957,0.168421,3.621053,0.000000,198.609732,4942.339374,2780.536246,0.0,16.902956,8.362515,411.861614,236.641383,325.17371,0.340426,7.265957,0.000000,0.344070
104,2006-06-08,2238.0000,100,12,11.5,23.5,0,0,5,0.434783,21,1.75,28,2.434783,0.212766,2.085106,0.000000,248.262165,3459.637562,1390.268123,0.0,21.588014,10.564347,288.30313,120.89288,206.378965,0.434783,4.184783,0.000000,0.418182
105,2006-06-09,2099.0000,75,12,12.5,24.5,0,0,0,0,27,2.25,41,3.28,0,2.77551,0.000000,0.000000,4448.105437,2035.749752,0.0,0.0,0.0,370.675453,162.85998,264.647151,0,5.53,NaN,0.406872
106,2006-06-10,2015.0000,70,11,12.75,23.75,0,0,0,0,18,1.636364,48,3.764706,0,2.778947,0.000000,0.000000,2965.403624,1011.591149,0.0,0.0,0.0,269.582148,79.340482,167.452411,0,5.40107,NaN,0.302970
107,2006-06-11,1903.0000,50,12.25,12.5,24.75,0,0,6,0.48,23,1.877551,39,3.12,0.242424,2.505051,0.000000,126.448894,1142.005958,821.917808,0.0,10.115911,5.109046,93.224976,65.753425,79.350455,0.48,4.997551,0.000000,0.375694
108,2006-06-12,2034.0000,65,14,14,28,2,0.142857,9,0.642857,17,1.214286,69,4.928571,0.392857,3.071429,329.489292,189.673340,2800.658979,1454.162276,23.534949,13.548096,18.541523,200.04707,103.868734,151.957902,0.785714,6.142857,0.181818,0.197674
109,2006-06-13,2325.0000,40,11.25,12,23.25,4,0.355556,9,0.75,26,2.311111,36,3,0.55914,2.666667,198.609732,189.673340,1290.963257,758.693361,17.654198,15.806112,16.700347,114.75229,63.224447,88.157274,1.105556,5.311111,0.321608,0.435146
110,2006-06-14,2316.0000,40,12.25,11,23.25,0,0,0,0,58,4.734694,113,10.272727,0,7.354839,0.000000,0.000000,2879.841112,2381.454162,0.0,0.0,0.0,235.08907,216.495833,226.29227,0,15.007421,NaN,0.315490
111,2006-06-15,2250.1390,52,12,11.75,23.75,6,0.5,12,1.021277,31,2.583333,38,3.234043,0.757895,2.905263,297.914598,252.897787,1539.225422,800.842993,24.826216,21.523216,23.1921,128.268785,68.15685,98.529196,1.521277,5.817376,0.328671,0.444072
112,2006-06-16,2299.0710,52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113,2006-06-17,2292.8830,44,12,12,24,4,0.333333,0,0,14,1.166667,15,1.25,0.166667,1.208333,198.609732,0.000000,695.134062,316.122234,16.550811,0.0,8.275405,57.927838,26.343519,42.135679,0.333333,2.416667,1.000000,0.482759
114,2006-06-18,1895.9180,40,11.75,12.5,24.25,0,0,4,0.32,17,1.446809,11,0.88,0.164948,1.154639,0.000000,84.299262,844.091360,231.822972,0.0,6.743941,3.476258,71.837563,18.545838,44.367601,0.32,2.326809,0.000000,0.621800
115,2006-06-19,1659.1270,80,12,11,23,1,0.083333,2,0.181818,3,0.25,3,0.272727,0.130435,0.26087,164.744646,42.149631,494.233937,63.224447,13.72872,3.831785,8.995403,41.186161,5.747677,24.237321,0.265152,0.522727,0.314286,0.478261
116,2006-06-20,1534.5730,97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,2006-06-21,1476.4280,72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
#save the data

df_subset.to_csv(data_string + "2006_puyallup.csv")

In [ ]:
#ask Andrew Berger about Jul 14 2006 - why total hours does not equal hours of day + hours of night?

In [30]:
#check if that is true for other files
data_2005  = pd.read_csv(data_string + "2005_puyallup.csv")
data_2004  = pd.read_csv(data_string + "2004_puyallup.csv")
# data_2004[data_2004['In'] != (data_2004['In_day'] + data_2004['In_night'])]
#looks like 'In' is 'In_day' + 'In_night' for 2004 and 2005